from .RasterToXarray import *
from _typeshed import Incomplete

__all__ = ['Subset', 'Aggregate', 'Foreach', 'Apply', 'Anomaly', 'Render', 'Clip', 'Merge', 'utils', 'RasterToXarray', 'XarrayToRaster']

def Subset(in_raster, variables=None, dimension_definitions=None): ...
def Aggregate(in_raster, dimension_name, raster_function, raster_function_arguments=None, aggregation_definition=None, dimensionless: bool = False): ...
def Foreach(in_raster, raster_function, raster_function_arguments=None): ...
def Apply(in_raster, raster_function, raster_function_arguments=None): ...
def Anomaly(in_raster, dimension_name: str = 'StdTime', anomaly_type: str = 'DIFFERENCE_FROM_MEAN', temporal_interval=None, ignore_nodata: bool = True): ...
def Render(in_raster, rendering_rule=None, colormap=None): ...
def Clip(in_raster, aoi): ...
def Merge(rasters, resolve_overlap: str = 'First'): ...

class Utilities:
    def GetStdTime(self, time_value, time_properties): ...
    def StandardizeMultidimensionalInfo(self, mdinfo): ...
    def ConstructSpatialReferenceFromParameters(self, srs_params): ...

utils: Incomplete

# Names in __all__ with no definition:
#   RasterToXarray
#   XarrayToRaster
