__all__ = ['Abs', 'ACos', 'ACosH', 'AggregateMultidimensionalRaster', 'AnalyzeChangesUsingCCDC', 'AnalyzeChangesUsingLandTrendr', 'ApplyGeometricTerrainCorrection', 'ApplyOrbitCorrection', 'ApplyRadiometricCalibration', 'ApplyRadiometricTerrainFlattening', 'ASin', 'ASinH', 'ATan', 'ATan2', 'ATanH', 'BitwiseAnd', 'BitwiseLeftShift', 'BitwiseNot', 'BitwiseOr', 'BitwiseRightShift', 'BitwiseXOr', 'BooleanAnd', 'BooleanNot', 'BooleanOr', 'BooleanXOr', 'CellStatistics', 'ClassifyObjectsUsingDeepLearning', 'ClassifyPixelsUsingDeepLearning', 'ClassifyRaster', 'ClassifyRasterUsingSpectra', 'CombinatorialAnd', 'CombinatorialOr', 'CombinatorialXOr', 'ComputeAccuracyForObjectDetection', 'ComputeChangeRaster', 'ComputeConfusionMatrix', 'ComputeSARIndices', 'ComputeSegmentAttributes', 'Con', 'ConvertSARUnits', 'Cos', 'CosH', 'CreateAccuracyAssessmentPoints', 'CreateBinaryMask', 'CreateColorComposite', 'Deburst', 'DeepLearningModelToEcd', 'Despeckle', 'DetectBrightOceanObjects', 'DetectChangeUsingChangeAnalysisRaster', 'DetectChangeUsingDeepLearning', 'DetectDarkOceanAreas', 'DetectObjectsUsingDeepLearning', 'DetectObjectsUsingText', 'Diff', 'DimensionalMovingStatistics', 'Divide', 'DownloadOrbitFile', 'EqualTo', 'Exp', 'Exp10', 'Exp2', 'ExportTrainingDataForDeepLearning', 'ExtractFeaturesUsingAIModels', 'ExtractVideoFramesToImages', 'ExtractWater', 'FindArgumentStatistics', 'Float', 'FocalStatistics', 'GenerateMultidimensionalAnomaly', 'GenerateTrainingSamplesFromSeedPoints', 'GenerateTrendRaster', 'GreaterThan', 'GreaterThanEqual', 'InList', 'InspectTrainingSamples', 'Int', 'InterpolateFromSpatiotemporalPoints', 'IsNull', 'LessThan', 'LessThanEqual', 'LinearSpectralUnmixing', 'Ln', 'Log10', 'Log2', 'Minus', 'Mod', 'MultidimensionalPrincipalComponents', 'MultidimensionalRasterCorrelation', 'Multilook', 'Negate', 'NonMaximumSuppression', 'NotEqual', 'OptimalInterpolation', 'Over', 'Pick', 'Plus', 'Power', 'PredictUsingRegressionModel', 'PredictUsingTrendRaster', 'RemoveRasterSegmentTilingArtifacts', 'RemoveThermalNoise', 'RoundDown', 'RoundUp', 'Sample', 'SegmentMeanShift', 'SetNull', 'Sin', 'SinH', 'Square', 'SquareRoot', 'SummarizeCategoricalRaster', 'Tan', 'TanH', 'Test', 'Times', 'TrainDeepLearningModel', 'TrainIsoClusterClassifier', 'TrainKNearestNeighborClassifier', 'TrainMaximumLikelihoodClassifier', 'TrainRandomTreesClassifier', 'TrainRandomTreesRegressionModel', 'TrainSupportVectorMachineClassifier', 'TrainUsingAutoDL', 'UpdateAccuracyAssessmentPoints', 'VideoMetadataToFeatureClass', 'VideoMultiplexer', 'WeightedSum', 'ZonalStatistics', 'ZonalStatisticsAsTable', 'ApplyEnvironment', 'FloatDivide', 'FloorDivide']

def Abs(in_raster_or_constant): ...
def ACos(in_raster_or_constant): ...
def ACosH(in_raster_or_constant): ...
def AggregateMultidimensionalRaster(in_multidimensional_raster, dimension, aggregation_method: str = '#', variables: str = '#', aggregation_def: str = '#', interval_keyword: str = '#', interval_value: str = '#', interval_unit: str = '#', interval_ranges: str = '#', aggregation_function: str = '#', ignore_nodata: str = '#', dimensionless: str = '#', percentile_value: str = '#', percentile_interpolation_type: str = '#'): ...
def AnalyzeChangesUsingCCDC(in_multidimensional_raster, bands: str = '#', tmask_bands: str = '#', chi_squared_threshold: str = '#', min_anomaly_observations: str = '#', update_frequency: str = '#'): ...
def AnalyzeChangesUsingLandTrendr(in_multidimensional_raster, processing_band: str = '#', snapping_date: str = '#', max_num_segments: str = '#', vertex_count_overshoot: str = '#', spike_threshold: str = '#', recovery_threshold: str = '#', prevent_one_year_recovery: str = '#', recovery_trend: str = '#', min_num_observations: str = '#', best_model_proportion: str = '#', pvalue_threshold: str = '#', output_other_bands: str = '#'): ...
def ApplyGeometricTerrainCorrection(in_radar_data, polarization_bands: str = '#', in_dem_raster: str = '#', geoid: str = '#'): ...
def ApplyOrbitCorrection(in_radar_data, in_orbit_file: str = '#', folder: str = '#'): ...
def ApplyRadiometricCalibration(in_radar_data, polarization_bands: str = '#', calibration_type: str = '#'): ...
def ApplyRadiometricTerrainFlattening(in_radar_data, in_dem_raster, geoid: str = '#', polarization_bands: str = '#', calibration_type: str = '#', out_scattering_area: str = '#', out_geometric_distortion: str = '#', out_geometric_distortion_mask: str = '#'): ...
def ASin(in_raster_or_constant): ...
def ASinH(in_raster_or_constant): ...
def ATan(in_raster_or_constant): ...
def ATan2(in_raster_or_constant1, in_raster_or_constant2): ...
def ATanH(in_raster_or_constant): ...
def BitwiseAnd(in_raster_or_constant1, in_raster_or_constant2): ...
def BitwiseLeftShift(in_raster_or_constant1, in_raster_or_constant2): ...
def BitwiseNot(in_raster_or_constant): ...
def BitwiseOr(in_raster_or_constant1, in_raster_or_constant2): ...
def BitwiseRightShift(in_raster_or_constant1, in_raster_or_constant2): ...
def BitwiseXOr(in_raster_or_constant1, in_raster_or_constant2): ...
def BooleanAnd(in_raster_or_constant1, in_raster_or_constant2): ...
def BooleanNot(in_raster_or_constant): ...
def BooleanOr(in_raster_or_constant1, in_raster_or_constant2): ...
def BooleanXOr(in_raster_or_constant1, in_raster_or_constant2): ...
def CellStatistics(in_rasters_or_constants, statistics_type: str = '#', ignore_nodata: str = '#', process_as_multiband: str = '#', percentile_value: str = '#', percentile_interpolation_type: str = '#'): ...
def ClassifyObjectsUsingDeepLearning(in_raster, out_feature_class, in_model_definition, in_features: str = '#', class_label_field: str = '#', processing_mode: str = '#', model_arguments: str = '#', caption_field: str = '#'): ...
def ClassifyPixelsUsingDeepLearning(in_raster, in_model_definition, arguments: str = '#', processing_mode: str = '#', out_classified_folder: str = '#', out_featureclass: str = '#', overwrite_attachments: str = '#', use_pixelspace: str = '#'): ...
def ClassifyRaster(in_raster, in_classifier_definition, in_additional_raster: str = '#'): ...
def ClassifyRasterUsingSpectra(in_raster, in_spectra_file, method: str = '#', thresholds: str = '#', out_score_raster: str = '#', out_classifier_definition: str = '#'): ...
def CombinatorialAnd(in_raster_or_constant1, in_raster_or_constant2): ...
def CombinatorialOr(in_raster_or_constant1, in_raster_or_constant2): ...
def CombinatorialXOr(in_raster_or_constant1, in_raster_or_constant2): ...
def ComputeAccuracyForObjectDetection(detected_features, ground_truth_features, out_accuracy_table, out_accuracy_report: str = '#', detected_class_value_field: str = '#', ground_truth_class_value_field: str = '#', min_iou: str = '#', mask_features: str = '#'): ...
def ComputeChangeRaster(from_raster, to_raster, compute_change_method: str = '#', from_classes: str = '#', to_classes: str = '#', filter_method: str = '#', define_transition_colors: str = '#', from_classname_field: str = '#', to_classname_field: str = '#'): ...
def ComputeConfusionMatrix(in_accuracy_assessment_points, out_confusion_matrix): ...
def ComputeSARIndices(in_radar_data, index: str = '#', polarization_bands: str = '#'): ...
def ComputeSegmentAttributes(in_segmented_raster, in_additional_raster: str = '#', used_attributes: str = '#'): ...
def Con(in_conditional_raster, in_true_raster_or_constant, in_false_raster_or_constant: str = '#', where_clause: str = '#'): ...
def ConvertSARUnits(in_radar_data, conversion_type: str = '#'): ...
def Cos(in_raster_or_constant): ...
def CosH(in_raster_or_constant): ...
def CreateAccuracyAssessmentPoints(in_class_data, out_points, target_field: str = '#', num_random_points: str = '#', sampling: str = '#', polygon_dimension_field: str = '#'): ...
def CreateBinaryMask(in_raster, background_value: str = '#', flood_fill: str = '#', expand_background: str = '#', expand_mask: str = '#', min_region_size: str = '#', background_nodata: str = '#'): ...
def CreateColorComposite(in_raster, method, red_expression, green_expression, blue_expression): ...
def Deburst(in_radar_data, polarization_bands: str = '#'): ...
def DeepLearningModelToEcd(in_deep_learning_model, in_classification_info_json, out_classifier_definition): ...
def Despeckle(in_radar_data, polarization_bands: str = '#', filter_type: str = '#', filter_size: str = '#', noise_model: str = '#', noise_variance: str = '#', add_noise_mean: str = '#', mult_noise_mean: str = '#', number_of_looks: str = '#', damp_factor: str = '#'): ...
def DetectBrightOceanObjects(in_radar_data, out_feature_class, out_type: str = '#', min_object_width: str = '#', max_object_width: str = '#', min_object_length: str = '#', max_object_length: str = '#', mask_features: str = '#', feature_type: str = '#', in_dem_raster: str = '#', geoid: str = '#', mask_tolerance: str = '#'): ...
def DetectChangeUsingChangeAnalysisRaster(in_change_analysis_raster, change_type, max_number_changes: str = '#', segment_date: str = '#', change_direction: str = '#', filter_by_year: str = '#', min_year: str = '#', max_year: str = '#', filter_by_duration: str = '#', min_duration: str = '#', max_duration: str = '#', filter_by_magnitude: str = '#', min_magnitude: str = '#', max_magnitude: str = '#', filter_by_start_value: str = '#', min_start_value: str = '#', max_start_value: str = '#', filter_by_end_value: str = '#', min_end_value: str = '#', max_end_value: str = '#'): ...
def DetectChangeUsingDeepLearning(from_raster, to_raster, in_model_definition, arguments: str = '#'): ...
def DetectDarkOceanAreas(in_radar_data, min_area: str = '#', mask_features: str = '#', feature_type: str = '#', in_dem_raster: str = '#', geoid: str = '#', mask_tolerance: str = '#'): ...
def DetectObjectsUsingDeepLearning(in_raster, out_detected_objects, in_model_definition, arguments: str = '#', run_nms: str = '#', confidence_score_field: str = '#', class_value_field: str = '#', max_overlap_ratio: str = '#', processing_mode: str = '#', use_pixelspace: str = '#'): ...
def DetectObjectsUsingText(input_raster_dataset, output_feature_class, class_name: str = '#', box_threshold: str = '#', text_threshold: str = '#'): ...
def Diff(in_raster_or_constant1, in_raster_or_constant2): ...
def DimensionalMovingStatistics(in_raster, dimension: str = '#', backward_window: str = '#', forward_window: str = '#', nodata_handling: str = '#', statistics_type: str = '#', percentile_value: str = '#', percentile_interpolation_type: str = '#', circular_wrap_value: str = '#'): ...
def Divide(in_raster_or_constant1, in_raster_or_constant2): ...
def DownloadOrbitFile(in_radar_data, orbit_type: str = '#', username: str = '#', password: str = '#', cloud_storage: str = '#', folder: str = '#'): ...
def EqualTo(in_raster_or_constant1, in_raster_or_constant2): ...
def Exp(in_raster_or_constant): ...
def Exp10(in_raster_or_constant): ...
def Exp2(in_raster_or_constant): ...
def ExportTrainingDataForDeepLearning(in_raster, out_folder, in_class_data: str = '#', image_chip_format: str = '#', tile_size_x: str = '#', tile_size_y: str = '#', stride_x: str = '#', stride_y: str = '#', output_nofeature_tiles: str = '#', metadata_format: str = '#', start_index: str = '#', class_value_field: str = '#', buffer_radius: str = '#', in_mask_polygons: str = '#', rotation_angle: str = '#', reference_system: str = '#', processing_mode: str = '#', blacken_around_feature: str = '#', crop_mode: str = '#', in_raster2: str = '#', in_instance_data: str = '#', instance_class_value_field: str = '#', min_polygon_overlap_ratio: str = '#'): ...
def ExtractFeaturesUsingAIModels(in_raster, mode, out_location, out_prefix, area_of_interest: str = '#', pretrained_models: str = '#', additional_models: str = '#', confidence_threshold: str = '#', save_intermediate_output: str = '#', test_time_augmentation: str = '#', buffer_distance: str = '#', extend_length: str = '#', smoothing_tolerance: str = '#', dangle_length: str = '#', in_road_features: str = '#', road_buffer_width: str = '#', regularize_parcels: str = '#', post_processing_workflow: str = '#', out_features: str = '#', parcel_tolerance: str = '#', regularization_method: str = '#', poly_tolerance: str = '#', prompt: str = '#', in_features: str = '#', out_summary: str = '#'): ...
def ExtractVideoFramesToImages(in_video, out_folder, image_type: str = '#', image_overlap: str = '#', require_fresh_metadata: str = '#', min_time: str = '#'): ...
def ExtractWater(in_radar_data, out_feature_class, min_area: str = '#', in_dem_raster: str = '#', geoid: str = '#'): ...
def FindArgumentStatistics(in_raster, dimension: str = '#', dimension_def: str = '#', interval_keyword: str = '#', variables: str = '#', statistics_type: str = '#', min: str = '#', max: str = '#', multiple_occurrence: str = '#', ignore_nodata: str = '#', value: str = '#', comparison: str = '#', occurrence: str = '#'): ...
def Float(in_raster_or_constant): ...
def FocalStatistics(in_raster, neighborhood: str = '#', statistics_type: str = '#', ignore_nodata: str = '#', percentile_value: str = '#'): ...
def GenerateMultidimensionalAnomaly(in_multidimensional_raster, variables: str = '#', method: str = '#', calculation_interval: str = '#', ignore_nodata: str = '#', reference_mean_raster: str = '#'): ...
def GenerateTrainingSamplesFromSeedPoints(in_class_data, in_seed_points, out_training_feature_class, min_sample_area: str = '#', max_sample_radius: str = '#'): ...
def GenerateTrendRaster(in_multidimensional_raster, dimension, variables: str = '#', line_type: str = '#', frequency: str = '#', ignore_nodata: str = '#', cycle_length: str = '#', cycle_unit: str = '#', rmse: str = '#', r2: str = '#', slope_p_value: str = '#', seasonal_period: str = '#'): ...
def GreaterThan(in_raster_or_constant1, in_raster_or_constant2): ...
def GreaterThanEqual(in_raster_or_constant1, in_raster_or_constant2): ...
def InList(in_raster_or_constant, in_raster_or_constants, process_as_multiband: str = '#'): ...
def InspectTrainingSamples(in_raster, in_training_features, in_classifier_definition, out_training_feature_class, in_additional_raster: str = '#'): ...
def Int(in_raster_or_constant): ...
def InterpolateFromSpatiotemporalPoints(in_dataset, variable_field, time_field, temporal_aggregation, cell_size, interpolation_method): ...
def IsNull(in_raster): ...
def LessThan(in_raster_or_constant1, in_raster_or_constant2): ...
def LessThanEqual(in_raster_or_constant1, in_raster_or_constant2): ...
def LinearSpectralUnmixing(in_raster, in_spectral_profile_file, value_option: str = '#'): ...
def Ln(in_raster_or_constant): ...
def Log10(in_raster_or_constant): ...
def Log2(in_raster_or_constant): ...
def Minus(in_raster_or_constant1, in_raster_or_constant2): ...
def Mod(in_raster_or_constant1, in_raster_or_constant2): ...
def MultidimensionalPrincipalComponents(in_multidimensional_raster, mode, dimension, out_pc, out_loadings, out_eigenvalues: str = '#', variable: str = '#', number_of_pc: str = '#'): ...
def MultidimensionalRasterCorrelation(in_mdim_raster1, in_mdim_raster2, dimension1: str = '#', variable1: str = '#', dimension2: str = '#', variable2: str = '#', corr_method: str = '#', lag: str = '#', calculate_xcorr: str = '#', calculate_pvalue: str = '#', out_max_corr_raster: str = '#'): ...
def Multilook(in_radar_data, polarization_bands: str = '#', range_looks: str = '#', azimuth_looks: str = '#'): ...
def Negate(in_raster_or_constant): ...
def NonMaximumSuppression(in_featureclass, confidence_score_field, out_featureclass, class_value_field: str = '#', max_overlap_ratio: str = '#'): ...
def NotEqual(in_raster_or_constant1, in_raster_or_constant2): ...
def OptimalInterpolation(in_background_raster, in_obs_data, obs_field, background_error_var, obs_error_var, background_error_corr_length: str = '#'): ...
def Over(in_raster_or_constant1, in_raster_or_constant2): ...
def Pick(in_position_raster, in_rasters_or_constants, process_as_multiband: str = '#'): ...
def Plus(in_raster_or_constant1, in_raster_or_constant2): ...
def Power(in_raster_or_constant1, in_raster_or_constant2): ...
def PredictUsingRegressionModel(in_rasters, in_regression_definition): ...
def PredictUsingTrendRaster(in_multidimensional_raster, variables: str = '#', dimension_def: str = '#', dimension_values: str = '#', start: str = '#', end: str = '#', interval_value: str = '#', interval_unit: str = '#'): ...
def RemoveRasterSegmentTilingArtifacts(in_segmented_raster, tileSizeX: str = '#', tileSizeY: str = '#'): ...
def RemoveThermalNoise(in_radar_data, polarization_bands: str = '#'): ...
def RoundDown(in_raster_or_constant): ...
def RoundUp(in_raster_or_constant): ...
def Sample(in_rasters, in_location_data, out_table, resampling_type: str = '#', unique_id_field: str = '#', process_as_multidimensional: str = '#', acquisition_definition: str = '#', statistics_type: str = '#', percentile_value: str = '#', buffer_distance: str = '#', layout: str = '#', generate_feature_class: str = '#'): ...
def SegmentMeanShift(in_raster, spectral_detail: str = '#', spatial_detail: str = '#', min_segment_size: str = '#', band_indexes: str = '#', max_segment_size: str = '#'): ...
def SetNull(in_conditional_raster, in_false_raster_or_constant, where_clause: str = '#'): ...
def Sin(in_raster_or_constant): ...
def SinH(in_raster_or_constant): ...
def Square(in_raster_or_constant): ...
def SquareRoot(in_raster_or_constant): ...
def SummarizeCategoricalRaster(in_raster, out_table, dimension: str = '#', aoi: str = '#', aoi_id_field: str = '#'): ...
def Tan(in_raster_or_constant): ...
def TanH(in_raster_or_constant): ...
def Test(in_raster, where_clause): ...
def Times(in_raster_or_constant1, in_raster_or_constant2): ...
def TrainDeepLearningModel(in_folder, out_folder, max_epochs: str = '#', model_type: str = '#', batch_size: str = '#', arguments: str = '#', learning_rate: str = '#', backbone_model: str = '#', pretrained_model: str = '#', validation_percentage: str = '#', stop_training: str = '#', freeze: str = '#', augmentation: str = '#', augmentation_parameters: str = '#', chip_size: str = '#', resize_to: str = '#', weight_init_scheme: str = '#', monitor: str = '#'): ...
def TrainIsoClusterClassifier(in_raster, max_classes, out_classifier_definition, in_additional_raster: str = '#', max_iterations: str = '#', min_samples_per_cluster: str = '#', skip_factor: str = '#', used_attributes: str = '#', max_merge_per_iter: str = '#', max_merge_distance: str = '#'): ...
def TrainKNearestNeighborClassifier(in_raster, in_training_features, out_classifier_definition, in_additional_raster: str = '#', kNN: str = '#', max_samples_per_class: str = '#', used_attributes: str = '#', dimension_value_field: str = '#'): ...
def TrainMaximumLikelihoodClassifier(in_raster, in_training_features, out_classifier_definition, in_additional_raster: str = '#', used_attributes: str = '#', dimension_value_field: str = '#'): ...
def TrainRandomTreesClassifier(in_raster, in_training_features, out_classifier_definition, in_additional_raster: str = '#', max_num_trees: str = '#', max_tree_depth: str = '#', max_samples_per_class: str = '#', used_attributes: str = '#', dimension_value_field: str = '#'): ...
def TrainRandomTreesRegressionModel(in_rasters, in_target_data, out_regression_definition, target_value_field: str = '#', target_dimension_field: str = '#', raster_dimension: str = '#', out_importance_table: str = '#', max_num_trees: str = '#', max_tree_depth: str = '#', max_samples: str = '#', average_points_per_cell: str = '#', percent_testing: str = '#', out_scatterplots: str = '#', out_sample_features: str = '#'): ...
def TrainSupportVectorMachineClassifier(in_raster, in_training_features, out_classifier_definition, in_additional_raster: str = '#', max_samples_per_class: str = '#', used_attributes: str = '#', dimension_value_field: str = '#'): ...
def TrainUsingAutoDL(in_data, out_model, pretrained_model: str = '#', total_time_limit: str = '#', autodl_mode: str = '#', networks: str = '#', save_evaluated_models: str = '#'): ...
def UpdateAccuracyAssessmentPoints(in_class_data, in_points, out_points, target_field: str = '#', polygon_dimension_field: str = '#', point_dimension_field: str = '#'): ...
def VideoMetadataToFeatureClass(in_video, csv_file: str = '#', flightpath: str = '#', flightpath_type: str = '#', imagepath: str = '#', imagepath_type: str = '#', footprint: str = '#', start_time: str = '#', stop_time: str = '#', min_distance: str = '#', min_time: str = '#', vmti: str = '#'): ...
def VideoMultiplexer(in_video_file, metadata_file, out_video_file, metadata_mapping_file: str = '#', timeshift_file: str = '#', elevation_layer: str = '#'): ...
def WeightedSum(in_weighted_sum_table): ...
def ZonalStatistics(in_zone_data, zone_field, in_value_raster, statistics_type: str = '#', ignore_nodata: str = '#', process_as_multidimensional: str = '#', percentile_value: str = '#', percentile_interpolation_type: str = '#', circular_calculation: str = '#', circular_wrap_value: str = '#'): ...
def ZonalStatisticsAsTable(in_zone_data, zone_field, in_value_raster, out_table, ignore_nodata: str = '#', statistics_type: str = '#', process_as_multidimensional: str = '#', percentile_values: str = '#', percentile_interpolation_type: str = '#', circular_calculation: str = '#', circular_wrap_value: str = '#', out_join_layer: str = '#'): ...
def ApplyEnvironment(in_raster): ...
def FloatDivide(in_raster_or_constant1, in_raster_or_constant2): ...
def FloorDivide(in_raster_or_constant1, in_raster_or_constant2): ...
