from arcpy.ia import Apply as Apply

__all__ = ['ApparentReflectance', 'Apply', 'ArgStatistics', 'Arithmetic', 'Aspect', 'AspectSlope', 'BandArithmetic', 'BAI', 'Buffered', 'CIg', 'CIre', 'Classify', 'ClayMinerals', 'Colormap', 'ColormapToRGB', 'ColorspaceConversion', 'Complex', 'CompositeBand', 'ComputeChange', 'Contour', 'ContrastBrightness', 'Convolution', 'Curvature', 'DetectChangeUsingChangeAnalysis', 'EVI', 'ElevationVoidFill', 'EqualToFrequency', 'ExtractBand', 'FerrousMinerals', 'GEMI', 'GenerateTrend', 'Geometric', 'GeometricMedian', 'GNDVI', 'GVITM', 'Gradient', 'Grayscale', 'GreaterThanFrequency', 'HeatIndex', 'HighestPosition', 'Hillshade', 'InterpolateRasterByDimension', 'IronOxide', 'LabelBadBands', 'LessThanFrequency', 'LinearUnmixing', 'Lookup', 'LowestPosition', 'MLClassify', 'MNDWI', 'MSAVI', 'MTVI2', 'Mask', 'Majority', 'Max', 'Mean', 'Median', 'Min', 'Minority', 'NBR', 'NDBI', 'NDMI', 'NDSI', 'NDVI', 'NDVIre', 'NDWI', 'PVI', 'Pansharpen', 'Percentile', 'Popularity', 'PredictUsingTrend', 'RTVICore', 'RadarCalibration', 'Range', 'Rank', 'RasterCalculator', 'RasterizeFeatures', 'RegionGrow', 'RegionPixelCount', 'Remap', 'Reproject', 'Resample', 'S1RadiometricCalibration', 'S1ThermalNoiseRemoval', 'SAVI', 'SR', 'SRre', 'SegMeanShift', 'ShadedRelief', 'Slope', 'Speckle', 'SpectralConversion', 'Statistics', 'StatisticsHistogram', 'StdDev', 'Stretch', 'SubsetBands', 'Sultan', 'Sum', 'TSAVI', 'TasseledCap', 'Threshold', 'TransposeBits', 'TrendToRGB', 'UnitConversion', 'VARI', 'Variety', 'VectorField', 'VectorFieldRenderer', 'WindChill', 'ZonalRemap']

def Grayscale(raster, conversion_parameters=None): ...
def Arithmetic(raster1, raster2, operation_type: str = 'Plus', extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
def ArgStatistics(rasters, stat_type=None, min_value=None, max_value=None, multiple_occurrence_value: int = 100, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
def Aspect(raster): ...
def BandArithmetic(raster, band_ids, method: int = 1): ...
def BAI(raster, red_band_id: int = 3, nir_band_id: int = 4): ...
def CIg(raster, nir_band_id: int = 7, green_band_id: int = 3): ...
def CIre(raster, nir_band_id: int = 7, redEdge_band_id: int = 6): ...
def ClayMinerals(raster, swir1_band_id: int = 6, swir2_band_id: int = 7): ...
def ColorspaceConversion(raster, conversion_type: str = 'rgb_to_hsv'): ...
def ColormapToRGB(raster): ...
def Colormap(raster, colormap=None, colorramp=None): ...
def Complex(raster): ...
def CompositeBand(rasters): ...
def ContrastBrightness(raster, contrast_offset: int = 0, brightness_offset: int = 0): ...
def Convolution(raster, kernel=None): ...
def Curvature(raster, curvature_type: str = 'standard', z_factor: int = 1): ...
def ElevationVoidFill(raster, max_void_width: int = 0): ...
def ExtractBand(raster, band_ids=None, band_names=None, band_wavelengths=None, missing_band_action: str = 'BestMatch', wavelength_match_tolerance=None): ...
def EVI(raster, nir_band_id: int = 5, red_band_id: int = 4, blue_band_id: int = 2): ...
def FerrousMinerals(raster, swir_band_id: int = 6, nir_band_id: int = 5): ...
def Statistics(raster, kernel_columns: int = 3, kernel_rows: int = 3, stat_type=None, fill_no_data_only: bool = False): ...
def Hillshade(dem, azimuth: float = 315.0, altitude: float = 45.0, z_factor: int = 1, slope_type: int = 1, ps_power: float = 0.664, psz_factor: float = 0.024, remove_edge_effect: bool = False, hillshade_type: int = 0): ...
def GEMI(raster, nir_band_id: int = 4, red_band_id: int = 3): ...
def GNDVI(raster, nir_band_id: int = 4, green_band_id: int = 2): ...
def GVITM(raster, band1_id: int = 1, band2_id: int = 2, band3_id: int = 3, band4_id: int = 4, band5_id: int = 5, band7_id: int = 7): ...
def IronOxide(raster, red_band_id: int = 4, blue_band_id: int = 2): ...
def Lookup(raster, field=None): ...
def Mask(raster, no_data_values=None, included_ranges=None, no_data_interpretation=None): ...
def MLClassify(raster, signature): ...
def MNDWI(raster, green_band_id: int = 3, swir_band_id: int = 6): ...
def MSAVI(raster, nir_band_id: int = 4, red_band_id: int = 3): ...
def MTVI2(raster, nir_band_id: int = 7, red_band_id: int = 5, green_band_id: int = 3): ...
def NBR(raster, swir_band_id: int = 7, nir_band_id: int = 5): ...
def NDBI(raster, swir_band_id: int = 6, nir_band_id: int = 5): ...
def NDMI(raster, nir_band_id: int = 5, swir1_band_id: int = 6): ...
def NDSI(raster, green_band_id: int = 4, swir_band_id: int = 6): ...
def NDVI(raster, nir_band_id: int = 4, red_band_id: int = 3): ...
def NDVIre(raster, nir_band_id: int = 7, redEdge_band_id: int = 6): ...
def NDWI(raster, nir_band_id: int = 5, green_band_id: int = 3): ...
def Pansharpen(pan_raster, ms_raster, ir_raster=None, fourth_band_of_ms_is_ir: bool = True, weights=[0.166, 0.167, 0.167, 0.5], type: str = 'ESRI', sensor=None): ...
def PVI(raster, nir_band_id: int = 4, red_band_id: int = 3, a: float = 0.3, b: float = 0.5): ...
def RasterCalculator(rasters, input_names, expression, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
def Remap(raster, input_ranges=None, output_values=None, no_data_ranges=None, allow_unmatched: bool = False, replacement_value=None): ...
def Resample(raster, resampling_type=None, input_cellsize=None, output_cellsize=None): ...
def RTVICore(raster, nir_band_id: int = 7, redEdge_band_id: int = 6, green_band_id: int = 3): ...
def SAVI(raster, nir_band_id: int = 4, red_band_id: int = 3, l: float = 0.33): ...
def ShadedRelief(raster, azimuth: int = 315, altitude: int = 45, z_factor: int = 1, colormap=None, colorramp: str = 'Elevation #1', slope_type: str = 'DEGREE', ps_power: float = 0.664, psz_factor: float = 0.024, remove_edge_effect: bool = False): ...
def Slope(dem, z_factor: int = 1, slope_type: str = 'DEGREE', ps_power: float = 0.664, psz_factor: float = 0.024, remove_edge_effect: bool = False): ...
def Speckle(raster, filter_type: str = 'Lee', filter_size: str = '3x3', noise_model: str = 'Multiplicative', noise_var=None, additive_noise_mean=None, multiplicative_noise_mean: int = 1, nlooks: int = 1, damp_factor=None): ...
def SpectralConversion(raster, conversion_matrix): ...
def SR(raster, nir_band_id: int = 5, red_band_id: int = 4): ...
def SRre(raster, nir_band_id: int = 7, redEdge_band_id: int = 6): ...
def StatisticsHistogram(raster, statistics=None, histograms=None): ...
def Stretch(raster, stretch_type: str = 'None', min: int = 0, max: int = 255, num_stddev: int = 2, statistics=None, dra: bool = False, min_percent: float = 0.25, max_percent: float = 0.5, gamma=None, compute_gamma: bool = False, sigmoid_strength_level: int = 2): ...
def Sultan(raster, band1_id: int = 1, band3_id: int = 3, band4_id: int = 4, band5_id: int = 5, band6_id: int = 6): ...
def TasseledCap(raster): ...
def Threshold(raster): ...
def TransposeBits(raster, input_bit_positions=[12, 13], output_bit_positions=[0, 1], constant_fill_value: int = 0, fill_raster=None): ...
def TSAVI(raster, nir_band_id: int = 4, red_band_id: int = 3, s: float = 0.33, a: float = 0.5, X: float = 1.5): ...
def UnitConversion(raster, from_unit=None, to_unit=None): ...
def VARI(raster, red_band_id: int = 3, green_band_id: int = 2, blue_band_id: int = 1): ...
def VectorField(raster_u_mag, raster_v_dir, input_data_type: str = 'Vector-UV', angle_reference_system: str = 'Geographic', output_data_type: str = 'Vector-UV'): ...
def VectorFieldRenderer(raster, is_uv_components=None, reference_system: str = 'Geographic', mass_flow_angle_representation: str = 'From', calculation_method: str = 'Vector Average', symbology_name: str = 'Single Arrow'): ...
def AspectSlope(raster, z_factor: int = 1): ...
def HeatIndex(temperature_raster, relative_humidity_raster, temperature_unit: str = 'Fahrenheit', heat_index_unit: str = 'Fahrenheit'): ...
def WindChill(temperature_raster, wind_speed_raster, temperature_units: str = 'Fahrenheit', wind_speed_units: str = 'mph', wind_chill_units: str = 'Fahrenheit'): ...
def Contour(raster, adaptive_smoothing: float = 2.5, contour_type: str = 'contour lines', z_base: int = 0, number_of_contours: int = 0, contour_interval: int = 100, nth_contour_line_in_bold: int = 5, z_factor: int = 1): ...
def PredictUsingTrend(raster, dimension_definition_type: str = 'BY_VALUE', dimension_values=None, start=None, end=None, interval_value: int = 1, interval_unit: str = 'HOURS'): ...
def GenerateTrend(raster, dimension_name, regression_type: str = 'LINEAR', cycle_length: int = 1, cycle_unit: str = 'YEARS', harmonic_frequency: int = 1, polynomial_order: int = 2, ignore_nodata: bool = True, rmse: bool = True, r2: bool = False, slope_p_value: bool = False, seasonal_period: str = 'DAYS'): ...
def TrendToRGB(raster, model_type: str = 'LINEAR'): ...
def Classify(raster1, raster2=None, classifier_definition=None): ...
def SegMeanShift(raster, spectral_detail=None, spatial_detail=None, spectral_radius=None, spatial_radius=None, min_num_pixels_per_segment=None): ...
def S1RadiometricCalibration(raster, calibration_type=None): ...
def S1ThermalNoiseRemoval(raster, calibration_type=None): ...
def RadarCalibration(raster, calibration_type=None): ...
def ApparentReflectance(raster, radiance_gain_values=None, radiance_bias_values=None, reflectance_gain_values=None, reflectance_bias_values=None, sun_elevation=None, albedo: bool = False, scale_factor=None, offset=None): ...
def Geometric(raster, geodata_transforms=None, append_geodata_xform: bool = False, z_factor=None, z_offset=None, constant_z=None, correct_geoid: bool = False, tolerance=None, dem=None): ...
def Buffered(raster): ...
def Reproject(raster, spatial_reference=None, x_cell_size: int = 0, y_cell_size: int = 0, x_registration_point: int = 0, y_registration_point: int = 0): ...
def RasterizeFeatures(raster, feature_class, class_index_field=None, resolve_overlap_method: str = 'FIRST'): ...
def RegionGrow(raster, seed_points, max_growth_radius_field, similarity_threshold_field, fill_value_field=None): ...
def ZonalRemap(raster, zonal_attribute_table, zone_raster=None, zone_field: str = 'ZoneID', min_value_field_name: str = 'ZoneMin', max_value_field_name: str = 'ZoneMax', output_value_field_name: str = 'ZoneValue', background_value: int = 0, default_output_value: int = 255, where_clause=None): ...
def LinearUnmixing(raster, spectral_profile_file=None, spectral_profile_def=None, training_feature=None, non_negative: bool = False, sum_to_one: bool = False): ...
def ComputeChange(raster1, raster2, method: str = 'DIFFERENCE', from_class_values=[], to_class_values=[], filter_method: str = 'CHANGED_PIXELS_ONLY', define_transition_colors: str = 'AVERAGE', extent_type: str = 'IntersectionOf', cellsize_type: str = 'MaxOf', from_class_name_field_name=None, to_class_name_field_name=None): ...
def DetectChangeUsingChangeAnalysis(raster, change_type: str = 'TIME_OF_LATEST_CHANGE', max_number_of_changes: int = 1, segment_date: str = 'BEGINNING_OF_SEGMENT', change_direction: str = 'ALL', filter_by_year: bool = False, min_year: int = 1970, max_year: int = 2020, filter_by_duration: bool = False, min_duration: int = 0, max_duration: int = 50, filter_by_magnitude: bool = False, min_magnitude: int = -50, max_magnitude: int = 50, filter_by_start_value: bool = False, min_start_value=None, max_start_value=None, filter_by_end_value: bool = False, min_end_value=None, max_end_value=None): ...
def InterpolateRasterByDimension(raster, interpolation_method: str = 'LINEAR', variables=None, dimension_definition=None, dimension_values=None, dimension=None, start_value=None, end_value=None, interval_value=None, interval_unit=None, target_raster=None, ignore_nodata: bool = True): ...
def Max(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Mean(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Median(rasters, percentile_interpolation_type: str = 'AUTO_DETECT', extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Min(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Minority(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Majority(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Range(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def StdDev(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Sum(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Variety(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def Percentile(rasters, percentile_value: int = 90, percentile_interpolation_type: str = 'AUTO_DETECT', extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', ignore_nodata: bool = False, process_as_multiband=None): ...
def GeometricMedian(rasters, epsilon: float = 0.001, max_iteration: int = 10, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
def EqualToFrequency(value_raster, rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', process_as_multiband=None): ...
def GreaterThanFrequency(value_raster, rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', process_as_multiband=None): ...
def LessThanFrequency(value_raster, rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', process_as_multiband=None): ...
def HighestPosition(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
def LowestPosition(rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
def Popularity(popularity_raster, rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', process_as_multiband=None): ...
def Rank(rank_raster, rasters, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf', process_as_multiband=None): ...
def RegionPixelCount(raster, max_region_size: int = 100, pixel_neighborhood: int = 4): ...
def Gradient(raster, gradient_dimension: str = 'X', denominator_unit: str = 'DEFAULT'): ...
def SubsetBands(raster, method: str = 'BY_IDS', bands=None, missing_band_action: str = 'BestMatch', exclude_bad_bands: bool = False): ...
def LabelBadBands(raster, method: str = 'BY_IDS', bands=None): ...
