from .util import ArcpyHandler as ArcpyHandler, convert_string_to_date_time as convert_string_to_date_time, get_geometry as get_geometry
from _typeshed import Incomplete
from arcpy.ia import Apply as Apply, CompositeBand as CompositeBand, Merge as Merge
from datetime import datetime as datetime

THRESHOLD: int

class _RasterCollectionCursor:
    def __init__(self, data_frame) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __next__(self): ...

class RasterCollection:
    def __init__(self, rasters, attribute_dict: Incomplete | None = None, where_clause: Incomplete | None = None, query_geometry: Incomplete | None = None) -> None: ...
    def filter(self, where_clause: str = '', query_geometry_or_extent: Incomplete | None = None, raster_query: str = ''): ...
    @property
    def fields(self): ...
    @property
    def count(self): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, item): ...
    def filterByTime(self, start_time: str = '', end_time: str = '', time_field_name: str = 'StdTime', date_time_format: Incomplete | None = None): ...
    def filterByGeometry(self, query_geometry_or_extent: Incomplete | None = None): ...
    def filterByAttribute(self, field_name, operator, field_values): ...
    def sort(self, field_name, ascending: bool = True): ...
    def getFieldValues(self, field_name, max_count: int = 0): ...
    def toMultidimensionalRaster(self, variable_field_name: str = '', dimension_field_names: str = ''): ...
    def max(self, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
    def min(self, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
    def median(self, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
    def mean(self, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
    def majority(self, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
    def sum(self, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
    def std(self, ignore_nodata: bool = True, extent_type: str = 'FirstOf', cellsize_type: str = 'FirstOf'): ...
    def mosaic(self, mosaic_method: str = 'FIRST'): ...
    def qualityMosaic(self, quality_rc_or_list, statistic_type: str = 'MAX'): ...
    def selectBands(self, band_ids_or_names): ...
    def map(self, func): ...
    def filterByRasterProperty(self, property_name, operator, property_values): ...
    def filterByCalendarRange(self, calendar_field, start, end: Incomplete | None = None, time_field_name: str = 'StdTime', date_time_format: Incomplete | None = None): ...
    def summarizeField(self, field_name, summary_type: str = 'ALL'): ...
    def merge(self, collection2): ...
    def reduce(self, func, func_args={}): ...
    def addField(self, field_name, field_values): ...
    def groupBy(self, field_name): ...
    def findImages(self, from_geometry: Incomplete | None = None, to_geometry: Incomplete | None = None, object_ids: Incomplete | None = None, where_clause: Incomplete | None = None, query_geometry_or_extent: Incomplete | None = None, raster_query: Incomplete | None = None, max_count: Incomplete | None = None): ...
    def imageToMap(self, geometry, raster_id, options: Incomplete | None = None): ...
    def mapToImage(self, geometry, raster_id, options: Incomplete | None = None): ...
    def getImageURL(self, image_uri): ...
    def measure(self, from_geometry: Incomplete | None = None, to_geometry: Incomplete | None = None, raster_id: Incomplete | None = None): ...
    def imageToMapMultiray(self, geometries, raster_ids): ...
    @staticmethod
    def fromSTACAPI(stac_api, query: Incomplete | None = None, attribute_dict: Incomplete | None = None, request_method: str = 'POST', request_params: Incomplete | None = None, context: Incomplete | None = None): ...
    @staticmethod
    def fromSTACCatalog(stac_catalog, attribute_dict: Incomplete | None = None, request_params: Incomplete | None = None, context: Incomplete | None = None): ...
