import logging
from _typeshed import Incomplete

def get_aoi(aoi): ...
def get_geometry(data): ...
def convert_string_to_date_time(date_time_value, date_time_format: Incomplete | None = None, drop_tzinfo: bool = False): ...

class ArcpyHandler(logging.Handler):
    def __init__(self, level: int = 10) -> None: ...
    def emit(self, record) -> None: ...

def get_available_device(max_memory: float = 0.8): ...
def get_available_device_with_nvml(max_memory: float = 0.8): ...
