from arcpy.toolbox import *
from arcpy.arcobjects import *
from .cmanagers import EnvManager as EnvManager, LogHistory as LogHistory, LogMetadata as LogMetadata, SeverityLevel as SeverityLevel
from _typeshed import Incomplete
from arcgisscripting import ExecuteError as ExecuteError, ExecuteWarning as ExecuteWarning
from arcpy import metadata as metadata, mp as mp, nax as nax, sharing as sharing, wmx as wmx
from arcpy._aio import AIO as AIO, AIOFileOpen as AIOFileOpen, CloudPathType as CloudPathType
from arcpy._version import __version__ as __version__, version as version
from arcpy.charts import Chart as Chart, Guide as Guide, TimeBinningProperties as TimeBinningProperties
from arcpy.geoprocessing import env as env, gp as gp
from arcpy.ia import Mensuration as Mensuration, Render as Render
from arcpy.ia.util import GetSTACInfo as GetSTACInfo
from arcpy.sa import Raster as Raster, RasterInfo as RasterInfo

msg: str
fnf_exception: Incomplete
READ_ACCESS: Incomplete
root_keys: Incomplete
reg_path: str
key: Incomplete
install_dir: Incomplete
local_appdata: Incomplete
uuid_paths: Incomplete
module_paths: Incomplete
addin_toolbox_path: Incomplete
sitepackpths: Incomplete
loader: Incomplete
alias: Incomplete

def ImportToolbox(input_file, module_name=None): ...

modulename: Incomplete
filename: Incomplete
item: Incomplete
filepath: Incomplete

def GetInstallInfo(product=None): ...
def GetPackageInfo(filename): ...
def ListInstallations(): ...
def SetProgressor(type, message=None, min_range=None, max_range=None, step_value=None): ...
def ResetProgressor(): ...
def SetProgressorLabel(label): ...
def SetProgressorPosition(position=None): ...
def ResetEnvironments(): ...
def ClearEnvironment(environment_name): ...
def GetMessage(index): ...
def GetReturnCode(index): ...
def GetMessages(severity=None): ...
def GetAllMessages(): ...
def AddMessage(message): ...
def AddIDMessage(message_type, message_ID, add_argument1=None, add_argument2=None): ...
def GetIDMessage(message_ID, default_message=None): ...
def AddError(message): ...
def AddWarning(message): ...
def AddReturnMessage(index): ...
def SetMessageLevels(levels: str = 'NORMAL') -> None: ...
def SetProduct(product): ...
def CheckProduct(product): ...
def ProductInfo(): ...
def CheckOutExtension(extension_code): ...
def CheckInExtension(extension_code): ...
def CheckExtension(extension_code): ...
def ListSpatialReferences(wild_card=None, spatial_reference_type=None): ...
def ListTransformations(from_sr, to_sr, extent=None, vertical: bool = False, first_only: bool = False): ...
def GetParameterAsText(index): ...
def SetParameterAsText(index, text): ...
def GetParameter(index): ...
def SetParameter(index, value): ...
def CopyParameter(from_param, to_param): ...
def SetParameterSymbology(index, text): ...
def ListFiles(wild_card=None): ...
def ListTools(wild_card=None): ...
def ListEnvironments(wild_card=None): ...
def ListToolboxes(wild_card=None): ...
def AddToolbox(input_file, module_name=None): ...
def RemoveToolbox(toolbox): ...
def GetSystemEnvironment(environment): ...
def Command(command_line): ...
def Usage(tool_name): ...
def Exists(dataset): ...
def ListFeatureClasses(wild_card=None, feature_type=None, feature_dataset=None): ...
def ListDatasets(wild_card=None, feature_type=None): ...
def ListTables(wild_card=None, table_type=None): ...
def ListRasters(wild_card=None, raster_type=None): ...
def ListRasterProducts(metadataFilePath): ...
def ListWorkspaces(wild_card=None, workspace_type=None): ...
def ListVersions(sde_workspace): ...
def ListUsers(sde_workspace): ...
def DisconnectUser(sde_workspace, users=None): ...
def ListFields(dataset, wild_card=None, field_type=None): ...
def ListIndexes(dataset, wild_card=None): ...
def SearchCursor(dataset, where_clause=None, spatial_reference=None, fields=None, sort_fields=None): ...
def UpdateCursor(dataset, where_clause=None, spatial_reference=None, fields=None, sort_fields=None): ...
def InsertCursor(dataset, spatial_reference=None): ...
def Describe(value, data_type=None): ...
def CreateObject(name, options=None): ...
def ValidateFieldName(name, workspace=None): ...
def ValidateTableName(name, workspace=None): ...
def ParseFieldName(name, workspace=None): ...
def ParseTableName(name, workspace=None): ...
def CreateScratchName(prefix=None, suffix=None, data_type=None, workspace=None): ...
def CreateUniqueName(base_name, workspace=None): ...
def TestSchemaLock(dataset): ...
def IsBeingEdited(dataset): ...
def CreateRandomValueGenerator(seed, distribution): ...
def IsSynchronous(tool_name): ...
def GetParameterCount(tool_name): ...
def GetParameterValue(tool_name, index): ...
def GetParameterInfo(tool_name=None): ...
def AddFieldDelimiters(datasource, field): ...
def ListPrinterNames(): ...
def GetSeverity(index): ...
def GetMessageCount(): ...
def GetMaxSeverity(): ...
def GetSeverityLevel(): ...
def SetSeverityLevel(severity) -> None: ...
def GetArgumentCount(): ...
def GetLogHistory(): ...
def SetLogHistory(log_history) -> None: ...
def GetLogMetadata(): ...
def SetLogMetadata(log_metadata) -> None: ...
def FromWKB(byte_array, spatial_reference=None): ...
def FromWKT(wkt_string, spatial_reference=None): ...
def FromGeohash(geohash_string): ...
def LinearUnitConversionFactor(from_unit, to_unit): ...
def ArealUnitConversionFactor(from_unit, to_unit): ...
def AcceptConnections(sde_workspace, accept_connections): ...
def AlterAliasName(table, alias): ...
def LogUsageMetering(code, task_name, num_objects: int = 0, units: float = 0.0): ...
def AttachLocator(loc_path, fc_path, input_field_names, output_field_names, settings={}): ...
def CreateGeocodeSDDraft(loc_path, out_sddraft, service_name, server_type: str = 'ARCGIS_SERVER', connection_file_path=None, copy_data_to_server: bool = False, folder_name=None, summary=None, tags=None, max_result_size: int = 500, max_batch_size: int = 1000, suggested_batch_size: int = 1000, supported_operations=['GEOCODE', 'REVERSE_GEOCODE', 'SUGGEST'], overwrite_existing_service: bool = False): ...
def CreateGPSDDraft(result, out_sddraft, service_name, server_type: str = 'ARCGIS_SERVER', connection_file_path: str = '', copy_data_to_server: bool = True, folder_name=None, summary=None, tags=None, executionType: str = 'Asynchronous', resultMapServer: bool = False, showMessages: str = 'None', maximumRecords: int = 1000, minInstances: int = 1, maxInstances: int = 2, maxUsageTime: int = 600, maxWaitTime: int = 60, maxIdleTime: int = 1800, capabilities=None, constantValues=None, choiceLists=None): ...
def CreateImageSDDraft(raster_or_mosaic_layer, out_sddraft, service_name, server_type: str = 'ARCGIS_SERVER', connection_file_path: str = '', copy_data_to_server: bool = False, folder_name=None, summary=None, tags=None): ...
def ListDataStoreItems(connection_file, datastore_type): ...
def ValidateDataStoreItem(connection_file, datastore_type, connection_name): ...
def RemoveDataStoreItem(connection_file, datastore_type, connection_name): ...
def AddDataStoreItem(connection_file, datastore_type, connection_name, server_path, client_path: str = '', hostname: str = ''): ...
def GetSigninToken(): ...
def GetActivePortalURL(): ...
def ListPortalURLs(): ...
def GetPortalDescription(portal_URL=None): ...
def GetPortalInfo(portal_URL=None): ...
def DecryptPYT(toolbox=None, password=None): ...
def EncryptPYT(toolbox=None, password=None): ...
def RasterToNumPyArray(*args, **kwargs): ...
def NumPyArrayToRaster(*args, **kwargs): ...
def GetImageEXIFProperties(*args, **kwargs): ...
def GetUTMFromLocation(*args, **kwargs): ...
def SetRasterKeyMetadata(*args, **kwargs): ...
def GetRasterKeyMetadata(*args, **kwargs): ...
def CreateAGSServerConnection(*args, **kwargs): ...
def SignInToPortal(*args, **kwargs): ...
def ImportCredentials(*args, **kwargs): ...
def ClearCredentials(*args, **kwargs): ...
def RefreshLayer(*args, **kwargs) -> None: ...
def SetupDebugger(): ...
