from _typeshed import Incomplete
from enum import IntEnum as _IntEnum

class CloudPathType(_IntEnum):
    VSI: Incomplete
    ACS: Incomplete
    HTTP: Incomplete
    CLOUDSTORES: Incomplete

class _LocalScandirIterator:
    def __init__(self, dir_entry: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...

class _CloudScandirIterator:
    def __init__(self, dir_entry: Incomplete | None = None, type: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...

class AIOScandirIterator:
    def __init__(self) -> None: ...
    @classmethod
    def new(cls, dir_entry, is_cloud: bool = False, type: Incomplete | None = None): ...
    def __iter__(self): ...
    def __next__(self): ...

class CloudDirEntryOp:
    def __init__(self) -> None: ...
    @classmethod
    def new(cls, cloud_dir_entry): ...
    def getvsipath(self): ...
    def getpath(self, type=...): ...

class _LocalDirEntry:
    def __init__(self, dir_entry: Incomplete | None = None) -> None: ...
    def close(self) -> None: ...
    @property
    def name(self): ...
    @property
    def path(self): ...
    def is_dir(self): ...
    def is_file(self): ...
    def stat(self): ...

class _CloudDirEntry:
    def __init__(self, dir_entry: Incomplete | None = None, type=...) -> None: ...
    def close(self): ...
    @property
    def name(self): ...
    @property
    def path(self): ...
    def is_dir(self): ...
    def is_file(self): ...
    def stat(self): ...

class AIODirEntry:
    def __init__(self) -> None: ...
    @classmethod
    def new(cls, dir_entry, is_cloud: bool = False, type: Incomplete | None = None): ...
    @property
    def cloud(self): ...
    def close(self): ...
    @property
    def name(self): ...
    @property
    def path(self): ...
    def is_dir(self): ...
    def is_file(self): ...
    def stat(self): ...

class CloudOp:
    def __init__(self) -> None: ...
    @classmethod
    def new(cls, cloud_arcio): ...
    def clearcache(self, path): ...
    def getendpoint(self): ...
    def getfile(self, src, dst, options: Incomplete | None = None): ...
    def getbucketname(self): ...
    def getmetadata(self, path, domain: Incomplete | None = None): ...
    def getobjectstorepath(self): ...
    def getproperties(self, path): ...
    def getprovidername(self): ...
    def getprovideroptions(self): ...
    def getregion(self): ...
    def getsignedurl(self, path, expiry, upload: bool = False): ...
    def putfile(self, src, dst, options: Incomplete | None = None): ...
    def setmetadata(self, path, domain: Incomplete | None = None, metadata: Incomplete | None = None, options: Incomplete | None = None): ...
    def validate(self, certificate: bool = False, stat: bool = False, list: bool = False, read: bool = False, modify: bool = False, path: Incomplete | None = None): ...

class _LocalIO:
    def __init__(self, path: Incomplete | None = None) -> None: ...
    def chdir(self, path) -> None: ...
    def copy(self, src, dst, options: Incomplete | None = None): ...
    def copytree(self, src, dst, options: Incomplete | None = None): ...
    def close(self, handle: Incomplete | None = None): ...
    def exists(self, path): ...
    def getatime(self, path): ...
    def getctime(self, path): ...
    def getcwd(self, type=...): ...
    def getmtime(self, path): ...
    def getpath(self, path, type: Incomplete | None = None): ...
    def getsize(self, path): ...
    def isdir(self, path): ...
    def isfile(self, path): ...
    def listdir(self, path: Incomplete | None = None, type: Incomplete | None = None): ...
    def mkdir(self, path): ...
    def makedirs(self, path): ...
    def open(self, path, mode: Incomplete | None = None, encoding: Incomplete | None = None, mime: Incomplete | None = None): ...
    def remove(self, path): ...
    def removefiles(self, paths: Incomplete | None = None): ...
    def rename(self, src: Incomplete | None = None, dst: Incomplete | None = None): ...
    def rmtree(self, path): ...
    def scandir(self, path, depth: Incomplete | None = None, type: Incomplete | None = None): ...

class _CloudIO:
    def __init__(self, path: Incomplete | None = None) -> None: ...
    def chdir(self, path): ...
    def copy(self, src, dst, options: Incomplete | None = None): ...
    def copytree(self, src, dst, options: Incomplete | None = None): ...
    def close(self, handle: Incomplete | None = None): ...
    def exists(self, path): ...
    def getatime(self, path) -> None: ...
    def getctime(self, path) -> None: ...
    def getcwd(self, type=...): ...
    def getmtime(self, path): ...
    def getpath(self, path, type=...): ...
    def getsize(self, path): ...
    def isdir(self, path): ...
    def isfile(self, path): ...
    def listdir(self, path: Incomplete | None = None, type=...): ...
    def mkdir(self, path) -> None: ...
    def makedirs(self, path) -> None: ...
    def open(self, path, mode: Incomplete | None = None, encoding: Incomplete | None = None, mime: Incomplete | None = None): ...
    def remove(self, path) -> None: ...
    def removefiles(self, paths: Incomplete | None = None): ...
    def rename(self, src: Incomplete | None = None, dst: Incomplete | None = None) -> None: ...
    def rmtree(self, path) -> None: ...
    def scandir(self, path, depth: int = 0, type=...): ...

class AIO:
    def __init__(self, path: Incomplete | None = None) -> None: ...
    @property
    def cloud(self): ...
    def chdir(self, path): ...
    def close(self, handle: Incomplete | None = None): ...
    def copy(self, src, dst, options: Incomplete | None = None): ...
    def copytree(self, src, dst, options: Incomplete | None = None): ...
    def exists(self, path): ...
    def getatime(self, path): ...
    def getctime(self, path): ...
    def getcwd(self, type=...): ...
    def getmtime(self, path): ...
    def getpath(self, path, type=...): ...
    def getsize(self, path): ...
    def isdir(self, path): ...
    def isfile(self, path): ...
    def listdir(self, path: Incomplete | None = None, type=...): ...
    def mkdir(self, path): ...
    def makedirs(self, path): ...
    def open(self, path, mode: Incomplete | None = None, encoding: str = 'utf-8', mime: Incomplete | None = None): ...
    def remove(self, path): ...
    def removefiles(self, paths: Incomplete | None = None): ...
    def rename(self, src: Incomplete | None = None, dst: Incomplete | None = None): ...
    def rmtree(self, path): ...
    def scandir(self, path, depth: int = 0, type=...): ...

class CloudFileOp:
    def __init__(self) -> None: ...
    @classmethod
    def new(cls, cloud_file): ...
    def clearcache(self): ...
    def usebufferedreader(self): ...
    def usecachedfile(self, blocksize: Incomplete | None = None, cachesize: Incomplete | None = None): ...

class _LocalIOFile:
    def __init__(self, file) -> None: ...
    def tell(self): ...
    def seek(self, offset, whence: Incomplete | None = None) -> None: ...
    def close(self): ...
    def flush(self): ...
    def read(self, size: int = -1): ...
    def rewind(self) -> None: ...
    def write(self, b): ...

class _CloudIOFile:
    def __init__(self, file) -> None: ...
    def tell(self): ...
    def seek(self, offset, whence: Incomplete | None = None): ...
    def clearcache(self): ...
    def close(self): ...
    def flush(self): ...
    def read(self, size: int = -1): ...
    def rewind(self): ...
    def usebufferedreader(self): ...
    def usecachedfile(self, blocksize: Incomplete | None = None, cachesize: Incomplete | None = None): ...
    def write(self, b): ...

class AIOFile:
    def __init__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args): ...
    @classmethod
    def new(cls, file, is_cloud: bool = False): ...
    @property
    def cloud(self): ...
    def tell(self): ...
    def seek(self, offset, whence=...): ...
    def close(self): ...
    def flush(self): ...
    def read(self, size: int = -1): ...
    def rewind(self): ...
    def write(self, b): ...

def AIOFileOpen(path, mode: str = 'r', encoding: str = 'utf-8', mime: Incomplete | None = None): ...
