from _typeshed import Incomplete
from arcpy import metadata as metadata
from arcpy._renderer import Graduated_colors_renderer as Graduated_colors_renderer, Graduated_symbols_renderer as Graduated_symbols_renderer, SimpleRenderer as SimpleRenderer, UniqueValueRenderer as UniqueValueRenderer
from arcpy._symbology import ClassBreak as ClassBreak, ColorRamp as ColorRamp, Item as Item, ItemGroup as ItemGroup, RasterClassBreak as RasterClassBreak, RasterItem as RasterItem, Symbol as Symbol, Symbology as Symbology
from arcpy.arcobjects._base import _ObjectWithoutInitCall, passthrough_attr as passthrough_attr
from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject as convertArcObjectToPythonObject
from arcpy.geoprocessing._base import gp_fixargs as gp_fixargs
from arcpy.pdfdocument import PDFDocument as PDFDocument, PDFDocumentCreate as PDFDocumentCreate, PDFDocumentOpen as PDFDocumentOpen
from arcpy.utils import ArgAdaptor as ArgAdaptor

class constants(ArgAdaptor):
    __args__: Incomplete

class AIXFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    convertMarkers: Incomplete
    embedColorProfile: Incomplete
    embedFonts: Incomplete
    filePath: Incomplete
    height: Incomplete
    imageCompression: Incomplete
    imageQuality: Incomplete
    imageCompressionQuality: Incomplete
    removeLayoutBackground: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    width: Incomplete
    def setImageCompression(self, image_compression): ...
    def setImageQuality(self, image_quality): ...
    def __init__(self, aix_path) -> None: ...

class ArcGISProject(_ObjectWithoutInitCall):
    activeMap: Incomplete
    activeView: Incomplete
    databases: Incomplete
    dateSaved: Incomplete
    defaultGeodatabase: Incomplete
    defaultToolbox: Incomplete
    documentVersion: Incomplete
    filePath: Incomplete
    folderConnections: Incomplete
    homeFolder: Incomplete
    isReadOnly: Incomplete
    metadata: Incomplete
    styles: Incomplete
    toolboxes: Incomplete
    def closeViews(self, view_type: str = 'MAPS_AND_LAYOUTS'): ...
    def copyItem(self, project_item, new_name: Incomplete | None = None): ...
    def createGraphicElement(self, container, geometry, style_item: Incomplete | None = None, name: Incomplete | None = None, lock_aspect_ratio: bool = True): ...
    def createGroupElement(self, container, element_list, name: Incomplete | None = None): ...
    def createLayout(self, page_width, page_height, page_units, name: Incomplete | None = None): ...
    def createMap(self, name: Incomplete | None = None, map_type: str = 'Map'): ...
    def createPictureElement(self, container, geometry, path, name: Incomplete | None = None, lock_aspect_ratio: bool = True): ...
    def createPredefinedGraphicElement(self, container, geometry, shape_type, style_item: Incomplete | None = None, name: Incomplete | None = None, lock_aspect_ratio: bool = True): ...
    def createReport(self, page_info, data_source, fields: Incomplete | None = None, statistics: Incomplete | None = None, name: Incomplete | None = None, template: str = 'ATTR_LIST', styling: str = 'BLACK_AND_WHITE'): ...
    def createTextElement(self, container, geometry, text_type, text, text_size: Incomplete | None = None, font_family_name: Incomplete | None = None, font_style_name: Incomplete | None = None, style_item: Incomplete | None = None, name: Incomplete | None = None, lock_aspect_ratio: bool = False): ...
    def deleteItem(self, project_item): ...
    def importDocument(self, document_path, include_layout: bool = True, reuse_existing_maps: bool = False, log_files: bool = True): ...
    def listBasemaps(self, wildcard: Incomplete | None = None): ...
    def listBrokenDataSources(self): ...
    def listColorRamps(self, wildcard: Incomplete | None = None): ...
    def listLayouts(self, wildcard: Incomplete | None = None): ...
    def listMaps(self, wildcard: Incomplete | None = None): ...
    def listReports(self, wildcard: Incomplete | None = None): ...
    def listStyleItems(self, style, style_class: Incomplete | None = None, wildcard: Incomplete | None = None): ...
    def setMergingStrategy(self, merge_conflict_flow_direction: str = 'PUSH'): ...
    def save(self): ...
    def saveACopy(self, file_name): ...
    def updateConnectionProperties(self, current_connection_info, new_connection_info, auto_update_joins_and_relates: bool = True, validate: bool = True, ignore_case: bool = False): ...
    def updateDatabases(self, databases, validate: bool = True): ...
    def updateFolderConnections(self, folder_connections, validate: bool = True): ...
    def updateStyles(self, styles): ...
    def updateToolboxes(self, toolboxes, validate: bool = True): ...
    def __init__(self, aprx_path) -> None: ...

class BMPFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    colorMode: Incomplete
    filePath: Incomplete
    georeferenceMapFrame: Incomplete
    height: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    threshold: Incomplete
    width: Incomplete
    worldFile: Incomplete
    def setColorMode(self, bmp_color_mode): ...
    def __init__(self, bmp_path) -> None: ...

class Bookmark(_ObjectWithoutInitCall):
    description: Incomplete
    hasThumbnail: Incomplete
    map: Incomplete
    name: Incomplete
    def updateThumbnail(self): ...
    def __eq__(self, other): ...

class BookmarkMapSeries(_ObjectWithoutInitCall):
    bookmarks: Incomplete
    currentBookmark: Incomplete
    currentPageNumber: Incomplete
    enabled: Incomplete
    mapFrame: Incomplete
    pageCount: Incomplete
    def export(self, export_format, mapseries_export_options: Incomplete | None = None): ...
    def exportToPDF(self, out_pdf, page_range_type: str = 'ALL', page_range_string: str = '', multiple_files: str = 'PDF_SINGLE_FILE', resolution: int = 96, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', embed_fonts: bool = True, layers_attributes: str = 'LAYERS_ONLY', georef_info: bool = True, jpeg_compression_quality: int = 80, clip_to_elements: bool = False, output_as_image: bool = False, embed_color_profile: bool = True, pdf_accessibility: bool = False, show_export_count: bool = False, keep_layout_background: bool = True, convert_markers: bool = False, simulate_overprint: bool = False): ...
    def getDefinition(self, cim_version): ...
    def getPageNumberFromName(self, page_name): ...
    def refresh(self): ...
    def setDefinition(self, definition_object): ...

class Camera(_ObjectWithoutInitCall):
    heading: Incomplete
    mode: Incomplete
    pitch: Incomplete
    roll: Incomplete
    scale: Incomplete
    X: Incomplete
    Y: Incomplete
    Z: Incomplete
    def getExtent(self): ...
    def setExtent(self, extent): ...
    def __eq__(self, other): ...

class ElevationSurface(_ObjectWithoutInitCall):
    name: Incomplete
    verticalExaggeration: Incomplete
    def listElevationSources(self, wildcard: Incomplete | None = None): ...

class ElevationSource(_ObjectWithoutInitCall):
    dataSource: Incomplete
    name: Incomplete
    visible: Incomplete

class EMFFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    convertMarkers: Incomplete
    filePath: Incomplete
    height: Incomplete
    imageQuality: Incomplete
    outputAsImage: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    width: Incomplete
    def setImageQuality(self, image_quality): ...
    def __init__(self, emf_path) -> None: ...

class EPSFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    convertMarkers: Incomplete
    embedFonts: Incomplete
    filePath: Incomplete
    height: Incomplete
    imageCompression: Incomplete
    imageQuality: Incomplete
    outputAsImage: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    width: Incomplete
    def setImageCompression(self, eps_compression): ...
    def setImageQuality(self, image_quality): ...
    def __init__(self, eps_path) -> None: ...

class GIFFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    colorMode: Incomplete
    filePath: Incomplete
    georeferenceMapFrame: Incomplete
    height: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    threshold: Incomplete
    width: Incomplete
    worldFile: Incomplete
    def setColorMode(self, gif_color_mode): ...
    def __init__(self, gif_path) -> None: ...

class GraphicElement(_ObjectWithoutInitCall):
    anchor: Incomplete
    elementHeight: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementRotation: Incomplete
    elementWidth: Incomplete
    isGroup: Incomplete
    locked: Incomplete
    longName: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    type: Incomplete
    visible: Incomplete
    def applyStyleItem(self, style_item): ...
    def clone(self, suffix: Incomplete | None = None): ...
    def delete(self): ...
    def getDefinition(self, cim_version): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...
    def __eq__(self, other): ...

class GroupElement(_ObjectWithoutInitCall):
    anchor: Incomplete
    elementHeight: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementRotation: Incomplete
    elements: Incomplete
    elementWidth: Incomplete
    isGroup: Incomplete
    locked: Incomplete
    longName: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    type: Incomplete
    visible: Incomplete
    def getDefinition(self, cim_version): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...
    def ungroupElements(self): ...

class JPEGFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    colorMode: Incomplete
    filePath: Incomplete
    georeferenceMapFrame: Incomplete
    height: Incomplete
    imageCompressionQuality: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    width: Incomplete
    worldFile: Incomplete
    def setColorMode(self, jpeg_color_mode): ...
    def __init__(self, jpeg_path) -> None: ...

class LabelClass(_ObjectWithoutInitCall):
    expression: Incomplete
    name: Incomplete
    SQLQuery: Incomplete
    visible: Incomplete
    def getDefinition(self, cim_version): ...
    def setDefinition(self, definition_object): ...

class Layer(_ObjectWithoutInitCall):
    brightness: Incomplete
    contrast: Incomplete
    connectionProperties: Incomplete
    dataSource: Incomplete
    definitionQuery: Incomplete
    groupType: Incomplete
    is3DLayer: Incomplete
    isBroken: Incomplete
    isFeatureLayer: Incomplete
    isSceneLayer: Incomplete
    isBasemapLayer: Incomplete
    isGroupLayer: Incomplete
    isNetworkAnalystLayer: Incomplete
    isNetworkDatasetLayer: Incomplete
    isParcelFabricLayer: Incomplete
    isRasterLayer: Incomplete
    isWebLayer: Incomplete
    isGraphicsLayer: Incomplete
    isTimeEnabled: Incomplete
    longName: Incomplete
    maxThreshold: Incomplete
    metadata: Incomplete
    minThreshold: Incomplete
    name: Incomplete
    pageQuery: Incomplete
    showLabels: Incomplete
    symbology: Incomplete
    time: Incomplete
    transparency: Incomplete
    URI: Incomplete
    visible: Incomplete
    def createLabelClass(self, name, expression, sql_query: Incomplete | None = None, labelclass_language: str = 'ARCADE'): ...
    def disableTime(self): ...
    def enableTime(self, startTimeField: Incomplete | None = None, endTimeField: Incomplete | None = None, autoCalculateTimeRange: bool = True, timeDimension: Incomplete | None = None): ...
    def extrusion(self, extrusion_type: str = 'NONE', expression: Incomplete | None = None): ...
    def getDefinition(self, cim_version): ...
    def getSelectionSet(self): ...
    def listDefinitionQueries(self, wildcard: Incomplete | None = None): ...
    def listLabelClasses(self, wildcard: Incomplete | None = None): ...
    def listLayers(self, wildcard: Incomplete | None = None): ...
    def listTables(self, wildcard: Incomplete | None = None): ...
    def openTableView(self, show_selected: bool = False): ...
    def pasteProperties(self, source_layer, layer_paste_properties: str = 'ALL'): ...
    def saveACopy(self, file_name): ...
    def setDefinition(self, definition_object): ...
    def setGroupType(self, group_type): ...
    def setPageQuery(self, field_name: str = 'NONE', match: bool = True): ...
    def setSelectionSet(self, oidList: Incomplete | None = None, method: str = 'NEW'): ...
    def supports(self, layer_property): ...
    def updateConnectionProperties(self, current_connection_info, new_connection_info, auto_update_joins_and_relates: bool = True, validate: bool = True, ignore_case: bool = False): ...
    def updateDefinitionQueries(self, definitionQueries): ...
    def updateLayerFromJSON(self, json_data): ...
    def __eq__(self, other): ...

class LayerFile(_ObjectWithoutInitCall):
    filePath: Incomplete
    metadata: Incomplete
    version: Incomplete
    def addLayer(self, add_layer_or_layerfile, add_position: str = 'AUTO_ARRANGE'): ...
    def addLayerToGroup(self, target_group_layer, add_layer_or_layerfile, add_position: str = 'AUTO_ARRANGE'): ...
    def insertLayer(self, reference_layer, insert_layer_or_layerfile, insert_position: str = 'BEFORE'): ...
    def listBrokenDataSources(self): ...
    def listLayers(self, wildcard: Incomplete | None = None): ...
    def listTables(self, wildcard: Incomplete | None = None): ...
    def moveLayer(self, reference_layer, move_layer, insert_position: str = 'BEFORE'): ...
    def removeLayer(self, remove_layer): ...
    def save(self): ...
    def saveACopy(self, file_name): ...
    def updateConnectionProperties(self, current_connection_info, new_connection_info, auto_update_joins_and_relates: bool = True, validate: bool = True, ignore_case: bool = False): ...
    def __init__(self, layer_file_path) -> None: ...

class LayerTime(_ObjectWithoutInitCall):
    daylightSavings: Incomplete
    endTime: Incomplete
    endTimeField: Incomplete
    startTime: Incomplete
    startTimeField: Incomplete
    timeDimension: Incomplete
    timeFormat: Incomplete
    timeOffset: Incomplete
    timeOffsetUnits: Incomplete
    timeStepInterval: Incomplete
    timeStepIntervalUnits: Incomplete
    timeZone: Incomplete
    timeZoneIANA: Incomplete

class Layout(_ObjectWithoutInitCall):
    mapSeries: Incomplete
    metadata: Incomplete
    name: Incomplete
    pageHeight: Incomplete
    pageUnits: Incomplete
    pageWidth: Incomplete
    URI: Incomplete
    def changePageSize(self, page_width, page_height, resize_elements: bool = True): ...
    def createBookmarkMapSeries(self, mapframe, bookmarks: Incomplete | None = None): ...
    def createMapFrame(self, geometry, map: Incomplete | None = None, name: Incomplete | None = None): ...
    def createMapSurroundElement(self, geometry, mapsurround_type, mapframe: Incomplete | None = None, style_item: Incomplete | None = None, name: Incomplete | None = None): ...
    def createSpatialMapSeries(self, mapframe, index_layer, name_field, sort_field: Incomplete | None = None): ...
    def createTableFrameElement(self, geometry, mapframe: Incomplete | None = None, table: Incomplete | None = None, fields: Incomplete | None = None, style_item: Incomplete | None = None, name: Incomplete | None = None): ...
    def deleteElement(self, element): ...
    def export(self, export_format): ...
    def exportToAIX(self, out_aix, resolution: int = 300, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', jpeg_compression_quality: int = 80, embed_fonts: bool = True, embed_color_profile: bool = True, clip_to_elements: bool = False, keep_layout_background: bool = False, convert_markers: bool = False): ...
    def exportToBMP(self, out_bmp, resolution: int = 96, bmp_color_mode: str = '24-BIT_TRUE_COLOR', bmp_image_compression: str = 'NONE', embed_color_profile: bool = True, clip_to_elements: bool = False): ...
    def exportToEMF(self, out_emf, resolution: int = 96, image_quality: str = 'BEST', output_as_image: bool = False, clip_to_elements: bool = False, convert_markers: bool = False): ...
    def exportToEPS(self, out_eps, resolution: int = 96, image_compression: str = 'DEFLATE', image_quality: str = 'BEST', embed_fonts: bool = True, output_as_image: bool = False, clip_to_elements: bool = False, convert_markers: bool = False): ...
    def exportToGIF(self, out_gif, resolution: int = 96, gif_color_mode: str = '8-BIT_ADAPTIVE_PALETTE', clip_to_elements: bool = False): ...
    def exportToJPEG(self, out_jpg, resolution: int = 96, jpeg_color_mode: str = '24-BIT_TRUE_COLOR', jpeg_quality: int = 80, embed_color_profile: bool = True, clip_to_elements: bool = False): ...
    def exportToPAGX(self, out_pagx): ...
    def exportToPDF(self, out_pdf, resolution: int = 96, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', embed_fonts: bool = True, layers_attributes: str = 'LAYERS_ONLY', georef_info: bool = True, jpeg_compression_quality: int = 80, clip_to_elements: bool = False, output_as_image: bool = False, embed_color_profile: bool = True, pdf_accessibility: bool = False, keep_layout_background: bool = True, convert_markers: bool = False, simulate_overprint: bool = False): ...
    def exportToPNG(self, out_png, resolution: int = 96, color_mode: str = '32-BIT_WITH_ALPHA', transparent_background: bool = False, embed_color_profile: bool = True, clip_to_elements: bool = False): ...
    def exportToSVG(self, out_svg, resolution: int = 96, compress_to_svgz: bool = False, image_quality: str = 'BEST', embed_fonts: bool = True, output_as_image: bool = False, clip_to_elements: bool = False, convert_markers: bool = False): ...
    def exportToTGA(self, out_tga, resolution: int = 96, color_mode: str = '24-BIT_TRUE_COLOR', transparent_background: bool = False, clip_to_elements: bool = False): ...
    def exportToTIFF(self, out_tif, resolution: int = 96, color_mode: str = '24-BIT_TRUE_COLOR', tiff_compression: str = 'LZW', jpeg_compression_quality: int = 80, transparent_background: bool = False, embed_color_profile: bool = True, clip_to_elements: bool = False, world_file: bool = False, geoTIFF_tags: bool = False, georef_mapframe: Incomplete | None = None): ...
    def getDefinition(self, cim_version): ...
    def listElements(self, element_type: Incomplete | None = None, wildcard: Incomplete | None = None): ...
    def openView(self): ...
    def setDefinition(self, definition_object): ...
    def __eq__(self, other): ...

class LegendElement(_ObjectWithoutInitCall):
    anchor: Incomplete
    columnCount: Incomplete
    elementHeight: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementRotation: Incomplete
    elementWidth: Incomplete
    fittingStrategy: Incomplete
    items: Incomplete
    locked: Incomplete
    longName: Incomplete
    mapFrame: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    showTitle: Incomplete
    syncLayerOrder: Incomplete
    syncLayerVisibility: Incomplete
    syncNewLayer: Incomplete
    syncReferenceScale: Incomplete
    title: Incomplete
    type: Incomplete
    visible: Incomplete
    def addItem(self, layer, add_position: str = 'TOP'): ...
    def applyStyleItem(self, style_item): ...
    def getDefinition(self, cim_version): ...
    def moveItem(self, reference_item, move_item, move_position: str = 'BEFORE'): ...
    def removeItem(self, remove_item): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...

class LegendItem(_ObjectWithoutInitCall):
    arrangement: Incomplete
    column: Incomplete
    name: Incomplete
    patchHeight: Incomplete
    patchWidth: Incomplete
    showFeatureCount: Incomplete
    showVisibleFeatures: Incomplete
    type: Incomplete
    visible: Incomplete
    def applyStyleItem(self, style_item): ...

class Map(_ObjectWithoutInitCall):
    defaultCamera: Incomplete
    defaultView: Incomplete
    excludedLayersFromClipping: Incomplete
    mapType: Incomplete
    mapUnits: Incomplete
    metadata: Incomplete
    name: Incomplete
    referenceScale: Incomplete
    spatialReference: Incomplete
    transformations: Incomplete
    URI: Incomplete
    def addBasemap(self, basemap_name): ...
    def addDataFromPath(self, data_path, web_service_type: str = 'AUTOMATIC', custom_parameters: Incomplete | None = None): ...
    def addLayer(self, add_layer_or_layerfile, add_position: str = 'AUTO_ARRANGE'): ...
    def addLayerToGroup(self, target_group_layer, add_layer_or_layerfile, add_position: str = 'AUTO_ARRANGE'): ...
    def addTable(self, add_table): ...
    def addTableToGroup(self, target_group_layer, add_table): ...
    def clearSelection(self): ...
    def clipLayers(self, clip_object, selection: str = 'ALL'): ...
    def copyBookmark(self, bookmark, name: Incomplete | None = None): ...
    def createGraphicsLayer(self, name: Incomplete | None = None): ...
    def createGroupLayer(self, name, group_layer: Incomplete | None = None): ...
    def exportBookmarks(self, out_bkmx): ...
    def exportToMAPX(self, out_mapx): ...
    def getDefinition(self, cim_version): ...
    def getWebLayerSharingDraft(self, server_type, service_type, service_name, layers_and_tables: Incomplete | None = None): ...
    def importBookmarks(self, bkmx_path): ...
    def insertLayer(self, reference_layer, insert_layer_or_layerfile, insert_position: str = 'BEFORE'): ...
    def listBookmarks(self, wildcard: Incomplete | None = None): ...
    def listBrokenDataSources(self): ...
    def listElevationSurfaces(self, wildcard: Incomplete | None = None): ...
    def listLayers(self, wildcard: Incomplete | None = None): ...
    def listTables(self, wildcard: Incomplete | None = None): ...
    def moveLayer(self, reference_layer, move_layer, insert_position: str = 'BEFORE'): ...
    def openView(self): ...
    def removeBookmark(self, remove_bookmark): ...
    def removeLayer(self, remove_layer): ...
    def removeTable(self, remove_table): ...
    def setDefinition(self, definition_object): ...
    def updateConnectionProperties(self, current_connection_info, new_connection_info, auto_update_joins_and_relates: bool = True, validate: bool = True, ignore_case: bool = False): ...
    def updateTransformations(self, transformations): ...
    def __eq__(self, other): ...

class MapFrame(_ObjectWithoutInitCall):
    anchor: Incomplete
    camera: Incomplete
    elementHeight: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementRotation: Incomplete
    elementWidth: Incomplete
    locked: Incomplete
    longName: Incomplete
    map: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    time: Incomplete
    type: Incomplete
    visible: Incomplete
    def addGrid(self, style_item): ...
    def convertGridToFeatures(self, grid_name, output_geodatabase, new_grid_name: Incomplete | None = None): ...
    def createBookmark(self, name: Incomplete | None = None, description: Incomplete | None = None): ...
    def export(self, export_format): ...
    def exportToAIX(self, out_aix, resolution: int = 300, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', jpeg_compression_quality: int = 80, embed_fonts: bool = True, embed_color_profile: bool = True, convert_markers: bool = False): ...
    def exportToBMP(self, out_bmp, resolution: int = 96, world_file: bool = False, bmp_color_mode: str = '24-BIT_TRUE_COLOR', bmp_image_compression: str = 'NONE', embed_color_profile: bool = True): ...
    def exportToEMF(self, out_emf, resolution: int = 96, image_quality: str = 'BEST', output_as_image: bool = False, convert_markers: bool = False): ...
    def exportToEPS(self, out_eps, resolution: int = 96, image_compression: str = 'DEFLATE', image_quality: str = 'BEST', embed_fonts: bool = True, output_as_image: bool = False, convert_markers: bool = False): ...
    def exportToGIF(self, out_gif, resolution: int = 96, world_file: bool = False, gif_color_mode: str = '8-BIT_ADAPTIVE_PALETTE'): ...
    def exportToJPEG(self, out_jpg, resolution: int = 96, world_file: bool = False, jpeg_color_mode: str = '24-BIT_TRUE_COLOR', jpeg_quality: int = 80, embed_color_profile: bool = True): ...
    def exportToPDF(self, out_pdf, resolution: int = 96, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', embed_fonts: bool = True, layers_attributes: str = 'LAYERS_ONLY', georef_info: bool = True, jpeg_compression_quality: int = 80, output_as_image: bool = False, embed_color_profile: bool = True, convert_markers: bool = False, simulate_overprint: bool = False): ...
    def exportToPNG(self, out_png, resolution: int = 96, world_file: bool = False, color_mode: str = '32-BIT_WITH_ALPHA', embed_color_profile: bool = True): ...
    def exportToSVG(self, out_svg, resolution: int = 96, compress_to_svgz: bool = False, image_quality: str = 'BEST', embed_fonts: bool = True, output_as_image: bool = False, convert_markers: bool = False): ...
    def exportToTGA(self, out_tga, resolution: int = 96, world_file: bool = False, color_mode: str = '24-BIT_TRUE_COLOR'): ...
    def exportToTIFF(self, out_tif, resolution: int = 96, world_file: bool = False, color_mode: str = '24-BIT_TRUE_COLOR', tiff_compression: str = 'LZW', geoTIFF_tags: bool = False, jpeg_compression_quality: int = 80, embed_color_profile: bool = True): ...
    def getDefinition(self, cim_version): ...
    def getLayerExtent(self, layer, selection_only: bool = True, symbolized_extent: bool = True): ...
    def panToExtent(self, extent): ...
    def removeGrids(self, wilcard: Incomplete | None = None): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...
    def zoomToAllLayers(self, selection_only: bool = True, symbolized_extent: bool = True): ...
    def zoomToBookmark(self, bookmark): ...
    def __eq__(self, other): ...

class MapSeries(_ObjectWithoutInitCall):
    clipToIndexFeature: Incomplete
    currentPageNumber: Incomplete
    enabled: Incomplete
    indexLayer: Incomplete
    mapFrame: Incomplete
    pageCount: Incomplete
    pageNameField: Incomplete
    selectedIndexFeatures: Incomplete
    def export(self, export_format, mapseries_export_options: Incomplete | None = None): ...
    def exportToPDF(self, out_pdf, page_range_type: str = 'ALL', page_range_string: str = '', multiple_files: str = 'PDF_SINGLE_FILE', resolution: int = 96, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', embed_fonts: bool = True, layers_attributes: str = 'LAYERS_ONLY', georef_info: bool = True, jpeg_compression_quality: int = 80, clip_to_elements: bool = False, show_selection_symbology: bool = False, output_as_image: bool = False, embed_color_profile: bool = True, pdf_accessibility: bool = False, show_export_count: bool = False, keep_layout_background: bool = True, convert_markers: bool = False, simulate_overprint: bool = False): ...
    def getDefinition(self, cim_version): ...
    def getPageNumberFromName(self, page_name): ...
    @property
    def pageRow(self): ...
    def refresh(self): ...
    def setDefinition(self, definition_object): ...

class MapSurroundElement(_ObjectWithoutInitCall):
    anchor: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementHeight: Incomplete
    elementWidth: Incomplete
    elementRotation: Incomplete
    locked: Incomplete
    longName: Incomplete
    mapFrame: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    type: Incomplete
    visible: Incomplete
    def applyStyleItem(self, style_item): ...
    def getDefinition(self, cim_version): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...

class MapTime(_ObjectWithoutInitCall):
    currentTimeEnd: Incomplete
    currentTimeStart: Incomplete
    currentTimeSpan: Incomplete
    currentTimeSpanUnits: Incomplete
    isTimeEnabled: Incomplete
    timeInclusion: Incomplete
    timeStepInterval: Incomplete
    timeStepIntervalUnits: Incomplete
    def setTimeInclusion(self, time_inclusion): ...
    def timeStep(self, reference_time, interval, interval_units): ...

class MapView(_ObjectWithoutInitCall):
    camera: Incomplete
    map: Incomplete
    def createBookmark(self, name: Incomplete | None = None, description: Incomplete | None = None): ...
    def export(self, export_format): ...
    def exportToAIX(self, out_aix, width, height, resolution: int = 300, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', jpeg_compression_quality: int = 80, embed_fonts: bool = True, embed_color_profile: bool = True, convert_markers: bool = False): ...
    def exportToBMP(self, out_bmp, width, height, resolution: int = 96, world_file: bool = False, bmp_color_mode: str = '24-BIT_TRUE_COLOR', bmp_image_compression: str = 'NONE', embed_color_profile: bool = True): ...
    def exportToEMF(self, out_emf, width, height, resolution: int = 96, image_quality: str = 'BEST', output_as_image: bool = False, convert_markers: bool = False): ...
    def exportToEPS(self, out_eps, width, height, resolution: int = 96, image_compression: str = 'DEFLATE', image_quality: str = 'BEST', embed_fonts: bool = True, output_as_image: bool = False, convert_markers: bool = False): ...
    def exportToGIF(self, out_gif, width, height, resolution: int = 96, world_file: bool = False, gif_color_mode: str = '8-BIT_ADAPTIVE_PALETTE'): ...
    def exportToJPEG(self, out_jpg, width, height, resolution: int = 96, world_file: bool = False, jpeg_color_mode: str = '24-BIT_TRUE_COLOR', jpeg_quality: int = 80, embed_color_profile: bool = True): ...
    def exportToPDF(self, out_pdf, width, height, resolution: int = 96, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', embed_fonts: bool = True, layers_attributes: str = 'LAYERS_ONLY', georef_info: bool = True, jpeg_compression_quality: int = 80, output_as_image: bool = False, embed_color_profile: bool = True, convert_markers: bool = False, simulate_overprint: bool = False): ...
    def exportToPNG(self, out_png, width, height, resolution: int = 96, world_file: bool = False, color_mode: str = '32-BIT_WITH_ALPHA', embed_color_profile: bool = True): ...
    def exportToSVG(self, out_svg, width, height, resolution: int = 96, compress_to_svgz: bool = False, image_quality: str = 'BEST', embed_fonts: bool = True, output_as_image: bool = False, convert_markers: bool = False): ...
    def exportToTGA(self, out_tga, width, height, resolution: int = 96, world_file: bool = False, color_mode: str = '24-BIT_TRUE_COLOR'): ...
    def exportToTIFF(self, out_tif, width, height, resolution: int = 96, world_file: bool = False, color_mode: str = '24-BIT_TRUE_COLOR', tiff_compression: str = 'LZW', geoTIFF_tags: bool = False, jpeg_compression_quality: int = 80, embed_color_profile: bool = True): ...
    def getLayerExtent(self, layer, selection_only: bool = True, symbolized_extent: bool = True): ...
    def panToExtent(self, extent): ...
    def zoomToAllLayers(self, selection_only: bool = True, symbolized_extent: bool = True): ...
    def zoomToBookmark(self, bookmark): ...

class MapSeriesExportOptions(_ObjectWithoutInitCall):
    customPages: Incomplete
    exportFileOptions: Incomplete
    exportPages: Incomplete
    showExportCount: Incomplete
    def setExportFileOptions(self, export_file_options): ...
    def setExportPages(self, export_pages): ...
    def __init__(self) -> None: ...

class PDFFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    compressVectorGraphics: Incomplete
    convertMarkers: Incomplete
    embedColorProfile: Incomplete
    embedFonts: Incomplete
    filePath: Incomplete
    georefInfo: Incomplete
    height: Incomplete
    imageCompression: Incomplete
    imageCompressionQuality: Incomplete
    imageQuality: Incomplete
    includeAccessibilityTags: Incomplete
    includeNonVisibleMapLayers: Incomplete
    layersAndAttributes: Incomplete
    outputAsImage: Incomplete
    removeLayoutBackground: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    simulateOverprint: Incomplete
    width: Incomplete
    def setImageCompression(self, image_compression): ...
    def setImageQuality(self, image_quality): ...
    def setLayersAndAttributes(self, layers_attributes): ...
    def __init__(self, pdf_path) -> None: ...

class PNGFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    colorMode: Incomplete
    filePath: Incomplete
    georeferenceMapFrame: Incomplete
    height: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    threshold: Incomplete
    transparentBackground: Incomplete
    width: Incomplete
    worldFile: Incomplete
    def setColorMode(self, png_color_mode): ...
    def __init__(self, png_path) -> None: ...

class PictureElement(_ObjectWithoutInitCall):
    anchor: Incomplete
    elementHeight: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementRotation: Incomplete
    elementWidth: Incomplete
    locked: Incomplete
    longName: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    sourceImage: Incomplete
    type: Incomplete
    visible: Incomplete
    def getDefinition(self, cim_version): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...

class Report(_ObjectWithoutInitCall):
    definitionQuery: Incomplete
    metadata: Incomplete
    name: Incomplete
    pageInfo: Incomplete
    referenceDataSource: Incomplete
    def export(self, export_format, report_export_options: Incomplete | None = None): ...
    def exportToPDF(self, out_pdf, page_range_type: str = 'ALL', page_range: str = '', starting_page_number: int = 1, total_page_number: Incomplete | None = None, resolution: int = 96, image_quality: str = 'BEST', compress_vector_graphics: bool = True, image_compression: str = 'ADAPTIVE', embed_fonts: bool = True, jpeg_compression_quality: int = 80): ...
    def getDefinition(self, cim_version): ...
    def listSections(self, wildcard: Incomplete | None = None): ...
    def openView(self): ...
    def setDefinition(self, definition_object): ...
    def setReferenceDataSource(self, data_source): ...
    def updatePageInfo(self, page_info): ...

class ReportLayoutSection(_ObjectWithoutInitCall):
    name: Incomplete
    type: Incomplete
    URI: Incomplete
    visible: Incomplete

class ReportExportOptions(_ObjectWithoutInitCall):
    customPages: Incomplete
    exportPages: Incomplete
    startingPageNumberLabelOffset: Incomplete
    totalPageNumberOverride: Incomplete
    def setExportPages(self, report_export_pages): ...
    def __init__(self) -> None: ...

class ReportSection(_ObjectWithoutInitCall):
    definitionQuery: Incomplete
    fields: Incomplete
    name: Incomplete
    referenceDataSource: Incomplete
    statistics: Incomplete
    type: Incomplete
    visible: Incomplete
    def setReferenceDataSource(self, data_source): ...
    def setRelatedReportSource(self, related_report_data_source, related_report_section_name, relate_or_relationship_class_name): ...

class StyleItem(_ObjectWithoutInitCall):
    category: Incomplete
    name: Incomplete
    style: Incomplete
    styleClass: Incomplete
    tags: Incomplete

class SVGFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    compressToSVGZ: Incomplete
    convertMarkers: Incomplete
    embedFonts: Incomplete
    filePath: Incomplete
    height: Incomplete
    imageQuality: Incomplete
    includeNonVisibleMapLayers: Incomplete
    outputAsImage: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    width: Incomplete
    def setImageQuality(self, image_quality): ...
    def __init__(self, svg_path) -> None: ...

class Table(_ObjectWithoutInitCall):
    connectionProperties: Incomplete
    dataSource: Incomplete
    definitionQuery: Incomplete
    isBroken: Incomplete
    isTimeEnabled: Incomplete
    longName: Incomplete
    metadata: Incomplete
    name: Incomplete
    time: Incomplete
    URI: Incomplete
    def disableTime(self): ...
    def enableTime(self, startTimeField: Incomplete | None = None, endTimeField: Incomplete | None = None, autoCalculateTimeRange: bool = True, timeDimension: Incomplete | None = None): ...
    def getDefinition(self, cim_version): ...
    def getSelectionSet(self): ...
    def listDefinitionQueries(self, wildcard: Incomplete | None = None): ...
    def openTableView(self, show_selected: bool = False): ...
    def pasteProperties(self, source_table, table_paste_properties: str = 'ALL'): ...
    def saveACopy(self, file_name): ...
    def setDefinition(self, definition_object): ...
    def setSelectionSet(self, oidList: Incomplete | None = None, method: str = 'NEW'): ...
    def updateConnectionProperties(self, current_connection_info, new_connection_info, auto_update_joins_and_relates: bool = True, validate: bool = True, ignore_case: bool = False): ...
    def updateDefinitionQueries(self, definitionQueries): ...
    def __init__(self, table_data_source) -> None: ...
    def __eq__(self, other): ...

class TableFrameElement(_ObjectWithoutInitCall):
    anchor: Incomplete
    elementHeight: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementWidth: Incomplete
    fields: Incomplete
    table: Incomplete
    locked: Incomplete
    longName: Incomplete
    mapFrame: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    query: Incomplete
    type: Incomplete
    visible: Incomplete
    def applyStyleItem(self, style_item): ...
    def getDefinition(self, cim_version): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...
    def setQuery(self, query_rows): ...
    def sortFields(self, field_info): ...

class TextElement(_ObjectWithoutInitCall):
    anchor: Incomplete
    elementHeight: Incomplete
    elementPositionX: Incomplete
    elementPositionY: Incomplete
    elementRotation: Incomplete
    elementWidth: Incomplete
    fontFamilyName: Incomplete
    fontStyleName: Incomplete
    isOverflowing: Incomplete
    locked: Incomplete
    longName: Incomplete
    name: Incomplete
    parentGroupElement: Incomplete
    text: Incomplete
    textAngle: Incomplete
    textSize: Incomplete
    type: Incomplete
    visible: Incomplete
    def applyStyleItem(self, style_item): ...
    def clone(self, suffix: Incomplete | None = None): ...
    def delete(self): ...
    def getDefinition(self, cim_version): ...
    def setAnchor(self, anchor): ...
    def setDefinition(self, definition_object): ...

class TGAFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    colorMode: Incomplete
    filePath: Incomplete
    height: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    transparentBackground: Incomplete
    width: Incomplete
    def setColorMode(self, tga_color_mode): ...
    def __init__(self, tga_path) -> None: ...

class TIFFFormat(_ObjectWithoutInitCall):
    clipToElements: Incomplete
    colorMode: Incomplete
    embedColorProfile: Incomplete
    filePath: Incomplete
    geoTIFFTags: Incomplete
    georeferenceMapFrame: Incomplete
    height: Incomplete
    imageCompression: Incomplete
    imageCompressionQuality: Incomplete
    resolution: Incomplete
    showSelectionSymbology: Incomplete
    threshold: Incomplete
    transparentBackground: Incomplete
    width: Incomplete
    worldFile: Incomplete
    def setColorMode(self, color_mode): ...
    def setImageCompression(self, tiff_compression): ...
    def __init__(self, tiff_path) -> None: ...

ob_conversion: Incomplete
