from _typeshed import Incomplete

__all__ = ['CreateToolbox', 'CreateTool', 'ImportTool', 'Delete', 'Rename', 'GetProps', 'SetProps', 'AuxFiles', 'AuxFileDelete', 'AuxFileCopy']

def CreateToolbox(path, alias: str = 'tbx1', props={}): ...
def Delete(path) -> None: ...
def Rename(path, new_name) -> None: ...
def GetProps(path, names: str = '*'): ...
def SetProps(path, props) -> None: ...
def CreateTool(path, type: str = 'ScriptTool', toolset: Incomplete | None = None) -> None: ...
def ImportTool(path, tool_path, name: Incomplete | None = None, toolset: Incomplete | None = None) -> None: ...
def AuxFiles(path, auxonly: bool = True): ...
def AuxFileDelete(file_path) -> None: ...
def AuxFileCopy(source_path, destination_path, overwrite: bool = False): ...
