from _typeshed import Incomplete
from arcpy.arcobjects._base import _ObjectWithoutInitCall
from arcpy_wmx import WorkflowExecutionError as WorkflowExecutionError, WorkflowExecutionStepError as WorkflowExecutionStepError

__all__ = ['Connect', 'WorkflowExecutionError', 'WorkflowExecutionStepError']

class ConfigItem:
    def __init__(self, data) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class ActivityType(ConfigItem): ...
class HoldType(ConfigItem): ...
class JobType(ConfigItem): ...

class JobTypeDescription:
    data: Incomplete
    def __init__(self, data={}) -> None: ...
    def __setattr__(self, name, value) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class Priority:
    def __init__(self, data) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class StatusType:
    def __init__(self, data) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class Attachment:
    def __init__(self, data) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class QueryResult:
    fields: Incomplete
    rows: Incomplete
    def __init__(self, xml) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class QueryField:
    name: Incomplete
    alias: Incomplete
    def __init__(self, fieldInfo) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class QueryRow:
    def __init__(self, rowInfo, fields) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, item): ...
    def __contains__(self, item) -> bool: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...

class Workflow:
    steps: Incomplete
    name: Incomplete
    def __init__(self, workflowDict) -> None: ...

def Connect(jtc_path: Incomplete | None = None): ...

class ExtendedProperty(_ObjectWithoutInitCall):
    name: Incomplete
    alias: Incomplete
    cardinality: Incomplete
    jobID: Incomplete
    def __getitem__(self, *args): ...
    def __len__(self, *args) -> int: ...
    def __iter__(self): ...

class ExtendedPropertyValue(_ObjectWithoutInitCall):
    data: Incomplete
    canUpdate: Incomplete
    displayOrder: Incomplete
    displayType: Incomplete
    domain: Incomplete
    filter: Incomplete
    ID: Incomplete
    length: Incomplete
    propAlias: Incomplete
    propName: Incomplete
    required: Incomplete
    tableListClass: Incomplete
    tableListDisplayField: Incomplete
    tableListStoreField: Incomplete
    userVisible: Incomplete

class Job(_ObjectWithoutInitCall):
    name: Incomplete
    ID: Incomplete
    assignedTo: Incomplete
    assignedType: Incomplete
    createdBy: Incomplete
    createdDate: Incomplete
    status: Incomplete
    percentComplete: Incomplete
    jobTypeID: Incomplete
    owner: Incomplete
    parent: Incomplete
    startDate: Incomplete
    dueDate: Incomplete
    startedDate: Incomplete
    endDate: Incomplete
    versionName: Incomplete
    parentVersion: Incomplete
    description: Incomplete
    priority: Incomplete
    versionExists: Incomplete
    currentSteps: Incomplete
    hasAOI: Incomplete
    notes: Incomplete
    hasLOI: Incomplete
    def save(self): ...
    def getPendingDays(self, consider_holds): ...
    def setDataWorkspace(self, data_workspace_id): ...
    def setAOI(self, aoi): ...
    def setLOI(self, loi): ...
    def listExtendedProperties(self): ...
    def getExtendedPropertyTable(self, tableName): ...
    def executeStep(self, step_id: int = 0, callback: Incomplete | None = None): ...
    def markStepAsComplete(self, step_id: int = 0, callback: Incomplete | None = None): ...
    def setStepAsCurrent(self, step_id): ...
    def getWorkflow(self): ...
    def getAttachments(self): ...
    def addAttachment(self, storage_type, source_location): ...
    def deleteAttachment(self, attachment_id): ...
    def retrieveAttachment(self, attachment_id, destination_location): ...
    def getHolds(self): ...
    def releaseHold(self, hold, comment: Incomplete | None = None): ...
    def addHold(self, hold_type_id, comment: Incomplete | None = None): ...
    def addDependency(self, depends_on_job_id, held_on_type: str = 'STEP', held_on_value: int = 0, dependent_on_type: str = 'STATUS', dependent_on_value: str = 'CLOSED'): ...
    def logActivity(self, activity_type, message: Incomplete | None = None): ...
    def sendNotification(self, notification_type): ...
    def retrieveJobMap(self, destination_location): ...
    def storeJobMap(self, source_location): ...
    def deleteJobMap(self): ...

class LinkedProperty(ExtendedProperty):
    def createRecord(self): ...
    def deleteRecord(self, record): ...
    def __getitem__(self, *args): ...
    def __len__(self, *args) -> int: ...
    def __iter__(self): ...

class Hold(_ObjectWithoutInitCall):
    ID: Incomplete
    type: Incomplete
    typeID: Incomplete
    comment: Incomplete
    active: Incomplete
    holdDate: Incomplete
    releasedBy: Incomplete
    releaseDate: Incomplete

class WorkflowStep(_ObjectWithoutInitCall):
    ID: Incomplete
    name: Incomplete
    nextSteps: Incomplete

class WorkflowPath(_ObjectWithoutInitCall):
    fromStep: Incomplete
    toStep: Incomplete
    description: Incomplete

class WorkflowConnection(_ObjectWithoutInitCall):
    def getJob(self, jobID): ...
    def createJob(self, job_type_id: int = -1, job_type_name: Incomplete | None = None, job_type_description: Incomplete | None = None, callback: Incomplete | None = None): ...
    def createSD(self, output_directory, service_name, connection_file_path: Incomplete | None = None, folder_name: Incomplete | None = None, description: Incomplete | None = None, mininstances: int = 1, maxinstances: int = 2, maxusagetime: int = 600, maxwaittime: int = 60, maxidletime: int = 1800): ...
    def queryJobs(self, fields, tables, aliases: Incomplete | None = None, where: Incomplete | None = None, order_by: Incomplete | None = None): ...
    def getQualifiedTableName(self, table_name): ...
    config: Incomplete
    jtcPath: Incomplete

class Configuration(_ObjectWithoutInitCall):
    def getUsers(self): ...
    def getUserGroups(self, username: Incomplete | None = None): ...
    def getJobTypes(self): ...
    def getPrivileges(self, username: Incomplete | None = None): ...
    def getPriorities(self): ...
    def getStatusTypes(self): ...
    def getMaps(self): ...
    def retrieveMap(self, map_name, destination_location): ...
    def storeMap(self, map_name, source_location, storage_type: Incomplete | None = None, overwrite: Incomplete | None = None): ...
    def getJobTypeDescription(self, job_type_id: int = -1, job_type_name: Incomplete | None = None): ...
    def getHoldTypes(self): ...
    def getActivityTypes(self): ...
    def getNotificationTypes(self): ...

class WorkflowExecutionResult(_ObjectWithoutInitCall):
    returnCode: Incomplete
