from _typeshed import Incomplete
from arcpy.arcobjects import Result

__all__ = ['AddDataToBIS', 'AddPointDataToBIS', 'AnalyzeBIS', 'BISToMosaicDataset', 'CreateBIS', 'ReducePointDensity', 'RemoveDataFromBIS', 'SmoothBathymetricTIN']

def BISToMosaicDataset(in_bis_workspace: Incomplete | None = None, out_mosaic: Incomplete | None = None, coordinate_system: Incomplete | None = None, in_query_file: Incomplete | None = None, create_overviews: Incomplete | None = None, force_overview_tiles: Incomplete | None = None) -> Result: ...
def AddDataToBIS(target_workspace: Incomplete | None = None, in_data: Incomplete | None = None, input_types: Incomplete | None = None, include_subfolders: Incomplete | None = None, footprint_type: Incomplete | None = None, vertical_units: Incomplete | None = None, directionality: Incomplete | None = None, in_bag_metadata_mapping_file: Incomplete | None = None, update_overviews: Incomplete | None = None) -> Result: ...
def AddPointDataToBIS(target_workspace: Incomplete | None = None, in_data: Incomplete | None = None, vertical_units: Incomplete | None = None, directionality: Incomplete | None = None, depth_field: Incomplete | None = None, footprint_type: Incomplete | None = None, cell_size: Incomplete | None = None, update_overviews: Incomplete | None = None) -> Result: ...
def AnalyzeBIS(in_bis: Incomplete | None = None, bis_checks: Incomplete | None = None, repair_operations: Incomplete | None = None) -> Result: ...
def CreateBIS(in_workspace: Incomplete | None = None, in_template: Incomplete | None = None, in_proxy_raster_location: Incomplete | None = None, coordinate_system: Incomplete | None = None, config_keyword: Incomplete | None = None) -> Result: ...
def RemoveDataFromBIS(target_biscatalog: Incomplete | None = None, where_clause: Incomplete | None = None, delete_overview_images: Incomplete | None = None, update_overviews: Incomplete | None = None) -> Result: ...
def ReducePointDensity(in_features: Incomplete | None = None, out_feature_class: Incomplete | None = None, depth_field: Incomplete | None = None, depth_direction: Incomplete | None = None, depth_bias: Incomplete | None = None, radius_unit: Incomplete | None = None, start_thinning_radius: Incomplete | None = None, end_thinning_radius: Incomplete | None = None, start_depth: Incomplete | None = None, end_depth: Incomplete | None = None) -> Result: ...
def SmoothBathymetricTIN(in_tin: Incomplete | None = None, out_tin: Incomplete | None = None, depth_direction: Incomplete | None = None, smoothing_iterations: Incomplete | None = None) -> Result: ...
