from arcpy._mp import Layer
from arcpy.typing.gp import Result1, Result2, Result3
from typing import Literal

__all__ = ['AlignFeatures', 'CalculateTransformationErrors', 'Densify', 'EdgematchFeatures', 'ErasePoint', 'ExtendLine', 'FlipLine', 'Generalize', 'GenerateEdgematchLinks', 'GenerateRubbersheetLinks', 'RubbersheetFeatures', 'SimplifyByStraightLinesAndCircularArcs', 'SimplifyByTangentSegments', 'Snap', 'SplitLineByMatch', 'TransferAttributes', 'TransformFeatures', 'TrimLine', 'UpdateCOGO']

def Densify(in_features=None, densification_method: Literal['DISTANCE', 'OFFSET', 'ANGLE'] | None = None, distance=None, max_deviation=None, max_angle=None, max_vertex_per_segment=None) -> Result1[str | Layer]: ...
def ErasePoint(in_features=None, remove_features=None, operation_type: Literal['INSIDE', 'OUTSIDE'] | None = None) -> Result1[str | Layer]: ...
def ExtendLine(in_features=None, length=None, extend_to: Literal['EXTENSION', 'FEATURE'] | None = None) -> Result1[str | Layer]: ...
def FlipLine(in_features=None) -> Result1[str | Layer]: ...
def Generalize(in_features=None, tolerance=None) -> Result1[str | Layer]: ...
def SimplifyByStraightLinesAndCircularArcs(in_features=None, max_offset=None, fitting_type: Literal['FIT_TO_VERTICES', 'FIT_TO_SEGMENTS'] | None = None, circular_arcs: Literal['CREATE', 'NOT_CREATE'] | None = None, max_arc_angle_step=None, min_vertex_count=None, min_radius=None, max_radius=None, min_arc_angle=None, closed_ends: Literal['PRESERVE', 'NOT_PRESERVE'] | None = None, anchor_points=None) -> Result2[str | Layer, str | Layer]: ...
def SimplifyByTangentSegments(in_features=None, max_offset=None) -> Result1[str | Layer]: ...
def Snap(in_features=None, snap_environment=None) -> Result1[str | Layer]: ...
def TrimLine(in_features=None, dangle_length=None, delete_shorts: Literal['DELETE_SHORT', 'KEEP_SHORT'] | None = None) -> Result1[str | Layer]: ...
def UpdateCOGO(in_line_features=None, distances_type: Literal['OVERWRITE', 'UPDATE_NULL_ONLY', 'USE_MINIMUM_DIFFERENCE', 'DO_NOT_UPDATE'] | None = None, distance_tolerance=None, direction_type: Literal['OVERWRITE', 'UPDATE_NULL_ONLY', 'USE_MINIMUM_DIFFERENCE', 'DO_NOT_UPDATE'] | None = None, minimum_direction_difference=None, minimum_direction_lateral_offset=None, combined_scale_factor=None, direction_offset=None) -> Result1[str | Layer]: ...
def AlignFeatures(in_features=None, target_features=None, search_distance=None, match_fields=None) -> Result1[str | Layer]: ...
def CalculateTransformationErrors(in_link_features=None, out_link_table=None, method: Literal['AFFINE', 'PROJECTIVE', 'SIMILARITY'] | None = None) -> Result2[str, str]: ...
def EdgematchFeatures(in_features=None, in_link_features=None, method: Literal['MOVE_ENDPOINT', 'ADD_SEGMENT', 'ADJUST_VERTICES'] | None = None, adjacent_features=None, border_features=None) -> Result1[str | Layer]: ...
def GenerateEdgematchLinks(source_features=None, adjacent_features=None, out_feature_class=None, search_distance=None, match_fields=None) -> Result1[str]: ...
def GenerateRubbersheetLinks(source_features=None, target_features=None, out_feature_class=None, search_distance=None, match_fields=None, out_match_table=None) -> Result3[str, str, str]: ...
def RubbersheetFeatures(in_features=None, in_link_features=None, in_identity_links=None, method: Literal['LINEAR', 'NATURAL_NEIGHBOR'] | None = None) -> Result1[str | Layer]: ...
def SplitLineByMatch(in_features=None, matched_features=None, in_match_table=None, out_feature_class=None, search_distance=None, in_features_as: Literal['AS_SOURCE', 'AS_TARGET'] | None = None, out_point_feature_class=None, split_dangle: Literal['SPLIT_DANGLE', 'NO_SPLIT_DANGLE'] | None = None, min_match_group_length=None, min_split_length=None, split_fields=None) -> Result2[str, str]: ...
def TransferAttributes(source_features=None, target_features=None, transfer_fields=None, search_distance=None, match_fields=None, out_match_table=None, transfer_rule_fields=None) -> Result2[str, str]: ...
def TransformFeatures(in_features=None, in_link_features=None, method: Literal['AFFINE', 'PROJECTIVE', 'SIMILARITY'] | None = None, out_link_table=None) -> Result3[str, str, str | Layer]: ...
