from arcpy._geocoding import *
from _typeshed import Incomplete
from arcpy.arcobjects import Result

__all__ = ['AddPolygonFieldsToLocator', 'AssignStreetsToPoints', 'AssignZonesToStreets', 'ClipLocator', 'ConsolidateLocator', 'CreateCompositeAddressLocator', 'CreateFeatureLocator', 'CreateLocator', 'DeletePolygonFieldsFromLocator', 'GeocodeAddresses', 'GeocodeFile', 'GeocodeLocationsFromTable', 'PackageLocator', 'RebuildAddressLocator', 'RematchAddresses', 'ReverseGeocode', 'SplitAddressIntoComponents', 'Locator']

def AddPolygonFieldsToLocator(in_locator: Incomplete | None = None, polygon_features: Incomplete | None = None, polygon_output_fields: Incomplete | None = None) -> Result: ...
def ClipLocator(in_locator: Incomplete | None = None, out_locator: Incomplete | None = None, area_of_interest: Incomplete | None = None, extent: Incomplete | None = None) -> Result: ...
def ConsolidateLocator(in_locator: Incomplete | None = None, output_folder: Incomplete | None = None, copy_arcsde_locator: Incomplete | None = None) -> Result: ...
def CreateCompositeAddressLocator(in_address_locators: Incomplete | None = None, in_field_map: Incomplete | None = None, in_selection_criteria: Incomplete | None = None, out_composite_address_locator: Incomplete | None = None, in_result_ordering: Incomplete | None = None) -> Result: ...
def CreateFeatureLocator(in_features: Incomplete | None = None, search_fields: Incomplete | None = None, output_locator: Incomplete | None = None, locator_fields: Incomplete | None = None, custom_output_fields: Incomplete | None = None) -> Result: ...
def CreateLocator(country_code: Incomplete | None = None, primary_reference_data: Incomplete | None = None, field_mapping: Incomplete | None = None, out_locator: Incomplete | None = None, language_code: Incomplete | None = None, alternatename_tables: Incomplete | None = None, alternate_field_mapping: Incomplete | None = None, custom_output_fields: Incomplete | None = None, precision_type: Incomplete | None = None) -> Result: ...
def DeletePolygonFieldsFromLocator(in_locator: Incomplete | None = None) -> Result: ...
def GeocodeAddresses(in_table: Incomplete | None = None, address_locator: Incomplete | None = None, in_address_fields: Incomplete | None = None, out_feature_class: Incomplete | None = None, out_relationship_type: Incomplete | None = None, country: Incomplete | None = None, location_type: Incomplete | None = None, category: Incomplete | None = None, output_fields: Incomplete | None = None) -> Result: ...
def PackageLocator(in_locator: Incomplete | None = None, output_file: Incomplete | None = None, copy_arcsde_locator: Incomplete | None = None, additional_files: Incomplete | None = None, summary: Incomplete | None = None, tags: Incomplete | None = None) -> Result: ...
def RebuildAddressLocator(in_address_locator: Incomplete | None = None) -> Result: ...
def RematchAddresses(in_geocoded_feature_class: Incomplete | None = None, in_where_clause: Incomplete | None = None) -> Result: ...
def ReverseGeocode(in_features: Incomplete | None = None, in_address_locator: Incomplete | None = None, out_feature_class: Incomplete | None = None, address_type: Incomplete | None = None, search_distance: Incomplete | None = None, feature_type: Incomplete | None = None, location_type: Incomplete | None = None) -> Result: ...
def AssignStreetsToPoints(in_point_features: Incomplete | None = None, point_field_mapping: Incomplete | None = None, in_street_features: Incomplete | None = None, street_field_mapping: Incomplete | None = None, out_points: Incomplete | None = None, street_fields: Incomplete | None = None, distance: Incomplete | None = None, output_geometry: Incomplete | None = None) -> Result: ...
def AssignZonesToStreets(in_street_features: Incomplete | None = None, zone_features: Incomplete | None = None, zone_fields: Incomplete | None = None, out_streets: Incomplete | None = None, tolerance: Incomplete | None = None) -> Result: ...
def SplitAddressIntoComponents(country_code: Incomplete | None = None, in_address_data: Incomplete | None = None, in_address_fields: Incomplete | None = None, out_address_data: Incomplete | None = None, in_exceptions: Incomplete | None = None) -> Result: ...
def GeocodeFile(in_table: Incomplete | None = None, locator: Incomplete | None = None, address_fields: Incomplete | None = None, output_type: Incomplete | None = None, output_location: Incomplete | None = None, output_name: Incomplete | None = None, country: Incomplete | None = None, location_type: Incomplete | None = None, category: Incomplete | None = None, output_fields: Incomplete | None = None) -> Result: ...
def GeocodeLocationsFromTable(in_table: Incomplete | None = None, in_address_locator: Incomplete | None = None, address_fields: Incomplete | None = None, output_name: Incomplete | None = None, country: Incomplete | None = None, location_type: Incomplete | None = None, category: Incomplete | None = None, output_fields: Incomplete | None = None) -> Result: ...

# Names in __all__ with no definition:
#   Locator
