from _typeshed import Incomplete
from arcpy.arcobjects import Result

__all__ = ['ComputePositioningQuality', 'CreateIPSDataModel', 'CreateIPSQualityDataset', 'EnableIndoorPositioning', 'GenerateIndoorPositioningDataset', 'GenerateIndoorPositioningFile', 'GenerateIndoorPositioningFileWithoutSurvey', 'ShareIndoorPositioningDataService']

def CreateIPSDataModel(target_workspace: Incomplete | None = None, coordinate_system: Incomplete | None = None, setup_indoors_model_for_ips: Incomplete | None = None) -> Result: ...
def GenerateIndoorPositioningDataset(target_ips_positioning_datasets: Incomplete | None = None, dataset_name: Incomplete | None = None, generation_method: Incomplete | None = None, in_levels: Incomplete | None = None, in_ips_recordings: Incomplete | None = None, in_beacons: Incomplete | None = None, in_ips_areas: Incomplete | None = None, in_walls: Incomplete | None = None) -> Result: ...
def ShareIndoorPositioningDataService(in_ips_datasets: Incomplete | None = None, ips_dataset_name: Incomplete | None = None, title: Incomplete | None = None, summary: Incomplete | None = None, tags: Incomplete | None = None, folder: Incomplete | None = None, sharing_level: Incomplete | None = None, group_sharing: Incomplete | None = None) -> Result: ...
def EnableIndoorPositioning(in_workspace: Incomplete | None = None) -> Result: ...
def GenerateIndoorPositioningFile(in_ips_recordings: Incomplete | None = None, target_ips_positioning: Incomplete | None = None, in_ips_transitions: Incomplete | None = None, in_ips_comment: Incomplete | None = None) -> Result: ...
def GenerateIndoorPositioningFileWithoutSurvey(target_positioning_table: Incomplete | None = None, in_beacon_features: Incomplete | None = None, in_ips_area_features: Incomplete | None = None, in_wall_features: Incomplete | None = None, in_facility_features: Incomplete | None = None, in_level_features: Incomplete | None = None, in_ips_transition_features: Incomplete | None = None, in_comment: Incomplete | None = None) -> Result: ...
def ComputePositioningQuality(target_ips_quality_dataset: Incomplete | None = None, in_ips_recordings_features: Incomplete | None = None, in_sight_blocking_details_features: Incomplete | None = None) -> Result: ...
def CreateIPSQualityDataset(target_workspace: Incomplete | None = None, coordinate_system: Incomplete | None = None, out_dataset_name: Incomplete | None = None) -> Result: ...
