from arcpy._mp import Layer, Table
from arcpy.typing.gp import Result, Result1, Result2, Result3
from typing import Literal

__all__ = ['AddGeometryToIndoorPositioningDataset', 'ComputePositioningQuality', 'CreateIPSDataModel', 'CreateIPSQualityDataset', 'EnableIndoorPositioning', 'GenerateIndoorPositioningDataset', 'GenerateIndoorPositioningFile', 'GenerateIndoorPositioningFileWithoutSurvey', 'ShareIndoorPositioningDataService']

def AddGeometryToIndoorPositioningDataset(target_ips_positioning_datasets=None, target_ips_positioning_dataset_name=None, in_level_features=None, in_ips_area_features=None, in_obstacle_features=None, in_entrance_exit_features=None) -> Result2[str | Layer, str | Layer]: ...
def CreateIPSDataModel(target_workspace=None, coordinate_system=None, setup_indoors_model_for_ips: Literal['SETUP_INDOORS_MODEL', 'NO_SETUP_INDOORS_MODEL'] | None = None) -> Result1[str]: ...
def GenerateIndoorPositioningDataset(target_ips_positioning_datasets=None, dataset_name=None, generation_method: Literal['SURVEY_BASED', 'SURVEY_LESS'] | None = None, in_levels=None, in_ips_recordings=None, in_beacons=None, in_ips_areas=None, in_walls=None, update_existing: Literal['UPDATE_EXISTING', 'NO_UPDATE_EXISTING'] | None = None, existing_dataset=None) -> Result1[str | Table]: ...
def ShareIndoorPositioningDataService(in_ips_datasets=None, ips_dataset_name=None, title=None, summary=None, tags=None, folder: Literal['cursor_perf32', 'for_pynit_TestFeatureServiceSanity', 'Survey-Connect with the arcpy team!', 'Survey-Upgrade python environment user survey'] | None = None, sharing_level: Literal['OWNER', 'ORGANIZATION', 'EVERYONE'] | None = None, group_sharing: list[Literal['BBPT', 'Analysis Team', 'Charts Team']] | Literal['BBPT', 'Analysis Team', 'Charts Team'] | str | None = None, update_existing: Literal['UPDATE_EXISTING', 'NO_UPDATE_EXISTING'] | None = None) -> Result2[str, str]: ...
def EnableIndoorPositioning(in_workspace=None) -> Result: ...
def GenerateIndoorPositioningFile(in_ips_recordings=None, target_ips_positioning=None, in_ips_transitions=None, in_ips_comment=None) -> Result1[str]: ...
def GenerateIndoorPositioningFileWithoutSurvey(target_positioning_table=None, in_beacon_features=None, in_ips_area_features=None, in_wall_features=None, in_facility_features=None, in_level_features=None, in_ips_transition_features=None, in_comment=None) -> Result1[str]: ...
def ComputePositioningQuality(target_ips_quality_dataset=None, in_ips_recordings_features=None, in_sight_blocking_details_features=None) -> Result3[str, str, str]: ...
def CreateIPSQualityDataset(target_workspace=None, coordinate_system=None, out_dataset_name=None) -> Result3[str, str, str]: ...
