from arcpy._mp import Layer
from arcpy.typing.gp import Result1
from typing import Literal

__all__ = ['ApplyMaritimeSymbology', 'ConvertS57ToS101', 'CopyS57Features', 'CreateS57ExchangeSet', 'ExpandCollapsedContours', 'ExportGeodatabaseToS57', 'ExportGeodatabaseToVPF', 'ExportS101Cell', 'GenerateCartographicLimits', 'GenerateDepthAreas', 'GenerateLandAreas', 'GenerateLightSector', 'ImportS100Cell', 'ImportS100FeatureCatalogue', 'ImportS57ToGeodatabase', 'ImportVPFToGeodatabase', 'ParseS58LogFile', 'ReducePointDensity', 'RepairNauticalData', 'SmoothBathymetricTIN', 'TransferQualityOfPosition', 'ValidateS57File']

def ApplyMaritimeSymbology(target_features=None, cxml_file=None) -> Result1[str | Layer]: ...
def GenerateCartographicLimits(input_polygons=None, erase_features=None, target_feature_class=None) -> Result1[str | Layer]: ...
def GenerateLightSector(in_features=None, sector_line_length=None, sector_arc_radius=None, sector_unit: Literal['CENTIMETERS', 'DECIMAL_DEGREES', 'DECIMETERS', 'FEET', 'INCHES', 'KILOMETERS', 'METERS', 'MILLIMETERS', 'NAUTICAL_MILES', 'POINTS', 'YARDS'] | None = None, reference_scale=None, coordinate_system=None) -> Result1[str]: ...
def TransferQualityOfPosition(in_geodatabase=None, unverified_features_only: Literal['UNVERIFIED_FEATURES', 'ALL_FEATURES'] | None = None) -> Result1[str]: ...
def ExpandCollapsedContours(target_contours=None, expansion_distance=None) -> Result1[str | Layer]: ...
def GenerateDepthAreas(in_tin=None, in_contours=None, contour_depth_field=None, depth_direction: Literal['POSITIVE_UP', 'POSITIVE_DOWN'] | None = None, target_workspace=None, min_depth=None, max_depth=None, in_extent_polygon=None) -> Result1[str | Layer]: ...
def GenerateLandAreas(in_workspace=None, target_workspace=None, in_extent_polygon=None, in_configuration_file=None) -> Result1[str | Layer]: ...
def ReducePointDensity(in_features=None, out_feature_class=None, depth_field=None, depth_direction: Literal['POSITIVE_UP', 'POSITIVE_DOWN'] | None = None, depth_bias: Literal['SHALLOW_BIASED', 'DEEP_BIASED'] | None = None, radius_unit: Literal['KILOMETERS', 'METERS', 'DECIMETERS', 'CENTIMETERS', 'MILLIMETERS', 'NAUTICAL_MILES', 'MILES', 'YARDS', 'FEET', 'INCHES', 'DECIMAL_DEGREES', 'POINTS'] | None = None, start_thinning_radius=None, end_thinning_radius=None, start_depth=None, end_depth=None) -> Result1[str]: ...
def SmoothBathymetricTIN(in_tin=None, out_tin=None, depth_direction: Literal['POSITIVE_UP', 'POSITIVE_DOWN'] | None = None, smoothing_iterations=None) -> Result1[str]: ...
def ConvertS57ToS101(in_feature_catalogue=None, in_config_file=None, input_s57=None, out_location=None) -> Result1[str]: ...
def ExportS101Cell(in_feature_catalogue=None, in_s101_workspace=None, product=None, export_type: Literal['NEW_DATASET', 'NEW_EDITION', 'UPDATE', 'REISSUE', 'CANCEL'] | None = None, output_location=None) -> Result1[str]: ...
def ImportS100Cell(in_feature_catalogue=None, in_base_cell=None, target_workspace=None, in_update_cells=None) -> Result1[str]: ...
def ImportS100FeatureCatalogue(in_feature_catalogue=None, target_workspace=None, admin_connection=None, coordinate_system=None, subtype_mapping=None, config_keyword=None) -> Result1[str]: ...
def CopyS57Features(in_features=None, target_workspace=None, compilation_scale=None, copy_dsnm_field: Literal['COPY_DSNM_FIELD', 'NO_DSNM_FIELD'] | None = None) -> Result1[str]: ...
def CreateS57ExchangeSet(in_directories=None, out_directory=None, layout_format: Literal['VERSION_LAYOUT', 'PRODUCT_LAYOUT', 'FLAT_LAYOUT'] | None = None, updates_only: Literal['INCLUDE_ONLY_UPDATES', 'INCLUDE_ALL'] | None = None, lfil_file=None) -> Result1[str]: ...
def ExportGeodatabaseToS57(in_source_gdb=None, product=None, export_type: Literal['NEW_DATASET', 'NEW_EDITION', 'UPDATE', 'REISSUE', 'CANCEL'] | None = None, out_location=None, in_product_config=None, clip_data_option: Literal['CLIP', 'DO_NOT_CLIP'] | None = None, sample_export: Literal['SAMPLE_EXPORT', 'OFFICIAL_EXPORT'] | None = None, in_scamin_file=None, in_feature_catalogue=None) -> Result1[str]: ...
def ImportS57ToGeodatabase(in_base_cell=None, target_workspace=None, in_update_cells=None, in_product_config=None) -> Result1[str]: ...
def ParseS58LogFile(in_s58_log_file=None, in_s57_file=None, in_production_database_workspace=None, in_reviewer_workspace=None, reviewer_session=None, in_update_cells=None) -> Result1[str]: ...
def RepairNauticalData(in_workspace=None, repair_operations: list[Literal['FIX_LNAM', 'REMOVE_ORPHAN_RELATIONSHIPS', 'MOVE_EQUIPMENT_FEATURES', 'NUDGE_BOUNDARY_FEATURES']] | Literal['FIX_LNAM', 'REMOVE_ORPHAN_RELATIONSHIPS', 'MOVE_EQUIPMENT_FEATURES', 'NUDGE_BOUNDARY_FEATURES'] | str | None = None) -> Result1[str]: ...
def ValidateS57File(in_s57_file=None, out_directory=None, in_update_cells=None, regional_rules: Literal['BR', 'EU', 'RU', 'US'] | None = None, in_ignore_list=None, exclude_shapefile: Literal['EXCLUDE_SHAPEFILE', 'DO_NOT_EXCLUDE_SHAPEFILE'] | None = None) -> Result1[str]: ...
def ExportGeodatabaseToVPF(in_source_gdb=None, ntm_date=None, out_location=None) -> Result1[str]: ...
def ImportVPFToGeodatabase(in_vpf_features=None, target_workspace=None) -> Result1[str]: ...
