from _typeshed import Incomplete
from arcpy._mp import ArcGISProject as ArcGISProject, ColorRamp as ColorRamp, LayerFile as LayerFile, Table as Table
from arcpy.pdfdocument import PDFDocumentCreate as PDFDocumentCreate, PDFDocumentOpen as PDFDocumentOpen

def CreateWebLayerSDDraft(map_or_layers, out_sddraft, service_name, server_type: str = 'HOSTING_SERVER', service_type: str = '', folder_name: Incomplete | None = None, overwrite_existing_service: bool = False, copy_data_to_server: bool = False, enable_editing: bool = False, allow_exporting: bool = True, enable_sync: bool = False, summary: Incomplete | None = None, tags: Incomplete | None = None, description: Incomplete | None = None, credits: Incomplete | None = None, use_limitations: Incomplete | None = None): ...
def ConvertWebMapToArcGISProject(webmap_json, template_pagx: Incomplete | None = None, mapframe_name: Incomplete | None = None, notes_gdb: Incomplete | None = None, report_template: Incomplete | None = None): ...
def ConvertLayoutFileToLayout(layout_file): ...
def ListTimeZones(wildcard: Incomplete | None = None, time_zone_type: str = 'MICROSOFT_WINDOWS'): ...
def CreateExportFormat(format, file_path: Incomplete | None = None): ...
def CreateExportOptions(class_type): ...
