from arcpy._mp import ArcGISProject as ArcGISProject, ColorRamp as ColorRamp, LayerFile as LayerFile, Table as Table, constants as _constants
from arcpy.pdfdocument import PDFDocumentCreate as PDFDocumentCreate, PDFDocumentOpen as PDFDocumentOpen

def CreateWebLayerSDDraft(map_or_layers, out_sddraft, service_name, server_type: str = 'HOSTING_SERVER', service_type: str = '', folder_name=None, overwrite_existing_service: bool = False, copy_data_to_server: bool = False, enable_editing: bool = False, allow_exporting: bool = True, enable_sync: bool = False, summary=None, tags=None, description=None, credits=None, use_limitations=None): ...
def ConvertWebMapToArcGISProject(webmap_json, template_pagx=None, mapframe_name=None, notes_gdb=None, report_template=None): ...
@_constants.maskargs
def ConvertLayoutFileToLayout(layout_file): ...
@_constants.maskargs
def ListTimeZones(wildcard=None, time_zone_type: str = 'MICROSOFT_WINDOWS'): ...
@_constants.maskargs
def CreateExportFormat(format, file_path=None): ...
@_constants.maskargs
def CreateExportOptions(class_type): ...
