from arcpy._mp import Layer
from arcpy.typing.gp import Result, Result1, Result2, Result3
from typing import Literal

__all__ = ['AddParcelType', 'AnalyzeParcelsByLeastSquaresAdjustment', 'AppendParcels', 'ApplyParcelLeastSquaresAdjustment', 'BuildParcelFabric', 'CopyParcels', 'CreateParcelFabric', 'CreateParcelRecords', 'CreateParcelSeeds', 'DeleteParcels', 'DisableParcelTopology', 'DuplicateParcels', 'EnableParcelTopology', 'ExportParcelRecordFeatures', 'ExportSequencedParcelFeatures', 'FindAdjacentParcelPoints', 'FindDisconnectedParcelPoints', 'FindGapsAndOverlaps', 'GenerateParcelFabricLinks', 'ImportParcelFabricPoints', 'MergeCollinearParcelBoundaries', 'RemoveParcelType', 'SelectParcelFeatures', 'SetParcelLineLabelPosition', 'UpgradeArcMapParcelFabric', 'ValidateParcelFabric']

def AnalyzeParcelsByLeastSquaresAdjustment(in_parcel_fabric=None, analysis_type: Literal['CONSISTENCY_CHECK', 'WEIGHTED_LEAST_SQUARES'] | None = None, convergence_tolerance=None) -> Result: ...
def AppendParcels(in_parcel_fabric=None, target_parcel_fabric=None) -> Result1[str | Layer]: ...
def ApplyParcelLeastSquaresAdjustment(in_parcel_fabric=None, movement_tolerance=None, update_attributes: Literal['UPDATE_ATTRIBUTES', 'NO_UPDATE_ATTRIBUTES'] | None = None) -> Result1[str]: ...
def BuildParcelFabric(in_parcel_fabric=None, extent=None, record_name=None) -> Result1[str]: ...
def CopyParcels(in_parcel_fabric=None, target_database=None, out_dataset_name=None, out_fabric_name=None) -> Result2[str, str]: ...
def CreateParcelSeeds(in_parcel_fabric=None, record_name=None) -> Result1[str]: ...
def DeleteParcels(in_parcel_polygon_features=None) -> Result1[str]: ...
def DuplicateParcels(in_parcel_polygon_features=None, record_name=None, duplicate_to_parcel_type=None, repeat=None, update_field=None, start=None, increment=None) -> Result3[str, str, str]: ...
def ExportParcelRecordFeatures(in_record_polygon_feature=None, target_feature_dataset=None) -> Result1[str]: ...
def ExportSequencedParcelFeatures(in_parcel_polygon_feature=None, target_feature_dataset=None, start_sequence_corner: Literal['NE', 'SE', 'SW', 'NW'] | None = None, points_sequence_format=None, lines_sequence_format=None, sequence_curves_separately: Literal['SEQUENCE_SEPARATELY', 'SEQUENCE_TOGETHER'] | None = None) -> Result: ...
def FindAdjacentParcelPoints(in_parcel_points=None, out_feature_class=None, tolerance=None) -> Result1[str]: ...
def FindDisconnectedParcelPoints(in_parcel_points=None, out_feature_class=None, ignore_fixed: Literal['IGNORE_FIXED', 'NO_IGNORE_FIXED'] | None = None, ignore_constrained: Literal['IGNORE_CONSTRAINED', 'NO_IGNORE_CONSTRAINED'] | None = None, consider_edge: Literal['CONSIDER_EDGE', 'NO_CONSIDER_EDGE'] | None = None) -> Result1[str]: ...
def FindGapsAndOverlaps(in_parcel_features=None, out_feature_class=None, maximum_width=None, detection_type: Literal['WITHIN_LAYER', 'BETWEEN_LAYERS'] | None = None) -> Result1[str]: ...
def GenerateParcelFabricLinks(target_parcel_fabric=None, out_links_feature_class=None, out_anchor_points_feature_class=None, from_date=None, to_date=None, min_link_length=None, extent=None) -> Result2[str, str]: ...
def ImportParcelFabricPoints(source_points=None, target_parcel_fabric=None, match_point_method: Literal['PROXIMITY', 'NAME_AND_PROXIMITY', 'GLOBALID_AND_PROXIMITY'] | None = None, search_distance=None, update_type: Literal['ALL', 'GEOMETRY_XYZ', 'RETIRE_AND_REPLACE'] | None = None, record_name=None, match_field=None, conflicts_table=None, update_create_option: Literal['UPDATE_AND_CREATE', 'CREATE_ONLY', 'UPDATE_ONLY'] | None = None, target_points=None, where_clause=None) -> Result2[str | Layer, str]: ...
def MergeCollinearParcelBoundaries(in_parcel_boundaries=None, offset_tolerance=None) -> Result1[str | Layer]: ...
def SelectParcelFeatures(in_parcel_polygon_features=None) -> Result2[str | Layer, str | Layer]: ...
def SetParcelLineLabelPosition(in_parcel_features=None) -> Result1[str | Layer]: ...
def ValidateParcelFabric(in_parcel_fabric=None, extent=None) -> Result1[str]: ...
def AddParcelType(in_parcel_fabric=None, name=None, administrative_polygon: Literal['ADMINISTRATIVE_POLYGON', 'TOPOLOGY_POLYGON'] | None = None, strata_parcels: Literal['STRATA_PARCELS', 'NOT_STRATA_PARCELS'] | None = None) -> Result3[str, str, str]: ...
def CreateParcelFabric(target_dataset=None, name=None, config_keyword=None) -> Result1[str]: ...
def CreateParcelRecords(in_parcel_features=None, record_field=None, record_expression=None, record_name_method: Literal['FIELD', 'EXPRESSION'] | None = None) -> Result2[str, str]: ...
def DisableParcelTopology(in_parcel_fabric=None) -> Result1[str]: ...
def EnableParcelTopology(in_parcel_fabric=None) -> Result1[str]: ...
def RemoveParcelType(in_parcel_fabric=None, name=None) -> Result3[str, str, str]: ...
def UpgradeArcMapParcelFabric(in_parcel_fabric=None, target_dataset=None, name=None, delete_identical: Literal['DELETE_IDENTICAL_LINES', 'KEEP_IDENTICAL_LINES'] | None = None) -> Result1[str]: ...
