from _typeshed import Incomplete
from arcpy._mp import Layer
from arcpy.typing.gp import Result, Result1, Result2, Result3
from typing import Literal

__all__ = ['AddParcelType', 'AnalyzeParcelsByLeastSquaresAdjustment', 'AppendParcels', 'ApplyParcelLeastSquaresAdjustment', 'BuildParcelFabric', 'CopyParcels', 'CreateParcelFabric', 'CreateParcelRecords', 'CreateParcelSeeds', 'DeleteParcels', 'DisableParcelTopology', 'DuplicateParcels', 'EnableParcelTopology', 'ExportParcelRecordFeatures', 'ExportSequencedParcelFeatures', 'FindAdjacentParcelPoints', 'FindDisconnectedParcelPoints', 'FindGapsAndOverlaps', 'GenerateParcelFabricLinks', 'ImportParcelFabricPoints', 'MergeCollinearParcelBoundaries', 'RemoveParcelType', 'SelectParcelFeatures', 'SetParcelLineLabelPosition', 'UpgradeArcMapParcelFabric', 'ValidateParcelFabric']

def AnalyzeParcelsByLeastSquaresAdjustment(in_parcel_fabric: Incomplete | None = None, analysis_type: Literal['CONSISTENCY_CHECK', 'WEIGHTED_LEAST_SQUARES'] | None = None, convergence_tolerance: Incomplete | None = None) -> Result: ...
def AppendParcels(in_parcel_fabric: Incomplete | None = None, target_parcel_fabric: Incomplete | None = None) -> Result1[str | Layer]: ...
def ApplyParcelLeastSquaresAdjustment(in_parcel_fabric: Incomplete | None = None, movement_tolerance: Incomplete | None = None, update_attributes: Literal['UPDATE_ATTRIBUTES', 'NO_UPDATE_ATTRIBUTES'] | None = None) -> Result1[str]: ...
def BuildParcelFabric(in_parcel_fabric: Incomplete | None = None, extent: Incomplete | None = None, record_name: Incomplete | None = None) -> Result1[str]: ...
def CopyParcels(in_parcel_fabric: Incomplete | None = None, target_database: Incomplete | None = None, out_dataset_name: Incomplete | None = None, out_fabric_name: Incomplete | None = None) -> Result2[str, str]: ...
def CreateParcelSeeds(in_parcel_fabric: Incomplete | None = None, record_name: Incomplete | None = None) -> Result1[str]: ...
def DeleteParcels(in_parcel_polygon_features: Incomplete | None = None) -> Result1[str]: ...
def DuplicateParcels(in_parcel_polygon_features: Incomplete | None = None, record_name: Incomplete | None = None, duplicate_to_parcel_type: Incomplete | None = None, repeat: Incomplete | None = None, update_field: Incomplete | None = None, start: Incomplete | None = None, increment: Incomplete | None = None) -> Result3[str, str, str]: ...
def ExportParcelRecordFeatures(in_record_polygon_feature: Incomplete | None = None, target_feature_dataset: Incomplete | None = None) -> Result1[str]: ...
def ExportSequencedParcelFeatures(in_parcel_polygon_feature: Incomplete | None = None, target_feature_dataset: Incomplete | None = None, start_sequence_corner: Literal['NE', 'SE', 'SW', 'NW'] | None = None, points_sequence_format: Incomplete | None = None, lines_sequence_format: Incomplete | None = None, sequence_curves_separately: Literal['SEQUENCE_SEPARATELY', 'SEQUENCE_TOGETHER'] | None = None) -> Result: ...
def FindAdjacentParcelPoints(in_parcel_points: Incomplete | None = None, out_feature_class: Incomplete | None = None, tolerance: Incomplete | None = None) -> Result1[str]: ...
def FindDisconnectedParcelPoints(in_parcel_points: Incomplete | None = None, out_feature_class: Incomplete | None = None, ignore_fixed: Literal['IGNORE_FIXED', 'NO_IGNORE_FIXED'] | None = None, ignore_constrained: Literal['IGNORE_CONSTRAINED', 'NO_IGNORE_CONSTRAINED'] | None = None, consider_edge: Literal['CONSIDER_EDGE', 'NO_CONSIDER_EDGE'] | None = None) -> Result1[str]: ...
def FindGapsAndOverlaps(in_parcel_features: Incomplete | None = None, out_feature_class: Incomplete | None = None, maximum_width: Incomplete | None = None, detection_type: Literal['WITHIN_LAYER', 'BETWEEN_LAYERS'] | None = None) -> Result1[str]: ...
def GenerateParcelFabricLinks(target_parcel_fabric: Incomplete | None = None, out_links_feature_class: Incomplete | None = None, out_anchor_points_feature_class: Incomplete | None = None, from_date: Incomplete | None = None, to_date: Incomplete | None = None, min_link_length: Incomplete | None = None, extent: Incomplete | None = None) -> Result2[str, str]: ...
def ImportParcelFabricPoints(source_points: Incomplete | None = None, target_parcel_fabric: Incomplete | None = None, match_point_method: Literal['PROXIMITY', 'NAME_AND_PROXIMITY', 'GLOBALID_AND_PROXIMITY'] | None = None, search_distance: Incomplete | None = None, update_type: Literal['ALL', 'GEOMETRY_XYZ', 'RETIRE_AND_REPLACE'] | None = None, record_name: Incomplete | None = None, match_field: Incomplete | None = None, conflicts_table: Incomplete | None = None, update_create_option: Literal['UPDATE_AND_CREATE', 'CREATE_ONLY', 'UPDATE_ONLY'] | None = None, target_points: Incomplete | None = None, where_clause: Incomplete | None = None) -> Result2[str | Layer, str]: ...
def MergeCollinearParcelBoundaries(in_parcel_boundaries: Incomplete | None = None, offset_tolerance: Incomplete | None = None) -> Result1[str | Layer]: ...
def SelectParcelFeatures(in_parcel_polygon_features: Incomplete | None = None) -> Result2[str | Layer, str | Layer]: ...
def SetParcelLineLabelPosition(in_parcel_features: Incomplete | None = None) -> Result1[str | Layer]: ...
def ValidateParcelFabric(in_parcel_fabric: Incomplete | None = None, extent: Incomplete | None = None) -> Result1[str]: ...
def AddParcelType(in_parcel_fabric: Incomplete | None = None, name: Incomplete | None = None, administrative_polygon: Literal['ADMINISTRATIVE_POLYGON', 'TOPOLOGY_POLYGON'] | None = None) -> Result3[str, str, str]: ...
def CreateParcelFabric(target_dataset: Incomplete | None = None, name: Incomplete | None = None, config_keyword: Incomplete | None = None) -> Result1[str]: ...
def CreateParcelRecords(in_parcel_features: Incomplete | None = None, record_field: Incomplete | None = None, record_expression: Incomplete | None = None, record_name_method: Literal['FIELD', 'EXPRESSION'] | None = None) -> Result2[str, str]: ...
def DisableParcelTopology(in_parcel_fabric: Incomplete | None = None) -> Result1[str]: ...
def EnableParcelTopology(in_parcel_fabric: Incomplete | None = None) -> Result1[str]: ...
def RemoveParcelType(in_parcel_fabric: Incomplete | None = None, name: Incomplete | None = None) -> Result3[str, str, str]: ...
def UpgradeArcMapParcelFabric(in_parcel_fabric: Incomplete | None = None, target_dataset: Incomplete | None = None, name: Incomplete | None = None, delete_identical: Literal['DELETE_IDENTICAL_LINES', 'KEEP_IDENTICAL_LINES'] | None = None) -> Result1[str]: ...
