from _typeshed import Incomplete
from arcpy.arcobjects import Result

__all__ = ['AddParcelType', 'AnalyzeParcelsByLeastSquaresAdjustment', 'AppendParcels', 'ApplyParcelLeastSquaresAdjustment', 'BuildParcelFabric', 'CopyParcels', 'CreateParcelFabric', 'CreateParcelRecords', 'CreateParcelSeeds', 'DeleteParcels', 'DisableParcelTopology', 'DuplicateParcels', 'EnableParcelTopology', 'ExportParcelRecordFeatures', 'ExportSequencedParcelFeatures', 'GenerateParcelFabricLinks', 'ImportParcelFabricPoints', 'MergeCollinearParcelBoundaries', 'RemoveParcelType', 'SelectParcelFeatures', 'SetParcelLineLabelPosition', 'UpgradeArcMapParcelFabric', 'ValidateParcelFabric']

def AnalyzeParcelsByLeastSquaresAdjustment(in_parcel_fabric: Incomplete | None = None, analysis_type: Incomplete | None = None, convergence_tolerance: Incomplete | None = None) -> Result: ...
def AppendParcels(in_parcel_fabric: Incomplete | None = None, target_parcel_fabric: Incomplete | None = None) -> Result: ...
def ApplyParcelLeastSquaresAdjustment(in_parcel_fabric: Incomplete | None = None, movement_tolerance: Incomplete | None = None, update_attributes: Incomplete | None = None) -> Result: ...
def BuildParcelFabric(in_parcel_fabric: Incomplete | None = None, extent: Incomplete | None = None, record_name: Incomplete | None = None) -> Result: ...
def CopyParcels(in_parcel_fabric: Incomplete | None = None, target_database: Incomplete | None = None, out_dataset_name: Incomplete | None = None, out_fabric_name: Incomplete | None = None) -> Result: ...
def CreateParcelSeeds(in_parcel_fabric: Incomplete | None = None, record_name: Incomplete | None = None) -> Result: ...
def DeleteParcels(in_parcel_polygon_features: Incomplete | None = None) -> Result: ...
def DuplicateParcels(in_parcel_polygon_features: Incomplete | None = None, record_name: Incomplete | None = None, duplicate_to_parcel_type: Incomplete | None = None, repeat: Incomplete | None = None, update_field: Incomplete | None = None, start: Incomplete | None = None, increment: Incomplete | None = None) -> Result: ...
def ExportParcelRecordFeatures(in_record_polygon_feature: Incomplete | None = None, target_feature_dataset: Incomplete | None = None) -> Result: ...
def ExportSequencedParcelFeatures(in_parcel_polygon_feature: Incomplete | None = None, target_feature_dataset: Incomplete | None = None, start_sequence_corner: Incomplete | None = None, points_sequence_format: Incomplete | None = None, lines_sequence_format: Incomplete | None = None, sequence_curves_separately: Incomplete | None = None) -> Result: ...
def GenerateParcelFabricLinks(target_parcel_fabric: Incomplete | None = None, out_links_feature_class: Incomplete | None = None, out_anchor_points_feature_class: Incomplete | None = None, from_date: Incomplete | None = None, to_date: Incomplete | None = None, min_link_length: Incomplete | None = None, extent: Incomplete | None = None) -> Result: ...
def ImportParcelFabricPoints(source_points: Incomplete | None = None, target_parcel_fabric: Incomplete | None = None, match_point_method: Incomplete | None = None, search_distance: Incomplete | None = None, update_type: Incomplete | None = None, record_name: Incomplete | None = None, match_field: Incomplete | None = None, conflicts_table: Incomplete | None = None, update_create_option: Incomplete | None = None, target_points: Incomplete | None = None, where_clause: Incomplete | None = None) -> Result: ...
def MergeCollinearParcelBoundaries(in_parcel_boundaries: Incomplete | None = None, offset_tolerance: Incomplete | None = None) -> Result: ...
def SelectParcelFeatures(in_parcel_polygon_features: Incomplete | None = None) -> Result: ...
def SetParcelLineLabelPosition(in_parcel_features: Incomplete | None = None) -> Result: ...
def ValidateParcelFabric(in_parcel_fabric: Incomplete | None = None, extent: Incomplete | None = None) -> Result: ...
def AddParcelType(in_parcel_fabric: Incomplete | None = None, name: Incomplete | None = None, administrative_polygon: Incomplete | None = None) -> Result: ...
def CreateParcelFabric(target_dataset: Incomplete | None = None, name: Incomplete | None = None, config_keyword: Incomplete | None = None) -> Result: ...
def CreateParcelRecords(in_parcel_features: Incomplete | None = None, record_field: Incomplete | None = None, record_expression: Incomplete | None = None, record_name_method: Incomplete | None = None) -> Result: ...
def DisableParcelTopology(in_parcel_fabric: Incomplete | None = None) -> Result: ...
def EnableParcelTopology(in_parcel_fabric: Incomplete | None = None) -> Result: ...
def RemoveParcelType(in_parcel_fabric: Incomplete | None = None, name: Incomplete | None = None) -> Result: ...
def UpgradeArcMapParcelFabric(in_parcel_fabric: Incomplete | None = None, target_dataset: Incomplete | None = None, name: Incomplete | None = None, delete_identical: Incomplete | None = None) -> Result: ...
