from _typeshed import Incomplete
from arcpy.utils import ArgAdaptor

__all__ = ['PDFDocument', 'PDFDocumentOpen', 'PDFDocumentCreate']

class constants(ArgAdaptor):
    __args__: Incomplete

class PDFDocument:
    def __init__(self, pdf_path, input_pdf_password=None, open_new: bool = False) -> None: ...
    def appendPages(self, pdf_path, input_pdf_password=None) -> None: ...
    def deletePages(self, page_range) -> None: ...
    def insertPages(self, pdf_path, before_page_number: int = 1, input_pdf_password=None) -> None: ...
    def saveAndClose(self) -> None: ...
    def updateDocProperties(self, pdf_title=None, pdf_author=None, pdf_subject=None, pdf_keywords=None, pdf_open_view=None, pdf_layout=None) -> None: ...
    @constants.maskargs
    def updateDocSecurity(self, new_master_password=None, new_user_password=None, encryption: str = 'AES-256', permissions: str = 'ALL') -> None: ...
    @property
    def pageCount(self): ...

def PDFDocumentOpen(pdf_path, user_password=None, master_password=None): ...
def PDFDocumentCreate(pdf_path): ...
