from _typeshed import Incomplete
from arcpy.utils import ArgAdaptor

__all__ = ['PDFDocument', 'PDFDocumentOpen', 'PDFDocumentCreate']

class constants(ArgAdaptor):
    __args__: Incomplete

class PDFDocument:
    def __init__(self, pdf_path, input_pdf_password: Incomplete | None = None, open_new: bool = False) -> None: ...
    def appendPages(self, pdf_path, input_pdf_password: Incomplete | None = None) -> None: ...
    def deletePages(self, page_range) -> None: ...
    def insertPages(self, pdf_path, before_page_number: int = 1, input_pdf_password: Incomplete | None = None) -> None: ...
    def saveAndClose(self) -> None: ...
    def updateDocProperties(self, pdf_title: Incomplete | None = None, pdf_author: Incomplete | None = None, pdf_subject: Incomplete | None = None, pdf_keywords: Incomplete | None = None, pdf_open_view: Incomplete | None = None, pdf_layout: Incomplete | None = None) -> None: ...
    def updateDocSecurity(self, new_master_password: Incomplete | None = None, new_user_password: Incomplete | None = None, encryption: str = 'AES-256', permissions: str = 'ALL') -> None: ...
    @property
    def pageCount(self): ...

def PDFDocumentOpen(pdf_path, user_password: Incomplete | None = None, master_password: Incomplete | None = None): ...
def PDFDocumentCreate(pdf_path): ...
