from arcpy._mp import Layer, Table
from arcpy.typing.gp import Result1, Result2
from typing import Literal

__all__ = ['CreateReviewerSession', 'DeleteReviewerSession', 'EnableDataReviewer', 'ExecuteReviewerBatchJob', 'ReselectSample', 'SelectRandomSample', 'WriteToReviewerTable']

def ReselectSample(in_layer_or_view=None, in_file=None) -> Result1[str | Table | Layer]: ...
def SelectRandomSample(in_layer_or_view=None, sample_method: Literal['FIXED_NUMBER', 'PERCENTAGE', 'AUTO_CALCULATE'] | None = None, number_of_records=None, percentage_of_records=None, confidence_level: Literal['90', '95', '98', '99'] | None = None, margin_of_error: Literal['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'] | None = None, out_file=None) -> Result2[str, str | Table | Layer]: ...
def ExecuteReviewerBatchJob(reviewer_workspace=None, session=None, batch_job_file=None, production_workspace=None, analysis_area=None, changed_features: Literal['CHANGED_FEATURES', 'ALL_FEATURES'] | None = None, production_workspaceversion=None) -> Result1[str | Table]: ...
def WriteToReviewerTable(in_reviewer_workspace=None, in_session=None, in_features=None, in_field=None, in_origin_table_name=None, in_review_status=None, in_subtype=None, in_notes=None, in_severity=None, in_check_title=None) -> Result1[str | Table]: ...
def CreateReviewerSession(reviewer_workspace=None, session_name=None, session_template=None, duplicate_checking: Literal['DATABASE', 'SESSION', 'NONE'] | None = None, store_geometry: Literal['STORE_GEOMETRY', 'DO_NOT_STORE_GEOMETRY'] | None = None, username=None, version=None) -> Result1[str]: ...
def DeleteReviewerSession(reviewer_workspace=None, session=None) -> Result1[str]: ...
def EnableDataReviewer(workspace=None, spatial_reference=None, register_as_versioned: Literal['NONVERSIONED', 'VERSIONED'] | None = None, config_keyword=None) -> Result1[str]: ...
