from _typeshed import Incomplete
from arcpy._mp import Table
from arcpy.typing.gp import Result1
from typing import Literal

__all__ = ['CreateReviewerSession', 'DeleteReviewerSession', 'EnableDataReviewer', 'ExecuteReviewerBatchJob', 'WriteToReviewerTable']

def ExecuteReviewerBatchJob(reviewer_workspace: Incomplete | None = None, session: Incomplete | None = None, batch_job_file: Incomplete | None = None, production_workspace: Incomplete | None = None, analysis_area: Incomplete | None = None, changed_features: Literal['CHANGED_FEATURES', 'ALL_FEATURES'] | None = None, production_workspaceversion: Incomplete | None = None) -> Result1[str | Table]: ...
def WriteToReviewerTable(in_reviewer_workspace: Incomplete | None = None, in_session: Incomplete | None = None, in_features: Incomplete | None = None, in_field: Incomplete | None = None, in_origin_table_name: Incomplete | None = None, in_review_status: Incomplete | None = None, in_subtype: Incomplete | None = None, in_notes: Incomplete | None = None, in_severity: Incomplete | None = None, in_check_title: Incomplete | None = None) -> Result1[str | Table]: ...
def CreateReviewerSession(reviewer_workspace: Incomplete | None = None, session_name: Incomplete | None = None, session_template: Incomplete | None = None, duplicate_checking: Literal['DATABASE', 'SESSION', 'NONE'] | None = None, store_geometry: Literal['STORE_GEOMETRY', 'DO_NOT_STORE_GEOMETRY'] | None = None, username: Incomplete | None = None, version: Incomplete | None = None) -> Result1[str]: ...
def DeleteReviewerSession(reviewer_workspace: Incomplete | None = None, session: Incomplete | None = None) -> Result1[str]: ...
def EnableDataReviewer(workspace: Incomplete | None = None, spatial_reference: Incomplete | None = None, register_as_versioned: Literal['NONVERSIONED', 'VERSIONED'] | None = None, config_keyword: Incomplete | None = None) -> Result1[str]: ...
