from _typeshed import Incomplete
from arcpy.arcobjects import Result

__all__ = ['CreateReviewerSession', 'DeleteReviewerSession', 'EnableDataReviewer', 'ExecuteReviewerBatchJob', 'WriteToReviewerTable']

def ExecuteReviewerBatchJob(reviewer_workspace: Incomplete | None = None, session: Incomplete | None = None, batch_job_file: Incomplete | None = None, production_workspace: Incomplete | None = None, analysis_area: Incomplete | None = None, changed_features: Incomplete | None = None, production_workspaceversion: Incomplete | None = None) -> Result: ...
def WriteToReviewerTable(in_reviewer_workspace: Incomplete | None = None, in_session: Incomplete | None = None, in_features: Incomplete | None = None, in_field: Incomplete | None = None, in_origin_table_name: Incomplete | None = None, in_review_status: Incomplete | None = None, in_subtype: Incomplete | None = None, in_notes: Incomplete | None = None, in_severity: Incomplete | None = None, in_check_title: Incomplete | None = None) -> Result: ...
def CreateReviewerSession(reviewer_workspace: Incomplete | None = None, session_name: Incomplete | None = None, session_template: Incomplete | None = None, duplicate_checking: Incomplete | None = None, store_geometry: Incomplete | None = None, username: Incomplete | None = None, version: Incomplete | None = None) -> Result: ...
def DeleteReviewerSession(reviewer_workspace: Incomplete | None = None, session: Incomplete | None = None) -> Result: ...
def EnableDataReviewer(workspace: Incomplete | None = None, spatial_reference: Incomplete | None = None, register_as_versioned: Incomplete | None = None, config_keyword: Incomplete | None = None) -> Result: ...
