from _typeshed import Incomplete
from arcpy import gp as gp
from collections.abc import Generator

name_hacks: Incomplete
data_type_hacks: Incomplete

def detect_encoding(readline): ...
def clnstr(s): ...

HTML_RE: Incomplete

def text_for_node(somenode): ...
def indent_text(astring, indentation: int = 4): ...
def indent_unicode_text(astring, indentation: int = 4): ...
def safe_name(*names, **kw): ...
def arglist_for_tool(tool, long_mode: bool = False): ...
def docstring_for_tool(tool) -> Generator[Incomplete, None, Incomplete]: ...
def function_name_for_tool(tool, alt_alias=None, use_alt_alias: bool = True): ...
def args_as_str(arglist, tool): ...
def result_str(tool): ...
def code_for_tool(tool, include_add_toolbox: bool = False, alt_alias=None, use_alt_alias: bool = True) -> Generator[Incomplete]: ...
def docstring_for_toolbox(toolbox): ...
def code_for_toolbox(toolbox, include_add_toolbox, relative_to=None, system_toolbox: bool = False, alt_alias=None, use_alt_alias: bool = True, exclude=[]) -> Generator[Incomplete, None, Incomplete]: ...
def generate_toolbox_module(tbxfile, output_file=None, include_gp_addtoolbox: bool = False, relative_paths: bool = False, system_toolbox: bool = False, alt_alias=None, use_alt_alias: bool = True, exclude=[]): ...
def import_toolbox(tbxfile, module_name=None): ...
