import ast
from _typeshed import Incomplete

__all__ = ['inProcess', 'noisy', 'logcall', 'ArgAdaptor', 'listofnamedtuples', 'getstartingpage', 'fetchautocomplete', 'py3_syntax_report']

def inProcess(): ...
def noisy() -> None: ...
def logcall() -> None: ...

class ArgAdaptor:
    __args__: Incomplete
    @classmethod
    def maskargs(cls, fn): ...
    @classmethod
    def maskmethods(cls, otherclass) -> None: ...

class RASTER_SENTINEL:
    __esri_toolinfo__: Incomplete

def fetchautocomplete(code, string_index): ...
def listofnamedtuples(list_of_dicts, tuple_name: str = ''): ...
def getstartingpage(page_range_string): ...
def py3_syntax_report(python_source, filename: str = '<script>'): ...

class MainBlockRemover(ast.NodeVisitor):
    main_block_nodes: Incomplete
    main_block_line_ranges: Incomplete
    scope_stack: Incomplete
    def __init__(self) -> None: ...
    def visit_FunctionDef(self, node) -> None: ...
    def visit_ClassDef(self, node) -> None: ...
    def visit_AsyncFunctionDef(self, node) -> None: ...
    def visit_If(self, node) -> None: ...
