from arcpy._mp import Layer
from arcpy.typing.gp import Result1, Result2
from typing import Literal

__all__ = ['ClearJobReplicationInfo', 'CreateJobDataReplica', 'CreateJobs', 'CreateNewJobs', 'CreateWorkflowDatabase', 'ExportJobData', 'GetJobAOI', 'GetJobDataWorkspace', 'GetJobParentVersion', 'GetJobVersion', 'ImportJobData', 'PostJobVersion', 'PublishWorkflowService', 'SynchronizeJobData', 'UpgradeWorkflowDatabase', 'Connect']

def ClearJobReplicationInfo(Input_Repository_URL=None, Input_DatabasePath=None) -> Result1[str]: ...
def CreateJobDataReplica(Input_Parent_Repository_URL=None, Input_Parent_Repository_Name=None, Input_Multi_Name=None) -> Result2[str, str]: ...
def CreateWorkflowDatabase(Input_Database_Connection=None, AOI_Spatial_Reference=None, Import_Configuration: Literal['Minimum Configuration', 'Quick Configuration', 'Custom Configuration'] | None = None, Input_Custom_Configuration=None, User_Store: Literal['TRADITIONAL', 'PORTAL'] | None = None) -> Result1[str]: ...
def ExportJobData(Input_Folder=None, Input_DatabasePath=None, Input_Repository_Name=None, Input_Export_Since=None, Input_Export_Until=None) -> Result1[str]: ...
def ImportJobData(Input_File=None, Input_Merge: Literal['COMBINE', 'REPLACE'] | None = None, Input_DatabasePath=None, Input_Repository_Name=None) -> Result1[str]: ...
def PublishWorkflowService(service_name=None, aoi_service_name=None, server=None, out_service_draft_location=None, input_database_path=None, server_folder=None, description=None, overwrite: Literal['OVERWRITE', 'NO_OVERWRITE'] | None = None) -> Result2[str, str]: ...
def SynchronizeJobData(Input_Parent_Repository_URL=None, Input_Parent_Repository_Name=None, Input_Multi_Name=None) -> Result2[str, str]: ...
def UpgradeWorkflowDatabase(Input_Database_Connection=None, User_Store: Literal['TRADITIONAL', 'PORTAL'] | None = None) -> Result1[str]: ...
def CreateJobs(Input_DatabasePath=None, Job_Types=None, Number_of_Jobs=None, Users=None, Priority_of_Jobs=None, Feature_Layer_AOI=None, Union_option: Literal['UNION', 'NO_UNION'] | None = None) -> Result1[str]: ...
def CreateNewJobs(Input_DatabasePath=None, Job_Type=None, Number_of_Jobs=None, Assignment_Type=None, Assign_To=None, Priority=None, Feature_Layer_LOI=None, Union: Literal['UNION', 'NO_UNION'] | None = None) -> Result1[str]: ...
def GetJobAOI(Input_JobID=None, aoi_Layer=None, Input_DatabasePath=None) -> Result1[str | Layer]: ...
def GetJobDataWorkspace(Input_JobID=None, Input_DatabasePath=None, Input_SDEFileLocation=None) -> Result1[str]: ...
def GetJobParentVersion(Input_JobID=None, Input_DatabasePath=None) -> Result1[str]: ...
def GetJobVersion(Input_JobID=None, Input_DatabasePath=None) -> Result2[str, str]: ...
def PostJobVersion(Input_JobID=None, Input_DatabasePath=None) -> Result1[str]: ...
def Connect(jtc_path=None) -> None: ...
