from arcpy._wmx import *
from _typeshed import Incomplete
from arcpy.arcobjects import Result

__all__ = ['ClearJobReplicationInfo', 'CreateJobDataReplica', 'CreateJobs', 'CreateNewJobs', 'CreateWorkflowDatabase', 'ExportJobData', 'GetJobAOI', 'GetJobDataWorkspace', 'GetJobParentVersion', 'GetJobVersion', 'ImportJobData', 'PostJobVersion', 'PublishWorkflowService', 'SynchronizeJobData', 'UpgradeWorkflowDatabase', 'Connect', 'WorkflowExecutionError', 'WorkflowExecutionStepError']

def ClearJobReplicationInfo(Input_Repository_URL: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None) -> Result: ...
def CreateJobDataReplica(Input_Parent_Repository_URL: Incomplete | None = None, Input_Parent_Repository_Name: Incomplete | None = None, Input_Multi_Name: Incomplete | None = None) -> Result: ...
def CreateWorkflowDatabase(Input_Database_Connection: Incomplete | None = None, AOI_Spatial_Reference: Incomplete | None = None, Import_Configuration: Incomplete | None = None, Input_Custom_Configuration: Incomplete | None = None, User_Store: Incomplete | None = None) -> Result: ...
def ExportJobData(Input_Folder: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None, Input_Repository_Name: Incomplete | None = None, Input_Export_Since: Incomplete | None = None, Input_Export_Until: Incomplete | None = None) -> Result: ...
def ImportJobData(Input_File: Incomplete | None = None, Input_Merge: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None, Input_Repository_Name: Incomplete | None = None) -> Result: ...
def PublishWorkflowService(service_name: Incomplete | None = None, aoi_service_name: Incomplete | None = None, server: Incomplete | None = None, out_service_draft_location: Incomplete | None = None, input_database_path: Incomplete | None = None, server_folder: Incomplete | None = None, description: Incomplete | None = None, overwrite: Incomplete | None = None) -> Result: ...
def SynchronizeJobData(Input_Parent_Repository_URL: Incomplete | None = None, Input_Parent_Repository_Name: Incomplete | None = None, Input_Multi_Name: Incomplete | None = None) -> Result: ...
def UpgradeWorkflowDatabase(Input_Database_Connection: Incomplete | None = None, User_Store: Incomplete | None = None) -> Result: ...
def CreateJobs(Input_DatabasePath: Incomplete | None = None, Job_Types: Incomplete | None = None, Number_of_Jobs: Incomplete | None = None, Users: Incomplete | None = None, Priority_of_Jobs: Incomplete | None = None, Feature_Layer_AOI: Incomplete | None = None, Union_option: Incomplete | None = None) -> Result: ...
def CreateNewJobs(Input_DatabasePath: Incomplete | None = None, Job_Type: Incomplete | None = None, Number_of_Jobs: Incomplete | None = None, Assignment_Type: Incomplete | None = None, Assign_To: Incomplete | None = None, Priority: Incomplete | None = None, Feature_Layer_LOI: Incomplete | None = None, Union: Incomplete | None = None) -> Result: ...
def GetJobAOI(Input_JobID: Incomplete | None = None, aoi_Layer: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None) -> Result: ...
def GetJobDataWorkspace(Input_JobID: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None, Input_SDEFileLocation: Incomplete | None = None) -> Result: ...
def GetJobParentVersion(Input_JobID: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None) -> Result: ...
def GetJobVersion(Input_JobID: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None) -> Result: ...
def PostJobVersion(Input_JobID: Incomplete | None = None, Input_DatabasePath: Incomplete | None = None) -> Result: ...

# Names in __all__ with no definition:
#   Connect
#   WorkflowExecutionError
#   WorkflowExecutionStepError
