import dataclasses
from arcgisscripting import na as cna

__all__ = ['NetworkDataset']

@dataclasses.dataclass
class _TMCTrafficFeedDirectoryConfig:
    traffic_directory: str | None
    def __eq__(self, other): ...

@dataclasses.dataclass
class _TMCTrafficFeedGPServiceConfig:
    connection_properties: dict
    service_name: str
    task_name: str
    def __eq__(self, other): ...

@dataclasses.dataclass
class _TMCLiveTrafficConfig:
    field_name: str
    table_name: str
    feed_config: _TMCTrafficFeedGPServiceConfig | _TMCTrafficFeedDirectoryConfig | None
    def __post_init__(self) -> None: ...
    def __eq__(self, other): ...

@dataclasses.dataclass
class _OpenLRTrafficServiceConfig:
    service_id: str
    def __eq__(self, other): ...

@dataclasses.dataclass
class _OpenLRTrafficFeedConfig:
    feed_ids: list[str]
    def __eq__(self, other): ...

@dataclasses.dataclass
class _OpenLRLiveTrafficConfig:
    attribute_mapping: dict[str, str]
    feed_config: _OpenLRTrafficServiceConfig | _OpenLRTrafficFeedConfig | None
    def __post_init__(self) -> None: ...
    def __eq__(self, other): ...

@dataclasses.dataclass
class _NetworkDatasetSchema:
    tmc_live_traffic: _TMCLiveTrafficConfig | None
    openlr_live_traffic: _OpenLRLiveTrafficConfig | None
    def __post_init__(self) -> None: ...
    def __eq__(self, other): ...

class NetworkDataset(cna.NetworkDataset):
    def __init__(self, in_network) -> None: ...
    def checkIntersectingFeatures(self, feature_layer, cutoff: int = 5000): ...
    def describe(self): ...
    def edges(self, edge_properties=None, attribute_names=None, time_of_day=None, eids=None, travel_mode=None, area_of_interest=None): ...
    def junctions(self, junction_properties=None, attribute_names=None, time_of_day=None, eids=None, travel_mode=None, area_of_interest=None): ...
    def turns(self, turn_properties=None, attribute_names=None, eids=None, travel_mode=None, area_of_interest=None): ...
    def getDataSourceFromSourceID(self, source_id): ...
    @property
    def travelModes(self): ...
    @property
    def isBuilt(self): ...
    @property
    def buildTimestamp(self): ...
    @property
    def edgeCount(self): ...
    @property
    def junctionCount(self): ...
    @property
    def turnCount(self): ...
