from _typeshed import Incomplete
from arcgisscripting import na as cna

__all__ = ['NetworkDataset']

class NetworkDataset(cna.NetworkDataset):
    def __init__(self, in_network) -> None: ...
    def checkIntersectingFeatures(self, feature_layer, cutoff: int = 5000): ...
    def describe(self): ...
    def edges(self, edge_properties: Incomplete | None = None, attribute_names: Incomplete | None = None, time_of_day: Incomplete | None = None, eids: Incomplete | None = None, travel_mode: Incomplete | None = None, area_of_interest: Incomplete | None = None): ...
    def junctions(self, junction_properties: Incomplete | None = None, attribute_names: Incomplete | None = None, time_of_day: Incomplete | None = None, eids: Incomplete | None = None, travel_mode: Incomplete | None = None, area_of_interest: Incomplete | None = None): ...
    def turns(self, turn_properties: Incomplete | None = None, attribute_names: Incomplete | None = None, eids: Incomplete | None = None, travel_mode: Incomplete | None = None, area_of_interest: Incomplete | None = None): ...
    def getDataSourceFromSourceID(self, source_id): ...
    @property
    def travelModes(self): ...
    @property
    def isBuilt(self): ...
    @property
    def buildTimestamp(self): ...
    @property
    def edgeCount(self): ...
    @property
    def junctionCount(self): ...
    @property
    def turnCount(self): ...
