from _typeshed import Incomplete
from enum import Enum

__all__ = ['Geoprocessor', 'gp', 'env']

class ServerLogLevel(Enum):
    SEVERE = 'SEVERE'
    WARNING = 'WARNING'
    INFO = 'INFO'
    FINE = 'FINE'
    VERBOSE = 'VERBOSE'
    DEBUG = 'DEBUG'

class Geoprocessor:
    def __init__(self) -> None: ...
    ServerLogLevel = ServerLogLevel
    addToResults: Incomplete
    autoCancelling: Incomplete
    isCancelled: Incomplete
    messageCount: Incomplete
    maxSeverity: Incomplete
    parameterCount: Incomplete
    toolbox: Incomplete
    overwriteOutput: Incomplete
    useCompatibleFieldTypes: Incomplete
    logHistory: Incomplete
    logLineage: Incomplete
    overwriteOutputOptions: Incomplete
    scriptVersion: Incomplete
    severityLevel: Incomplete
    def getInstallInfo(self, *args): ...
    def listInstallations(self, *args): ...
    def setProgressor(self, *args): ...
    def resetProgressor(self, *args): ...
    def setProgressorLabel(self, *args): ...
    def setProgressorPosition(self, *args): ...
    def resetEnvironments(self, *args): ...
    def clearEnvironment(self, *args): ...
    def getMessage(self, *args): ...
    def getSeverity(self, *args): ...
    def getReturnCode(self, *args): ...
    def getMessages(self, *args): ...
    def getAllMessages(self, *args): ...
    def addMessage(self, *args): ...
    def addIDMessage(self, *args): ...
    def getIDMessage(self, *args): ...
    def addError(self, *args): ...
    def addWarning(self, *args): ...
    def addReturnMessage(self, *args): ...
    def setProduct(self, *args): ...
    def checkProduct(self, *args): ...
    def productInfo(self, *args): ...
    def checkOutExtension(self, *args): ...
    def checkInExtension(self, *args): ...
    def checkExtension(self, *args): ...
    def listSpatialReferences(self, *args): ...
    def listTransformations(self, *args): ...
    def getParameterAsText(self, *args): ...
    def setParameterAsText(self, *args): ...
    def getParameter(self, *args): ...
    def setParameter(self, *args): ...
    def copyParameter(self, *args): ...
    def setParameterSymbology(self, *args): ...
    def listFiles(self, *args): ...
    def listTools(self, *args): ...
    def listEnvironments(self, *args): ...
    def listToolboxes(self, *args): ...
    def addToolbox(self, *args): ...
    def removeToolbox(self, *args): ...
    def getSystemEnvironment(self, *args): ...
    def command(self, *args): ...
    def usage(self, *args): ...
    def exists(self, *args): ...
    def listFeatureClasses(self, *args): ...
    def listDatasets(self, *args): ...
    def listTables(self, *args): ...
    def listRasters(self, *args): ...
    def listRasterProducts(self, *args): ...
    def listWorkspaces(self, *args): ...
    def listVersions(self, *args): ...
    def listFields(self, *args): ...
    def listIndexes(self, *args): ...
    def listPrinterNames(self, *args): ...
    def searchCursor(self, *args): ...
    def updateCursor(self, *args): ...
    def insertCursor(self, *args): ...
    def describe(self, *args): ...
    def createObject(self, *args): ...
    def validateFieldName(self, *args): ...
    def validateTableName(self, *args): ...
    def parseFieldName(self, *args): ...
    def parseTableName(self, *args): ...
    def createScratchName(self, *args): ...
    def createUniqueName(self, *args): ...
    def testSchemaLock(self, *args): ...
    def createRandomValueGenerator(self, *args): ...
    def isSynchronous(self, *args): ...
    def getParameterCount(self, *args): ...
    def getParameterValue(self, *args): ...
    def getParameterInfo(self, *args): ...
    def addFieldDelimiters(self, *args): ...
    def getSystemToolboxesPath(self): ...
    def getSystemToolboxesPaths(self): ...
    def getMyToolboxesPath(self): ...
    def wildcardMatch(self, wildcard, data): ...
    def alterAliasName(self, table, alias): ...
    def acceptConnections(self, sde_workspace, accept_connections): ...
    def logUsageMetering(self, code, task_name, num_objects: int = 0, units: float = 0.0): ...
    def createGPSDDraft(self, result, out_sddraft, service_name, server_type: str = 'ARCGIS_SERVER', connection_file_path: str = '', copy_data_to_server: bool = True, folder_name: Incomplete | None = None, summary: Incomplete | None = None, tags: Incomplete | None = None, executionType: str = 'Asynchronous', resultMapServer: bool = False, showMessages: str = 'None', maximumRecords: int = 1000, minInstances: int = 1, maxInstances: int = 2, maxUsageTime: int = 600, maxWaitTime: int = 60, maxIdleTime: int = 1800, capabilities: Incomplete | None = None, constantValues: Incomplete | None = None, choiceLists: Incomplete | None = None): ...
    def fromEsriJson(self, json): ...
    def listDataStoreItems(self, connection_file, datastore_type): ...
    def validateDataStoreItem(self, connection_file, datastore_type, connection_name): ...
    def removeDataStoreItem(self, connection_file, datastore_type, connection_name): ...
    def addDataStoreItem(self, connection_file, datastore_type, connection_name, server_path, client_path: str = '', hostname: str = ''): ...
    def getSigninToken(self): ...
    def getActivePortalURL(self): ...
    def listPortalURLs(self): ...
    def getPortalDescription(self, portal_URL: Incomplete | None = None): ...
    def getPortalInfo(self, portal_URL: Incomplete | None = None): ...
    def encryptPYT(self, toolbox, password): ...
    def decryptPYT(self, toolbox, password): ...
    def logToServer(self, msg: str, level: ServerLogLevel, method_name: str = '', code: int = 0, elapsed: float = -1.0): ...
    def __getattr__(self, attr): ...

gp: Incomplete
env: Incomplete
