__all__ = ['Envelope', 'Rectangle', 'Extent', 'HfBinary', 'HfForward', 'HfLinear', 'HfInverseLinear', 'HfTable', 'VfBinary', 'VfLinear', 'VfInverseLinear', 'VfSymLinear', 'VfSymInverseLinear', 'VfCos', 'VfSec', 'VfCosSec', 'VfSecCos', 'VfTable', 'NbrAnnulus', 'NbrCircle', 'NbrIrregular', 'NbrRectangle', 'NbrWedge', 'NbrWeight', 'RadiusVariable', 'RadiusFixed', 'TimeWithinDay', 'TimeSpecialDays', 'TimeMultipleDays', 'TimeWholeYear', 'KrigingModelOrdinary', 'KrigingModelUniversal', 'FuzzyGaussian', 'FuzzyLarge', 'FuzzyLinear', 'FuzzyMSLarge', 'FuzzyMSSmall', 'FuzzyNear', 'FuzzySmall', 'RemapRange', 'RemapValue', 'TopoPointElevation', 'TopoContour', 'TopoStream', 'TopoSink', 'TopoBoundary', 'TopoLake', 'WOTable', 'WSTable']

def Envelope(x_min, y_min, x_max, y_max): ...
def Rectangle(x_min, y_min, x_max, y_max): ...
def Extent(x_min, y_min, x_max, y_max): ...
def HfBinary(zero_factor=None, cut_angle=None): ...
def HfForward(zero_factor=None, side_value=None): ...
def HfLinear(zero_factor=None, cut_angle=None, slope=None): ...
def HfInverseLinear(zero_factor=None, cut_angle=None, slope=None): ...
def HfTable(in_table): ...
def VfBinary(zero_factor=None, low_cut_angle=None, high_cut_angle=None): ...
def VfLinear(zero_factor=None, low_cut_angle=None, high_cut_angle=None, slope=None): ...
def VfInverseLinear(zero_factor=None, low_cut_angle=None, high_cut_angle=None, slope=None): ...
def VfSymLinear(zero_factor=None, low_cut_angle=None, high_cut_angle=None, slope=None): ...
def VfSymInverseLinear(zero_factor=None, low_cut_angle=None, high_cut_angle=None, slope=None): ...
def VfCos(low_cut_angle=None, high_cut_angle=None, cos_power=None): ...
def VfSec(low_cut_angle=None, high_cut_angle=None, sec_power=None): ...
def VfCosSec(low_cut_angle=None, high_cut_angle=None, cos_power=None, sec_power=None): ...
def VfSecCos(low_cut_angle=None, high_cut_angle=None, sec_power=None, cos_power=None): ...
def VfTable(in_table): ...
def NbrAnnulus(inner_radius=None, outer_radius=None, units=None): ...
def NbrCircle(radius=None, units=None): ...
def NbrIrregular(in_kernel_file): ...
def NbrRectangle(width=None, height=None, units=None): ...
def NbrWedge(start_angle=None, end_angle=None, radius=None, units=None): ...
def NbrWeight(in_kernel_file): ...
def RadiusVariable(number_of_points=None, max_distance=None): ...
def RadiusFixed(distance=None, min_number_of_points=None): ...
def TimeWithinDay(day=None, start_time=None, end_time=None): ...
def TimeSpecialDays(): ...
def TimeMultipleDays(year=None, start_day=None, end_day=None): ...
def TimeWholeYear(year=None): ...
def KrigingModelOrdinary(semivariogram_type, lag_size=None, major_range=None, partial_sill=None, nugget=None): ...
def KrigingModelUniversal(semivariogram_type, lag_size=None, major_range=None, partial_sill=None, nugget=None): ...
def FuzzyGaussian(midpoint=None, spread=None): ...
def FuzzyLarge(midpoint=None, spread=None): ...
def FuzzyLinear(min=None, max=None): ...
def FuzzyMSLarge(mean_multiplier=None, std_multiplier=None): ...
def FuzzyMSSmall(mean_multiplier=None, std_multiplier=None): ...
def FuzzyNear(midpoint=None, spread=None): ...
def FuzzySmall(midpoint=None, spread=None): ...
def RemapRange(table): ...
def RemapValue(table): ...
def WOTable(table, list_): ...
def WSTable(table): ...
def TopoPointElevation(table): ...
def TopoContour(table): ...
def TopoStream(table): ...
def TopoSink(table): ...
def TopoBoundary(table): ...
def TopoLake(table): ...
