import Utils as Utils
from _typeshed import Incomplete

class _DataSetName(str):
    def __new__(cls, *arguments, **keywords): ...

class _CompoundParameter:
    def __init__(self, keyword: Incomplete | None = None) -> None: ...
    def __eq__(self, rhs): ...
