import Utils as Utils

class _DataSetName(str):
    def __new__(cls, *arguments, **keywords): ...

class _CompoundParameter:
    def __init__(self, keyword=None) -> None: ...
    def __eq__(self, rhs): ...
