from _typeshed import Incomplete

__all__ = ['Envelope', 'Rectangle', 'Extent', 'HfBinary', 'HfForward', 'HfLinear', 'HfInverseLinear', 'HfTable', 'VfBinary', 'VfLinear', 'VfInverseLinear', 'VfSymLinear', 'VfSymInverseLinear', 'VfCos', 'VfSec', 'VfCosSec', 'VfSecCos', 'VfTable', 'NbrAnnulus', 'NbrCircle', 'NbrIrregular', 'NbrRectangle', 'NbrWedge', 'NbrWeight', 'RadiusVariable', 'RadiusFixed', 'TimeWithinDay', 'TimeSpecialDays', 'TimeMultipleDays', 'TimeWholeYear', 'KrigingModelOrdinary', 'KrigingModelUniversal', 'FuzzyGaussian', 'FuzzyLarge', 'FuzzyLinear', 'FuzzyMSLarge', 'FuzzyMSSmall', 'FuzzyNear', 'FuzzySmall', 'RemapRange', 'RemapValue', 'TopoPointElevation', 'TopoContour', 'TopoStream', 'TopoSink', 'TopoBoundary', 'TopoLake', 'WOTable', 'WSTable']

def Envelope(x_min, y_min, x_max, y_max): ...
def Rectangle(x_min, y_min, x_max, y_max): ...
def Extent(x_min, y_min, x_max, y_max): ...
def HfBinary(zero_factor: Incomplete | None = None, cut_angle: Incomplete | None = None): ...
def HfForward(zero_factor: Incomplete | None = None, side_value: Incomplete | None = None): ...
def HfLinear(zero_factor: Incomplete | None = None, cut_angle: Incomplete | None = None, slope: Incomplete | None = None): ...
def HfInverseLinear(zero_factor: Incomplete | None = None, cut_angle: Incomplete | None = None, slope: Incomplete | None = None): ...
def HfTable(in_table): ...
def VfBinary(zero_factor: Incomplete | None = None, low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None): ...
def VfLinear(zero_factor: Incomplete | None = None, low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, slope: Incomplete | None = None): ...
def VfInverseLinear(zero_factor: Incomplete | None = None, low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, slope: Incomplete | None = None): ...
def VfSymLinear(zero_factor: Incomplete | None = None, low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, slope: Incomplete | None = None): ...
def VfSymInverseLinear(zero_factor: Incomplete | None = None, low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, slope: Incomplete | None = None): ...
def VfCos(low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, cos_power: Incomplete | None = None): ...
def VfSec(low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, sec_power: Incomplete | None = None): ...
def VfCosSec(low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, cos_power: Incomplete | None = None, sec_power: Incomplete | None = None): ...
def VfSecCos(low_cut_angle: Incomplete | None = None, high_cut_angle: Incomplete | None = None, sec_power: Incomplete | None = None, cos_power: Incomplete | None = None): ...
def VfTable(in_table): ...
def NbrAnnulus(inner_radius: Incomplete | None = None, outer_radius: Incomplete | None = None, units: Incomplete | None = None): ...
def NbrCircle(radius: Incomplete | None = None, units: Incomplete | None = None): ...
def NbrIrregular(in_kernel_file): ...
def NbrRectangle(width: Incomplete | None = None, height: Incomplete | None = None, units: Incomplete | None = None): ...
def NbrWedge(start_angle: Incomplete | None = None, end_angle: Incomplete | None = None, radius: Incomplete | None = None, units: Incomplete | None = None): ...
def NbrWeight(in_kernel_file): ...
def RadiusVariable(number_of_points: Incomplete | None = None, max_distance: Incomplete | None = None): ...
def RadiusFixed(distance: Incomplete | None = None, min_number_of_points: Incomplete | None = None): ...
def TimeWithinDay(day: Incomplete | None = None, start_time: Incomplete | None = None, end_time: Incomplete | None = None): ...
def TimeSpecialDays(): ...
def TimeMultipleDays(year: Incomplete | None = None, start_day: Incomplete | None = None, end_day: Incomplete | None = None): ...
def TimeWholeYear(year: Incomplete | None = None): ...
def KrigingModelOrdinary(semivariogram_type, lag_size: Incomplete | None = None, major_range: Incomplete | None = None, partial_sill: Incomplete | None = None, nugget: Incomplete | None = None): ...
def KrigingModelUniversal(semivariogram_type, lag_size: Incomplete | None = None, major_range: Incomplete | None = None, partial_sill: Incomplete | None = None, nugget: Incomplete | None = None): ...
def FuzzyGaussian(midpoint: Incomplete | None = None, spread: Incomplete | None = None): ...
def FuzzyLarge(midpoint: Incomplete | None = None, spread: Incomplete | None = None): ...
def FuzzyLinear(min: Incomplete | None = None, max: Incomplete | None = None): ...
def FuzzyMSLarge(mean_multiplier: Incomplete | None = None, std_multiplier: Incomplete | None = None): ...
def FuzzyMSSmall(mean_multiplier: Incomplete | None = None, std_multiplier: Incomplete | None = None): ...
def FuzzyNear(midpoint: Incomplete | None = None, spread: Incomplete | None = None): ...
def FuzzySmall(midpoint: Incomplete | None = None, spread: Incomplete | None = None): ...
def RemapRange(table): ...
def RemapValue(table): ...
def WOTable(table, list_): ...
def WSTable(table): ...
def TopoPointElevation(table): ...
def TopoContour(table): ...
def TopoStream(table): ...
def TopoSink(table): ...
def TopoBoundary(table): ...
def TopoLake(table): ...
