import arcgisscripting
from . import Utils as Utils
from _typeshed import Incomplete
from arcpy import env as env, gp as gp

useLocalFunctions: bool

def SetUseLocalFunctions(value) -> None: ...
def tryLocalFunction(*args): ...

class Raster(arcgisscripting.Raster):
    def __init__(self, in_raster, is_multidimensional: bool = False) -> None: ...
    def __new__(cls, in_raster, is_multidimensional: bool = False): ...
    @property
    def bandNames(self): ...
    def getRasterBands(self, band_ids_or_names: Incomplete | None = None): ...
    def getBandProperty(self, band_id_or_name, property_name): ...
    def setBandProperty(self, band_id_or_name, property_name, property_value): ...
    def exportImage(self, width: int = 0, height: int = 0, format: str = 'PNG32', extent: Incomplete | None = None, spatial_reference: Incomplete | None = None, mosaic_rule: Incomplete | None = None): ...
    def getVariableAttributes(self, variable_name): ...
    def getDimensionNames(self, variable_name): ...
    def getDimensionAttributes(self, variable_name, dimension_name): ...
    def getDimensionValues(self, variable_name, dimension_name): ...
    def renameVariable(self, current_variable_name, new_variable_name): ...
    def renameBand(self, current_band_name_or_index, new_band_name): ...
    def removeVariables(self, variable_names): ...
    def addDimension(self, variable, new_dimension_name, dimension_value, dimension_attributes: Incomplete | None = None): ...
    def appendSlices(self, mdRaster): ...
    def setVariableAttributes(self, variable_name, variable_attributes): ...
    def read(self, upper_left_corner=(0, 0), origin_coordinate: Incomplete | None = None, ncols: int = 0, nrows: int = 0, nodata_to_value: Incomplete | None = None, cell_size: Incomplete | None = None): ...
    def write(self, array, upper_left_corner=(0, 0), origin_coordinate: Incomplete | None = None, value_to_nodata: Incomplete | None = None): ...
    @property
    def hasTranspose(self): ...
    @property
    def RAT(self): ...
    def getColormap(self, variable_name: str = ''): ...
    def setColormap(self, color_map, variable_name: str = ''): ...
    def getStatistics(self, variable_name: str = ''): ...
    def setStatistics(self, statistics_obj, variable_name: str = ''): ...
    def getHistograms(self, variable_name: str = ''): ...
    def setHistograms(self, histogram_obj, variable_name: str = ''): ...
    def computeGSD(self, locations, spatial_reference: Incomplete | None = None, dem: Incomplete | None = None): ...
    def getProperty(self, property_name): ...
    def setProperty(self, property_name, property_value): ...
    def computeStatistics(self, variable: Incomplete | None = None, aoi: Incomplete | None = None, cellsize: Incomplete | None = None): ...
    def computeHistograms(self, variable: Incomplete | None = None, aoi: Incomplete | None = None, cellsize: Incomplete | None = None): ...
    def isConstant(self, value): ...
    def isEmpty(self): ...
    @staticmethod
    def fromSTACItem(stac_item, request_params: Incomplete | None = None, context: Incomplete | None = None): ...
