from . import CompoundParameter
from _typeshed import Incomplete

__all__ = ['TopoPointElevation', 'TopoContour', 'TopoStream', 'TopoSink', 'TopoBoundary', 'TopoLake']

class TopoInput: ...

class __TopoInputNestedList(TopoInput, CompoundParameter._CompoundParameter):
    inFeatures: Incomplete
    def __init__(self, keyword, inFeatures) -> None: ...

class __TopoInputList(TopoInput, CompoundParameter._CompoundParameter):
    inFeatures: Incomplete
    def __init__(self, keyword, inFeatures) -> None: ...

def TopoPointElevation(inFeatures): ...
def TopoContour(inFeatures): ...
def TopoStream(inFeatures): ...
def TopoSink(inFeatures): ...
def TopoBoundary(inFeatures): ...
def TopoLake(inFeatures): ...
