from arcpy import Extent as Extent, gp as gp

UNEVALUATED_RASTER_FUNCTION_SIGNAL: str

class StateSwapper:
    SingleRasterResult: int
    NoSingleRasterResult: int
    def __init__(self, outputCategory=...) -> None: ...
    def __call__(self, wrapper): ...

class ParameterErrors:
    def __init__(self) -> None: ...
    def add_id_message(self, severity: str, message_id: int, *args) -> None: ...
    def combine(self) -> str: ...
    def create_id_message(self, severity: str, message_id: int, *args) -> str: ...

def compoundParameterToString(parameter, cls): ...
def multiValueCompoundParameterToString(parameter, cls): ...
def isNumerical(object): ...
def flattenLists(iterable): ...
def argumentValueEqualsString(argument, string): ...
def useDefaultArgumentValue(argument): ...
