from _typeshed import Incomplete

__all__ = ['GetJSONTypeOBJ', 'GetClassFromCIM', 'ConstructTypeObject']

def GetClassFromCIM(class_name, module_name: Incomplete | None = None): ...
def ConstructTypeObject(type_class, default_none: bool = True): ...
def GetJSONTypeOBJ(json_obj): ...
