from enum import Enum

__all__ = ['WhatToExpect', 'GetCoreType', 'GetCIMArrayType', 'GetBasicArrayType', 'GetAttributeWithType', 'ChangeNoneTypeInEnum', 'ChangeBoolType', 'GetCimType', 'GetObjectFromType', 'GetCIMObject']

class WhatToExpect(Enum):
    CimType = 0
    BasicType = 1
    ArrayOfBasicType = 2
    ArrayOfCimType = 3
    UnknownToLog = 4
    ArrayOfUnknownToLog = 5

def GetCoreType(type_string): ...
def GetAttributeWithType(element, debug: bool = False): ...
def ChangeNoneTypeInEnum(obj, cls, attr_name, text) -> None: ...
def ChangeBoolType(obj, cls, attr_name, text) -> None: ...
def GetCimType(cls, element): ...
def GetObjectFromType(cls, expecting_type, element, debug: bool = False): ...
def GetCIMArrayType(cls, element): ...
def GetBasicArrayType(cls, element): ...
def GetCIMObject(cimdefinition): ...
