from _typeshed import Incomplete

__all__ = ['_BaseArcObject', '_ObjectWithoutInitCall', 'passthrough_attr', 'pass_parameterized_attr', 'FromScriptingArcObject']

class _ArcobjectPassthrough:
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, val): ...
    def __delattr__(self, attr): ...

class _BaseArcObject:
    def __init__(self, *args, **kwargs) -> None: ...

class _ObjectWithoutInitCall:
    @classmethod
    def __from_scripting_arc_object__(cls, wrap_object): ...

class _ObjectWithoutInitCallWrapper:
    @classmethod
    def __from_scripting_arc_object__(cls, wrap_object): ...

def passthrough_attr(attr_name, readonly: bool = False, doc: Incomplete | None = None): ...
def pass_parameterized_attr(attr_name, *args, **kwargs): ...
def FromScriptingArcObject(cls, obj): ...
