from _typeshed import Incomplete
from arcpy._mp import constants as _constants
from arcpy.arcobjects import mixins as mixins
from arcpy.arcobjects._base import _BaseArcObject, passthrough_attr as passthrough_attr
from arcpy.arcobjects.arcobjectconversion import convertArcObjectToPythonObject as convertArcObjectToPythonObject

class Annotation(_BaseArcObject):
    @_constants.maskargs
    def getGraphic(self, cim_version): ...
    def setGraphic(self, definition_object): ...

class ArcSDESQLExecute(mixins.ArcSDESQLExecuteMixin, _BaseArcObject):
    transactionAutoCommit: Incomplete
    def execute(self, *args): ...
    def startTransaction(self, *args): ...
    def rollbackTransaction(self, *args): ...
    def commitTransaction(self, *args): ...

class Array(mixins.ArrayMixin, _BaseArcObject):
    count: Incomplete
    def __next__(self, *args): ...
    def add(self, *args): ...
    def getObject(self, *args): ...
    def reset(self, *args): ...
    def next(self, *args): ...
    def remove(self, *args): ...
    def removeAll(self, *args): ...
    def insert(self, *args): ...
    def replace(self, *args): ...
    def clone(self, *args): ...

class Cursor(mixins.CursorMixin, _BaseArcObject):
    def __next__(self, *args): ...
    def reset(self, *args): ...
    def next(self, *args): ...
    def newRow(self, *args): ...
    def updateRow(self, *args): ...
    def insertRow(self, *args): ...
    def deleteRow(self, *args): ...

class Extent(mixins.ExtentMixin, _BaseArcObject):
    XMin: Incomplete
    YMin: Incomplete
    XMax: Incomplete
    YMax: Incomplete
    MMin: Incomplete
    MMax: Incomplete
    ZMin: Incomplete
    ZMax: Incomplete
    width: Incomplete
    height: Incomplete
    depth: Incomplete
    lowerLeft: Incomplete
    lowerRight: Incomplete
    upperLeft: Incomplete
    upperRight: Incomplete
    spatialReference: Incomplete
    geohash: Incomplete
    geohashNeighbors: Incomplete
    geohashCovers: Incomplete
    polygon: Incomplete
    JSON: Incomplete
    def contains(self, second_geometry, relation=None): ...
    def crosses(self, second_geometry): ...
    def disjoint(self, second_geometry): ...
    def equals(self, second_geometry): ...
    def overlaps(self, second_geometry): ...
    def touches(self, second_geometry): ...
    def within(self, second_geometry, relation=None): ...
    def projectAs(self, spatial_reference, transformation_name=None): ...

class FeatureSet(mixins.FeatureSetMixin, _BaseArcObject):
    JSON: Incomplete
    GeoJSON: Incomplete
    def load(self, *args, **kwargs): ...
    def save(self, *args): ...

class Field(mixins.FieldMixin, _BaseArcObject):
    name: Incomplete
    aliasName: Incomplete
    baseName: Incomplete
    domain: Incomplete
    type: Incomplete
    length: Incomplete
    precision: Incomplete
    scale: Incomplete
    editable: Incomplete
    isNullable: Incomplete
    required: Incomplete
    defaultValue: Incomplete

class FieldInfo(mixins.FieldInfoMixin, _BaseArcObject):
    count: Incomplete
    def addField(self, *args): ...
    def getFieldName(self, *args): ...
    def getNewName(self, *args): ...
    def getSplitRule(self, *args): ...
    def getVisible(self, *args): ...
    def setFieldName(self, *args): ...
    def setNewName(self, *args): ...
    def setSplitRule(self, *args): ...
    def setVisible(self, *args): ...
    def removeField(self, *args): ...
    def findFieldByName(self, *args): ...
    def findFieldByNewName(self, *args): ...
    def loadFromString(self, *args): ...
    def exportToString(self, *args): ...

class FieldMap(mixins.FieldMapMixin, _BaseArcObject):
    mergeRule: Incomplete
    outputField: Incomplete
    joinDelimiter: Incomplete
    inputFieldCount: Incomplete
    def addInputField(self, *args): ...
    def getInputTableName(self, *args): ...
    def getInputFieldName(self, *args): ...
    def getStartTextPosition(self, *args): ...
    def getEndTextPosition(self, *args): ...
    def removeAll(self, *args): ...
    def removeInputField(self, *args): ...
    def findInputFieldIndex(self, *args): ...
    def setStartTextPosition(self, *args): ...
    def setEndTextPosition(self, *args): ...

class FieldMappings(mixins.FieldMappingsMixin, _BaseArcObject):
    fieldValidationWorkspace: Incomplete
    fieldCount: Incomplete
    fields: Incomplete
    fieldMappings: Incomplete
    def addTable(self, *args): ...
    def removeAll(self, *args): ...
    def addFieldMap(self, *args): ...
    def getFieldMap(self, *args): ...
    def replaceFieldMap(self, *args): ...
    def removeFieldMap(self, *args): ...
    def findFieldMapIndex(self, *args): ...
    def loadFromString(self, *args): ...
    def exportToString(self, *args): ...

class Filter(_BaseArcObject):
    type: Incomplete
    list: Incomplete
    filters: Incomplete
    def __getitem__(self, key): ...

class GeoProcessor(_BaseArcObject):
    messageCount: Incomplete
    maxSeverity: Incomplete
    parameterCount: Incomplete
    toolbox: Incomplete
    overwriteOutput: Incomplete
    overwriteOutputOptions: Incomplete
    useCompatibleFieldTypes: Incomplete
    logHistory: Incomplete
    logLineage: Incomplete
    scriptVersion: Incomplete
    severityLevel: Incomplete
    def getInstallInfo(self, *args): ...
    def listInstallations(self, *args): ...
    def setProgressor(self, *args): ...
    def resetProgressor(self, *args): ...
    def setProgressorLabel(self, *args): ...
    def setProgressorPosition(self, *args): ...
    def resetEnvironments(self, *args): ...
    def clearEnvironment(self, *args): ...
    def getMessage(self, *args): ...
    def getSeverity(self, *args): ...
    def getReturnCode(self, *args): ...
    def getMessages(self, *args): ...
    def getAllMessages(self, *args): ...
    def addMessage(self, *args): ...
    def addIDMessage(self, *args): ...
    def getIDMessage(self, *args): ...
    def addError(self, *args): ...
    def addWarning(self, *args): ...
    def addReturnMessage(self, *args): ...
    def productInfo(self, *args): ...
    def setProduct(self, *args): ...
    def checkProduct(self, *args): ...
    def checkOutExtension(self, *args): ...
    def checkInExtension(self, *args): ...
    def checkExtension(self, *args): ...
    def getParameterAsText(self, *args): ...
    def setParameterAsText(self, *args): ...
    def getParameter(self, *args): ...
    def setParameter(self, *args): ...
    def copyParameter(self, *args): ...
    def setParameterSymbology(self, *args): ...
    def listFiles(self, *args): ...
    def listTools(self, *args): ...
    def listEnvironments(self, *args): ...
    def listToolboxes(self, *args): ...
    def addToolbox(self, *args): ...
    def removeToolbox(self, *args): ...
    def getSystemEnvironment(self, *args): ...
    def command(self, *args): ...
    def usage(self, *args): ...
    def exists(self, *args): ...
    def listFeatureClasses(self, *args): ...
    def listDatasets(self, *args): ...
    def listTables(self, *args): ...
    def listRasters(self, *args): ...
    def listRasterProducts(self, *args): ...
    def listWorkspaces(self, *args): ...
    def listVersions(self, *args): ...
    def listUsers(self, *args): ...
    def disconnectUser(self, *args): ...
    def listFields(self, *args): ...
    def listIndexes(self, *args): ...
    def searchCursor(self, *args): ...
    def updateCursor(self, *args): ...
    def insertCursor(self, *args): ...
    def describe(self, *args): ...
    def createObject(self, *args): ...
    def validateFieldName(self, *args): ...
    def validateTableName(self, *args): ...
    def parseFieldName(self, *args): ...
    def parseTableName(self, *args): ...
    def createScratchName(self, *args): ...
    def createUniqueName(self, *args): ...
    def testSchemaLock(self, *args): ...
    def createRandomValueGenerator(self, *args): ...
    def isSynchronous(self, *args): ...
    def getParameterCount(self, *args): ...
    def getParameterValue(self, *args): ...
    def getParameterInfo(self, *args): ...
    def addFieldDelimiters(self, *args): ...
    def listPrinterNames(self, *args): ...
    def wildcardMatch(self, *args): ...
    def alterAliasName(self, *args): ...
    def listSpatialReferences(self, *args): ...
    def listTransformations(self, *args): ...
    def acceptConnections(self, *args): ...
    def logUsageMetering(self, *args): ...
    def createGPSDDraft(self, *args): ...
    def fromEsriJson(self, *args): ...
    def listDataStoreItems(self, *args): ...
    def validateDataStoreItem(self, *args): ...
    def removeDataStoreItem(self, *args): ...
    def addDataStoreItem(self, *args): ...
    def getSigninToken(self, *args): ...
    def getActivePortalURL(self, *args): ...
    def listPortalURLs(self, *args): ...
    def getPortalDescription(self, *args): ...
    def getPortalInfo(self, *args): ...
    def decryptPYT(self, *args): ...
    def encryptPYT(self, *args): ...

class Geometry(mixins.GeometrySpecializationMixin, _BaseArcObject):
    labelPoint: Incomplete
    type: Incomplete
    extent: Incomplete
    trueCentroid: Incomplete
    firstPoint: Incomplete
    lastPoint: Incomplete
    isMultipart: Incomplete
    hullRectangle: Incomplete
    area: Incomplete
    length: Incomplete
    length3D: Incomplete
    partCount: Incomplete
    pointCount: Incomplete
    centroid: Incomplete
    WKB: Incomplete
    WKT: Incomplete
    spatialReference: Incomplete
    JSON: Incomplete
    hasCurves: Incomplete
    def __getSVG__(self, scale_factor: float = 1.0, color=None): ...
    def getPart(self, *args): ...
    def contains(self, second_geometry, relation=None): ...
    def crosses(self, second_geometry): ...
    def disjoint(self, second_geometry): ...
    def equals(self, second_geometry): ...
    def overlaps(self, second_geometry): ...
    def touches(self, second_geometry): ...
    def within(self, second_geometry, relation=None): ...
    def projectAs(self, spatial_reference, transformation_name=None): ...
    def positionAlongLine(self, value, use_percentage: bool = False, geodesic: bool = False): ...
    def queryPointAndDistance(self, in_point, use_percentage: bool = False): ...
    def snapToLine(self, in_point): ...
    def measureOnLine(self, in_point, use_percentage: bool = False): ...
    def generalize(self, distance): ...
    def getLength(self, method: str = 'GEODESIC', units=None): ...
    def getArea(self, method: str = 'GEODESIC', units=None): ...
    def getGeohash(self, precision: int = 8): ...
    def segmentAlongLine(self, start_measure, end_measure, use_percentage: bool = False): ...
    def angleAndDistanceTo(self, other_geometry, method: str = 'GEODESIC'): ...
    def pointFromAngleAndDistance(self, angle, distance, method: str = 'GEODESIC'): ...
    def boundary(self): ...
    def buffer(self, distance): ...
    def clip(self, envelope): ...
    def convexHull(self): ...
    def difference(self, other): ...
    def intersect(self, other, dimension): ...
    def symmetricDifference(self, other): ...
    def union(self, other): ...
    def distanceTo(self, other): ...
    def cut(self, other): ...
    def densify(self, method, distance: int = 0, deviation=None): ...
    def move(self, dx: float = 0.0, dy: float = 0.0, dz=None): ...
    def scale(self, origin=None, sx: float = 1.0, sy: float = 1.0, sz=None): ...
    def rotate(self, origin=None, rotation_angle: float = 0.0): ...
    def reverseOrientation(self): ...

class Index(_BaseArcObject):
    name: Incomplete
    isAscending: Incomplete
    isFullText: Incomplete
    isUnique: Incomplete
    fields: Incomplete

class NetCDFFileProperties(mixins.NetCDFFilePropertiesMixin, _BaseArcObject):
    def getAttributeNames(self, *args): ...
    def getAttributeValue(self, *args): ...
    def getDimensionIndex(self, *args): ...
    def getDimensions(self, *args): ...
    def getDimensionsByVariable(self, *args): ...
    def getDimensionSize(self, *args): ...
    def getDimensionValue(self, *args): ...
    def getFieldType(self, *args): ...
    def getSpatialReference(self, *args): ...
    def getVariables(self, *args): ...
    def getVariablesByDimension(self, *args): ...

class Parameter(mixins.ParameterMixin, _BaseArcObject):
    name: Incomplete
    displayName: Incomplete
    displayOrder: Incomplete
    direction: Incomplete
    datatype: Incomplete
    charts: Incomplete
    parameterType: Incomplete
    parameterDependencies: Incomplete
    enabled: Incomplete
    value: Incomplete
    defaultEnvironmentName: Incomplete
    altered: Incomplete
    hasBeenValidated: Incomplete
    category: Incomplete
    schema: Incomplete
    filter: Incomplete
    filters: Incomplete
    symbology: Incomplete
    message: Incomplete
    multiValue: Incomplete
    columns: Incomplete
    keys: Incomplete
    valueAsText: Incomplete
    values: Incomplete
    controlCLSID: Incomplete
    def setErrorMessage(self, *args): ...
    def setWarningMessage(self, *args): ...
    def setIDMessage(self, *args): ...
    def clearMessage(self, *args): ...
    def hasError(self, *args): ...
    def hasWarning(self, *args): ...
    def isInputValueDerived(self, *args): ...

class Point(mixins.PointMixin, _BaseArcObject):
    X: Incomplete
    Y: Incomplete
    M: Incomplete
    Z: Incomplete
    ID: Incomplete
    def clone(self, *args): ...
    def contains(self, second_geometry, relation=None): ...
    def crosses(self, second_geometry): ...
    def disjoint(self, second_geometry): ...
    def equals(self, second_geometry): ...
    def overlaps(self, second_geometry): ...
    def touches(self, second_geometry): ...
    def within(self, second_geometry, relation=None): ...

class RandomNumberGenerator(_BaseArcObject):
    def loadFromString(self, *args): ...
    def exportToString(self, *args): ...

class RecordSet(mixins.RecordSetMixin, _BaseArcObject):
    JSON: Incomplete
    def load(self, *args, **kwargs): ...
    def save(self, *args): ...

class Result(mixins.ResultMixin, _BaseArcObject):
    status: Incomplete
    resultID: Incomplete
    messageCount: Incomplete
    maxSeverity: Incomplete
    outputCount: Incomplete
    inputCount: Incomplete
    def getMessage(self, *args): ...
    def getMessages(self, *args): ...
    def getCharts(self, wildcard=None): ...
    def getAllMessages(self, *args): ...
    def getSeverity(self, *args): ...
    def getOutput(self, *args): ...
    def getInput(self, *args): ...
    def getMapImageURL(self, *args): ...
    def cancel(self, *args): ...
    def saveToFile(self, *args): ...

class Row(_BaseArcObject):
    __passthrough_to_ao__: bool
    def setValue(self, *args): ...
    def getValue(self, *args): ...
    def setNull(self, *args): ...
    def isNull(self, *args): ...

class Schema(_BaseArcObject):
    type: Incomplete
    clone: Incomplete
    featureTypeRule: Incomplete
    featureType: Incomplete
    geometryTypeRule: Incomplete
    geometryType: Incomplete
    extentRule: Incomplete
    extent: Incomplete
    fieldsRule: Incomplete
    additionalFields: Incomplete
    cellSizeRule: Incomplete
    cellSize: Incomplete
    rasterRule: Incomplete
    rasterFormatRule: Incomplete
    additionalChildren: Incomplete

class SpatialReference(mixins.SpatialReferenceMixin, _BaseArcObject):
    type: Incomplete
    name: Incomplete
    alias: Incomplete
    abbreviation: Incomplete
    remarks: Incomplete
    factoryCode: Incomplete
    PCSName: Incomplete
    PCSCode: Incomplete
    GCSName: Incomplete
    GCSCode: Incomplete
    spheroidName: Incomplete
    spheroidCode: Incomplete
    projectionName: Incomplete
    projectionCode: Incomplete
    datumName: Incomplete
    datumCode: Incomplete
    primeMeridianName: Incomplete
    primeMeridianCode: Incomplete
    angularUnitName: Incomplete
    angularUnitCode: Incomplete
    linearUnitName: Incomplete
    linearUnitCode: Incomplete
    hasXYPrecision: Incomplete
    hasZPrecision: Incomplete
    hasMPrecision: Incomplete
    falseOriginAndUnits: Incomplete
    ZFalseOriginAndUnits: Incomplete
    MFalseOriginAndUnits: Incomplete
    domain: Incomplete
    ZDomain: Incomplete
    MDomain: Incomplete
    usage: Incomplete
    centralMeridian: Incomplete
    centralMeridianInDegrees: Incomplete
    longitudeOfOrigin: Incomplete
    latitudeOfOrigin: Incomplete
    latitudeOf1st: Incomplete
    latitudeOf2nd: Incomplete
    falseEasting: Incomplete
    falseNorthing: Incomplete
    centralParallel: Incomplete
    standardParallel1: Incomplete
    standardParallel2: Incomplete
    longitudeOf1st: Incomplete
    longitudeOf2nd: Incomplete
    scaleFactor: Incomplete
    azimuth: Incomplete
    semiMajorAxis: Incomplete
    semiMinorAxis: Incomplete
    flattening: Incomplete
    longitude: Incomplete
    radiansPerUnit: Incomplete
    metersPerUnit: Incomplete
    GCS: Incomplete
    isHighPrecision: Incomplete
    XYTolerance: Incomplete
    MTolerance: Incomplete
    ZTolerance: Incomplete
    XYResolution: Incomplete
    MResolution: Incomplete
    ZResolution: Incomplete
    classification: Incomplete
    VCS: Incomplete
    def setFalseOriginAndUnits(self, *args): ...
    def setZFalseOriginAndUnits(self, *args): ...
    def setMFalseOriginAndUnits(self, *args): ...
    def setDomain(self, *args): ...
    def setZDomain(self, *args): ...
    def setMDomain(self, *args): ...
    def createFromFile(self, *args): ...
    def create(self, *args): ...
    def loadFromString(self, *args): ...
    def exportToString(self, *args, **kwargs): ...

class Value(_BaseArcObject):
    value: Incomplete
    isEmpty: Incomplete

class ValueTable(mixins.ValueTableMixin, _BaseArcObject):
    rowCount: Incomplete
    columnCount: Incomplete
    def setColumns(self, *args): ...
    def addColumns(self, *args): ...
    def addRow(self, *args): ...
    def getRow(self, *args): ...
    def getTrueRow(self, *args): ...
    def getValue(self, *args): ...
    def getTrueValue(self, *args): ...
    def loadFromString(self, *args): ...
    def exportToString(self, *args): ...
    def removeRow(self, *args): ...
    def setRow(self, *args): ...
    def setValue(self, *args): ...
