from _typeshed import Incomplete
from arcpy.arcobjects.arcobjects import Geometry

__all__ = ['Annotation', 'Dimension', 'Multipatch', 'Multipoint', 'PointGeometry', 'Polygon', 'Polyline', 'AsShape', 'FromCoordString', 'GenerateOptimalCoordinateSystem']

class Annotation(Geometry):
    __type_string__: str

class Dimension(Geometry):
    __type_string__: str

class Multipatch(Geometry):
    __type_string__: str

class Multipoint(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...
    def __getSVG__(self, scale_factor: float = 1.0, fill_color: Incomplete | None = None): ...

class PointGeometry(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    @property
    def __geo_interface__(self): ...
    def __getSVG__(self, scale_factor: int = 1, fill_color: Incomplete | None = None): ...
    def toCoordString(self, notation): ...

class Polygon(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...
    def __getSVG__(self, scale_factor: int = 1, fill_color: Incomplete | None = None): ...

class Polyline(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...
    def __getSVG__(self, scale_factor: int = 1, stroke_color: Incomplete | None = None): ...

def AsShape(geojson_struct, esri_json: bool = False): ...
def FromCoordString(coordinate_str, notation): ...
def GenerateOptimalCoordinateSystem(extent, property, custom_name: Incomplete | None = None): ...
