from arcpy.arcobjects.arcobjects import Geometry

__all__ = ['Dimension', 'Multipatch', 'Multipoint', 'PointGeometry', 'Polygon', 'Polyline', 'AsShape', 'FromCoordString', 'GenerateOptimalCoordinateSystem']

class Dimension(Geometry):
    __type_string__: str

class Multipatch(Geometry):
    __type_string__: str

class Multipoint(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference=None, has_z=None, has_m=None, has_id=None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...

class PointGeometry(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference=None, has_z=None, has_m=None, has_id=None) -> None: ...
    @property
    def __geo_interface__(self): ...
    def toCoordString(self, notation): ...

class Polygon(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference=None, has_z=None, has_m=None, has_id=None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...

class Polyline(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference=None, has_z=None, has_m=None, has_id=None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...

def AsShape(geojson_struct, esri_json: bool = False): ...
def FromCoordString(coordinate_str, notation): ...
def GenerateOptimalCoordinateSystem(extent, property, custom_name=None): ...
