from _typeshed import Incomplete
from arcpy.arcobjects.arcobjects import Geometry

__all__ = ['Dimension', 'Multipatch', 'Multipoint', 'PointGeometry', 'Polygon', 'Polyline', 'AsShape', 'FromCoordString', 'GenerateOptimalCoordinateSystem']

class Dimension(Geometry):
    __type_string__: str

class Multipatch(Geometry):
    __type_string__: str

class Multipoint(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...

class PointGeometry(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    @property
    def __geo_interface__(self): ...
    def toCoordString(self, notation): ...

class Polygon(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...

class Polyline(Geometry):
    __type_string__: str
    def __init__(self, inputs, spatial_reference: Incomplete | None = None, has_z: Incomplete | None = None, has_m: Incomplete | None = None, has_id: Incomplete | None = None) -> None: ...
    def __iter__(self): ...
    @property
    def __geo_interface__(self): ...

def AsShape(geojson_struct, esri_json: bool = False): ...
def FromCoordString(coordinate_str, notation): ...
def GenerateOptimalCoordinateSystem(extent, property, custom_name: Incomplete | None = None): ...
