from _typeshed import Incomplete
from typing import NamedTuple

__all__ = ['ArrayMixin', 'CursorMixin', 'GeometrySpecializationMixin', 'PointMixin', 'ResultMixin']

class pagesize_tuple(NamedTuple):
    width: Incomplete
    height: Incomplete

class bookmark_tuple(NamedTuple):
    name: Incomplete
    extent: Incomplete

class webmap_tuple(NamedTuple):
    mapDocument: Incomplete
    DPI: Incomplete
    outputSizeHeight: Incomplete
    outputSizeWidth: Incomplete

class CursorMixin:
    def __iter__(self): ...

class ArrayMixin:
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, index, value) -> None: ...
    def __init__(self, items=[]) -> None: ...
    def append(self, value) -> None: ...
    def extend(self, values) -> None: ...

class GeometrySpecializationMixin:
    __type_mapping__: Incomplete
    class _passthrough: ...
    @classmethod
    def __from_scripting_arc_object__(cls, obj): ...
    __type_string__: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __add__(self, other): ...
    def __or__(self, other): ...
    def __sub__(self, other): ...
    def __xor__(self, other): ...
    def __reduce__(self): ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __len__(self) -> int: ...

class ParameterMixin:
    def __init__(self, name: Incomplete | None = None, displayName: Incomplete | None = None, direction: Incomplete | None = None, datatype: Incomplete | None = None, parameterType: Incomplete | None = None, enabled: Incomplete | None = None, category: Incomplete | None = None, symbology: Incomplete | None = None, multiValue: Incomplete | None = None) -> None: ...

class ArcSDESQLExecuteMixin:
    def __init__(self, server: Incomplete | None = None, instance: Incomplete | None = None, database: Incomplete | None = None, user: Incomplete | None = None, password: Incomplete | None = None) -> None: ...

class NetCDFFilePropertiesMixin:
    def __init__(self, netcdffile: Incomplete | None = None) -> None: ...

class SpatialReferenceMixin:
    def __init__(self, item: Incomplete | None = None, vcs: int = -1, text: Incomplete | None = None) -> None: ...
    def __reduce__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class FieldMappingsMixin:
    def __init__(self) -> None: ...
    def __iter__(self): ...

class FieldMapMixin:
    def __init__(self) -> None: ...

class FieldMixin:
    def __init__(self) -> None: ...

class ExtentMixin:
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class ValueTableMixin:
    def __init__(self, columns: Incomplete | None = None) -> None: ...

class FieldInfoMixin:
    def __init__(self) -> None: ...

class FeatureSetMixin:
    def __init__(self, *args, **kwargs) -> None: ...

class RecordSetMixin:
    def __init__(self, *args, **kwargs) -> None: ...

class PointMixin:
    def __init__(self, X: Incomplete | None = None, Y: Incomplete | None = None, Z: Incomplete | None = None, M: Incomplete | None = None, ID: Incomplete | None = None) -> None: ...

class ResultMixin:
    def __init__(self, toolname: str = '', resultID: str = '') -> None: ...
    def __unicode__(self): ...
    def __getitem__(self, key): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
