__all__ = ['UtilityNetwork']

class UtilityNetwork:
    def __init__(self, utilityNetworkPath) -> None: ...
    def HasValidNetworkTopology(self) -> bool: ...
    def AddConnectivityAssociation(self, association_type: int, from_table: str, from_global_id: str, from_terminal_name: str, to_table: str, to_global_id: str, to_terminal_name: str, percent_along: float) -> int: ...
    def AddContainmentAssociation(self, container_table: str, container_global_id: str, content_table: str, content_global_id: str, is_content_visible: bool) -> int: ...
    def AddStructuralAttachmentAssociation(self, structure_table: str, structure_global_id: str, attachment_table: str, attachment_global_id: str) -> int: ...
    def DeleteConnectivityAssociation(self, association_type: int, association_global_id: str): ...
    def DeleteContainmentAssociation(self, association_global_id: str): ...
    def DeleteStructuralAttachmentAssociation(self, association_global_id: str): ...
    def DisableSubnetworkController(self, table: str, global_id: str, terminal_name: str): ...
    def EnableSubnetworkController(self, table: str, global_id: str, terminal_name: str, subnetwork_controller_name: str, subnetwork_name: str, tier_name: str, description: str, notes: str) -> int: ...
