import types
from contextlib import ContextDecorator

__all__ = ['LogHistory', 'LogMetadata', 'SeverityLevel']

class StateManager(ContextDecorator):
    def __init__(self, prop: str, val: bool | int) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc): ...

class LogHistory(StateManager):
    def __init__(self, log_history: bool) -> None: ...

class LogMetadata(StateManager):
    def __init__(self, log_metadata: bool) -> None: ...

class SeverityLevel(StateManager):
    def __init__(self, severity_level: int) -> None: ...
